const K = 'color: var(--accent-violet)';
const S = 'color: var(--accent-cyan)';
const N = 'color: var(--accent-amber)';
const C = 'color: var(--text-tertiary)';

export default {
  id: "algo",
  subject: "Algoritmos",
  tone: "violet",
  title: "Recursión y complejidad",
  description: "Piensa como computador: análisis de complejidad, recursión y los algoritmos clásicos.",
  order: 3,
  prereq: null,
  units: [
    {
      id: "algo-u1",
      name: "Unidad 1 · Pensamiento algorítmico",
      lessons: [
        {
          id: "algo-l1",
          title: "Qué es un algoritmo",
          mins: 12,
          content: [
            { type: "p", html: "Un <code>algoritmo</code> es una secuencia finita y ordenada de pasos precisos que resuelve un problema o realiza una tarea. Para que sea válido, cada paso debe ser claro y no ambiguo, y el proceso debe terminar después de un número finito de pasos." },
            { type: "p", html: "Un mismo problema puede resolverse con distintos algoritmos: para ordenar una lista existen decenas de estrategias. Elegir un buen algoritmo importa tanto como escribir código correcto: uno ineficiente puede tardar horas donde uno eficiente tarda segundos." },
            { type: "code", lines: [
              `<span style="${C}">// Algoritmo: encontrar el mayor de tres números</span>`,
              `<span style="${K}">INICIO</span>`,
              `  <span style="${K}">LEER</span> a, b, c`,
              `  <span style="${K}">SI</span> a &gt;= b <span style="${K}">Y</span> a &gt;= c <span style="${K}">ENTONCES</span>`,
              `    <span style="${K}">ESCRIBIR</span> a`,
              `  <span style="${K}">SINO SI</span> b &gt;= c <span style="${K}">ENTONCES</span>`,
              `    <span style="${K}">ESCRIBIR</span> b`,
              `  <span style="${K}">SINO</span>`,
              `    <span style="${K}">ESCRIBIR</span> c`,
              `  <span style="${K}">FIN SI</span>`,
              `<span style="${K}">FIN</span>`,
            ]},
            { type: "note", text: "Antes de escribir código, traza el algoritmo a mano con un ejemplo pequeño: si no puedes explicar cada paso en papel, tampoco podrás traducirlo correctamente a un lenguaje de programación." },
          ],
          quiz: {
            question: "¿Cuál de estas características es obligatoria para que una secuencia de pasos se considere un algoritmo?",
            options: [
              "Debe terminar después de un número finito de pasos",
              "Debe estar escrita en un lenguaje de programación concreto",
              "Debe tardar menos de un segundo en ejecutarse",
              "Debe usar únicamente operaciones aritméticas",
            ],
            correct: 0,
            ok: "Un algoritmo debe ser finito: tiene que terminar tras una cantidad limitada de pasos, sin importar el lenguaje o la velocidad de ejecución.",
            bad: "Un algoritmo puede describirse en pseudocódigo sin lenguaje concreto, puede tardar más de un segundo, y puede incluir operaciones distintas a las aritméticas; lo obligatorio es que termine.",
          },
          extra: {
            type: "match",
            prompt: "Empareja cada término con su definición.",
            payload: {
              left: ["Algoritmo", "Entrada", "Salida", "Paso"],
              right: [
                "Una instrucción individual y no ambigua dentro de la secuencia del algoritmo",
                "Resultado que el algoritmo produce al terminar de ejecutarse",
                "Secuencia finita y ordenada de instrucciones precisas que resuelve un problema",
                "Dato que el algoritmo recibe antes de empezar a procesar",
              ],
            },
            answer: { pairs: [[0, 2], [1, 3], [2, 1], [3, 0]] },
            ok: "Un algoritmo es la secuencia completa de pasos; la entrada es lo que recibe, la salida lo que produce, y un paso es cada instrucción individual dentro de esa secuencia.",
            bad: "No confundas el todo (algoritmo) con sus partes: un paso es una instrucción, la entrada es lo que recibe y la salida lo que produce.",
          },
        },
        {
          id: "algo-l2",
          title: "Pseudocódigo",
          mins: 14,
          content: [
            { type: "p", html: "El <code>pseudocódigo</code> describe un algoritmo con una notación intermedia entre el lenguaje natural y un lenguaje de programación real: usa palabras clave estructuradas (<code>SI</code>, <code>MIENTRAS</code>, <code>PARA</code>) sin atarse a la sintaxis exacta de ningún lenguaje concreto." },
            { type: "p", html: "Escribir primero en pseudocódigo permite concentrarte en la lógica del algoritmo sin distraerte con detalles de sintaxis (punto y coma, llaves, tipos); después puedes traducirlo a Java, Python o cualquier otro lenguaje." },
            { type: "code", lines: [
              `<span style="${C}">// Suma los números del 1 al n</span>`,
              `<span style="${K}">FUNCION</span> sumarHastaN(n)`,
              `  suma &lt;- <span style="${N}">0</span>`,
              `  <span style="${K}">PARA</span> i <span style="${K}">DESDE</span> <span style="${N}">1</span> <span style="${K}">HASTA</span> n <span style="${K}">HACER</span>`,
              `    suma &lt;- suma + i`,
              `  <span style="${K}">FIN PARA</span>`,
              `  <span style="${K}">DEVOLVER</span> suma`,
              `<span style="${K}">FIN FUNCION</span>`,
            ]},
            { type: "note", text: "El símbolo <- representa la asignación: la variable toma el valor de la expresión de la derecha, igual que = en Java pero sin la ambigüedad de la comparación de igualdad." },
          ],
          quiz: {
            question: "¿Cuál es la principal ventaja de escribir primero un algoritmo en pseudocódigo antes de programarlo en Java?",
            options: [
              "El pseudocódigo se ejecuta directamente en la JVM sin compilar",
              "El pseudocódigo es un lenguaje de programación oficial de Java",
              "Permite concentrarte en la lógica del algoritmo sin la sintaxis exacta de un lenguaje concreto",
              "El pseudocódigo elimina la necesidad de probar el algoritmo",
            ],
            correct: 2,
            ok: "El pseudocódigo no se ejecuta ni pertenece a ningún lenguaje: es una herramienta de diseño que te deja pensar en los pasos antes de preocuparte por la sintaxis.",
            bad: "El pseudocódigo no se ejecuta en la JVM, no es un lenguaje oficial de Java, y no reemplaza las pruebas; su valor está en separar el diseño de la sintaxis.",
          },
          extra: {
            type: "order",
            prompt: "Ordena las líneas para construir el pseudocódigo que encuentra el mayor de dos números a y b.",
            payload: {
              lines: [
                { id: "c", html: `  <span style="${K}">SI</span> a &gt; b <span style="${K}">ENTONCES</span> <span style="${K}">ESCRIBIR</span> a <span style="${K}">SINO</span> <span style="${K}">ESCRIBIR</span> b <span style="${K}">FIN SI</span>` },
                { id: "a", html: `<span style="${K}">INICIO</span>` },
                { id: "d", html: `<span style="${K}">FIN</span>` },
                { id: "b", html: `  <span style="${K}">LEER</span> a, b` },
              ],
            },
            answer: { order: ["a", "b", "c", "d"] },
            ok: "El algoritmo primero declara el inicio, luego lee las dos entradas, después compara y escribe la mayor, y por último declara el fin.",
            bad: "Sin LEER las entradas antes de compararlas no hay datos que evaluar, y FIN siempre cierra el algoritmo: no puede ir antes de INICIO ni de la comparación.",
          },
        },
        {
          id: "algo-l3",
          title: "Trazas de ejecución",
          mins: 16,
          content: [
            { type: "p", html: "Una <code>traza de ejecución</code> consiste en seguir manualmente, paso a paso, cómo cambian las variables de un algoritmo mientras se ejecuta. Es la herramienta más confiable para verificar si un algoritmo hace lo que crees que hace, antes incluso de escribir código." },
            { type: "code", lines: [
              `<span style="${K}">int</span> resultado = <span style="${N}">1</span>;`,
              `<span style="${K}">for</span> (<span style="${K}">int</span> i = <span style="${N}">1</span>; i &lt;= <span style="${N}">4</span>; i++) {`,
              `  resultado = resultado * i;`,
              `}`,
            ]},
            { type: "p", html: "Al trazar este bucle: en i=1, resultado pasa de 1 a 1; en i=2, pasa a 2; en i=3, pasa a 6; en i=4, pasa a 24. Cuando i llega a 5, la condición <code>i &lt;= 4</code> es falsa y el bucle termina." },
          ],
          quiz: {
            question: "Al trazar el bucle for (int i = 1; i <= 4; i++) resultado = resultado * i; con resultado inicial 1, ¿qué valor tiene resultado cuando el bucle termina?",
            options: [
              "1, porque resultado nunca cambia dentro del bucle",
              "10, la suma de 1+2+3+4",
              "4, el último valor de i",
              "24, el resultado de multiplicar 1×2×3×4",
            ],
            correct: 3,
            ok: "El bucle multiplica resultado por cada i de 1 a 4: 1×1×2×3×4 = 24, el factorial de 4.",
            bad: "El bucle multiplica, no suma, así que no da 10; resultado sí cambia en cada vuelta y termina en 24, no en el último valor de i ni en su valor inicial.",
          },
          extra: {
            type: "order",
            prompt: "Traza este bucle: int contador = 0; for (int i = 1; i <= 4; i++) { contador = contador + i; } Ordena los valores que toma contador, desde el inicial hasta el último.",
            payload: {
              lines: [
                { id: "c", html: `<span style="${C}">// contador = 3 (tras i = 2)</span>` },
                { id: "a", html: `<span style="${C}">// contador = 0 (valor inicial, antes del bucle)</span>` },
                { id: "e", html: `<span style="${C}">// contador = 10 (tras i = 4)</span>` },
                { id: "b", html: `<span style="${C}">// contador = 1 (tras i = 1)</span>` },
                { id: "d", html: `<span style="${C}">// contador = 6 (tras i = 3)</span>` },
              ],
            },
            answer: { order: ["a", "b", "c", "d", "e"] },
            ok: "contador empieza en 0; en cada vuelta se le suma el i actual: tras i=1 vale 1, tras i=2 vale 3 (1+2), tras i=3 vale 6 (3+3), tras i=4 vale 10 (6+4).",
            bad: "La secuencia es acumulativa: cada vuelta suma el i actual al valor previo de contador, no al valor inicial; no puedes saltarte un valor intermedio.",
          },
        },
        {
          id: "algo-l4",
          title: "Notación Big O",
          mins: 20,
          content: [
            { type: "p", html: "La <code>notación Big O</code> describe cómo crece el tiempo (o la memoria) que necesita un algoritmo a medida que crece el tamaño de la entrada <code>n</code>, ignorando constantes y términos de menor orden. Es una forma de comparar algoritmos sin depender de la velocidad de una computadora concreta." },
            { type: "p", html: "Órdenes comunes, de mejor a peor: <code>O(1)</code> (constante, no depende de n), <code>O(log n)</code> (logarítmico), <code>O(n)</code> (lineal), <code>O(n log n)</code>, <code>O(n²)</code> (cuadrático) y <code>O(2ⁿ)</code> (exponencial)." },
            { type: "code", lines: [
              `<span style="${C}">// O(1): acceso directo, no depende del tamaño del arreglo</span>`,
              `<span style="${K}">int</span> primero = arreglo[<span style="${N}">0</span>];`,
              ``,
              `<span style="${C}">// O(n): recorre todo el arreglo una vez</span>`,
              `<span style="${K}">for</span> (<span style="${K}">int</span> x : arreglo) {`,
              `  <span style="${S}">System</span>.out.println(x);`,
              `}`,
              ``,
              `<span style="${C}">// O(n²): un bucle anidado dentro de otro</span>`,
              `<span style="${K}">for</span> (<span style="${K}">int</span> i = <span style="${N}">0</span>; i &lt; arreglo.length; i++) {`,
              `  <span style="${K}">for</span> (<span style="${K}">int</span> j = <span style="${N}">0</span>; j &lt; arreglo.length; j++) {`,
              `    <span style="${S}">System</span>.out.println(arreglo[i] + arreglo[j]);`,
              `  }`,
              `}`,
            ]},
            { type: "note", text: "Para comparar dos algoritmos con Big O, fíjate en el término dominante cuando n crece mucho: O(n² + 100n) se simplifica a O(n²), porque el término cuadrático domina sobre el lineal." },
          ],
          quiz: {
            question: "El tercer fragmento anida un for dentro de otro, ambos recorriendo el arreglo completo. ¿Qué complejidad Big O tiene?",
            options: [
              "O(1)",
              "O(n²)",
              "O(n)",
              "O(log n)",
            ],
            correct: 1,
            ok: "Por cada uno de los n elementos del bucle externo, el bucle interno recorre los n elementos otra vez: n × n = n², complejidad cuadrática.",
            bad: "No es constante ni lineal, porque el trabajo crece con el cuadrado de n; tampoco es logarítmico, que describe reducir el problema a la mitad en cada paso.",
          },
          extra: {
            type: "match",
            prompt: "Empareja cada complejidad con un ejemplo de operación.",
            payload: {
              left: ["O(1)", "O(log n)", "O(n)", "O(n²)"],
              right: [
                "Recorrer todos los elementos de un arreglo una sola vez con un bucle",
                "Comparar cada elemento de un arreglo con todos los demás, usando dos bucles anidados",
                "Acceder a un elemento de un arreglo por su índice, sin recorrer nada",
                "Descartar la mitad de los elementos restantes en cada paso, como en la búsqueda binaria",
              ],
            },
            answer: { pairs: [[0, 2], [1, 3], [2, 0], [3, 1]] },
            ok: "O(1) accede directo sin recorrer nada; O(log n) descarta la mitad en cada paso; O(n) recorre una vez; O(n²) compara cada par con bucles anidados.",
            bad: "No confundas recorrer una vez (O(n)) con recorrer con bucles anidados (O(n²)); acceder por índice es O(1), y descartar la mitad en cada paso es O(log n).",
          },
        },
      ],
    },
    {
      id: "algo-u2",
      name: "Unidad 2 · Recursión",
      lessons: [
        {
          id: "algo-l5",
          title: "El caso base",
          mins: 18,
          content: [
            { type: "p", html: "Una función <code>recursiva</code> es aquella que se llama a sí misma para resolver una versión más pequeña del mismo problema. Todo algoritmo recursivo necesita un <code>caso base</code>: una condición simple que se resuelve directamente, sin más llamadas recursivas, y que detiene la recursión." },
            { type: "p", html: "Sin un caso base correcto, la función se llamaría a sí misma indefinidamente hasta agotar la memoria disponible para las llamadas pendientes, un error conocido como <code>desbordamiento de pila</code> (stack overflow)." },
            { type: "code", lines: [
              `<span style="${K}">public static int</span> factorial(<span style="${K}">int</span> n) {`,
              `  <span style="${K}">if</span> (n == <span style="${N}">0</span>) {`,
              `    <span style="${K}">return</span> <span style="${N}">1</span>; <span style="${C}">// caso base</span>`,
              `  }`,
              `  <span style="${K}">return</span> n * factorial(n - <span style="${N}">1</span>); <span style="${C}">// llamada recursiva</span>`,
              `}`,
            ]},
          ],
          quiz: {
            question: "¿Qué ocurre si eliminas el caso base if (n == 0) return 1; de la función factorial?",
            options: [
              "El resultado sería el mismo, pero más lento",
              "Java detecta el error y ejecuta el caso base de forma implícita",
              "La función se llamaría a sí misma indefinidamente hasta provocar un desbordamiento de pila",
              "factorial(0) devolvería 0 en lugar de 1",
            ],
            correct: 2,
            ok: "Sin caso base, cada llamada genera otra llamada con n-1, sin detenerse nunca, hasta agotar la memoria de la pila de llamadas.",
            bad: "No es solo más lento, Java no agrega un caso base implícito, y el problema no es el valor de retorno de un caso puntual sino que la recursión nunca termina.",
          },
          extra: {
            type: "blanks",
            prompt: "Completa el caso base y la llamada recursiva de factorial.",
            payload: {
              code: [
                `<span style="${K}">public static int</span> factorial(<span style="${K}">int</span> n) {`,
                `  <span style="${K}">if</span> (n == <b0>) {`,
                `    <span style="${K}">return</span> <span style="${N}">1</span>; <span style="${C}">// caso base</span>`,
                `  }`,
                `  <span style="${K}">return</span> n * factorial(n - <b1>); <span style="${C}">// llamada recursiva</span>`,
                `}`,
              ],
              bank: ["0", "1", "n", "2"],
            },
            answer: { blanks: ["0", "1"] },
            ok: "El caso base se cumple cuando n llega a 0, y cada llamada recursiva reduce n en 1 para acercarse a ese caso base.",
            bad: "Si el caso base comparara con un valor distinto de 0, o si el decremento no fuera exactamente 1, la recursión podría saltarse el 0 y no terminar nunca.",
          },
        },
        {
          id: "algo-l6",
          title: "Recursión sobre listas",
          mins: 20,
          content: [
            { type: "p", html: "La recursión también sirve para procesar arreglos o listas: el caso base suele ser la posición final del arreglo, y el paso recursivo procesa un elemento y delega el resto a una llamada con el índice reducido en uno." },
            { type: "code", lines: [
              `<span style="${K}">public static int</span> sumarArreglo(<span style="${K}">int</span>[] arreglo, <span style="${K}">int</span> indice) {`,
              `  <span style="${K}">if</span> (indice == arreglo.length) {`,
              `    <span style="${K}">return</span> <span style="${N}">0</span>; <span style="${C}">// caso base: no quedan elementos</span>`,
              `  }`,
              `  <span style="${K}">return</span> arreglo[indice] + sumarArreglo(arreglo, indice + <span style="${N}">1</span>);`,
              `}`,
            ]},
            { type: "note", text: "Cada llamada recursiva avanza el índice en uno, acercándose al caso base; si el índice nunca avanzara, la recursión no terminaría." },
          ],
          quiz: {
            question: "En sumarArreglo(arreglo, indice), ¿qué representa el caso base indice == arreglo.length?",
            options: [
              "Que ya no quedan elementos por sumar, así que la suma parcial es 0",
              "Un error de índice fuera de rango",
              "El elemento con el valor más grande",
              "El primer elemento del arreglo",
            ],
            correct: 0,
            ok: "Cuando indice llega a arreglo.length, ya se procesaron todos los elementos; el caso base devuelve 0 porque no hay nada más que sumar.",
            bad: "No representa el primer elemento ni el mayor valor, y no es un error: es la condición de parada, exactamente en el límite válido del arreglo.",
          },
          extra: {
            type: "blanks",
            prompt: "Completa la función recursiva que suma los elementos de una lista.",
            payload: {
              code: [
                `<span style="${K}">public static int</span> sumarLista(<span style="${K}">int</span>[] lista, <span style="${K}">int</span> indice) {`,
                `  <span style="${K}">if</span> (indice == <b0>) {`,
                `    <span style="${K}">return</span> <span style="${N}">0</span>; <span style="${C}">// caso base: no quedan elementos</span>`,
                `  }`,
                `  <span style="${K}">return</span> lista[indice] + sumarLista(lista, indice + <b1>);`,
                `}`,
              ],
              bank: ["lista.length", "1", "0", "lista.length - 1"],
            },
            answer: { blanks: ["lista.length", "1"] },
            ok: "El caso base se activa cuando indice llega a lista.length (ya no hay elementos); cada llamada recursiva avanza el índice en 1 para acercarse a ese límite.",
            bad: "Si el caso base comparara con 0 en vez de lista.length, o si el índice no avanzara en 1, la recursión no recorrería toda la lista ni terminaría donde corresponde.",
          },
        },
        {
          id: "algo-l7",
          title: "Torres de Hanói",
          mins: 22,
          content: [
            { type: "p", html: "El problema de las <code>Torres de Hanói</code> consiste en mover n discos de una torre origen a una torre destino, usando una torre auxiliar, sin colocar nunca un disco más grande sobre uno más pequeño. Es un ejemplo clásico de recursión: mover n discos se reduce a mover n-1 discos dos veces, más un movimiento simple." },
            { type: "p", html: "Estrategia recursiva: mueve los n-1 discos superiores de origen a auxiliar (usando destino como apoyo), mueve el disco más grande de origen a destino, y luego mueve los n-1 discos de auxiliar a destino (usando origen como apoyo)." },
            { type: "code", lines: [
              `<span style="${K}">public static void</span> hanoi(<span style="${K}">int</span> n, <span style="${S}">String</span> origen, <span style="${S}">String</span> destino, <span style="${S}">String</span> auxiliar) {`,
              `  <span style="${K}">if</span> (n == <span style="${N}">1</span>) {`,
              `    <span style="${S}">System</span>.out.println(<span style="${S}">"Mover disco 1 de "</span> + origen + <span style="${S}">" a "</span> + destino);`,
              `    <span style="${K}">return</span>;`,
              `  }`,
              `  hanoi(n - <span style="${N}">1</span>, origen, auxiliar, destino);`,
              `  <span style="${S}">System</span>.out.println(<span style="${S}">"Mover disco "</span> + n + <span style="${S}">" de "</span> + origen + <span style="${S}">" a "</span> + destino);`,
              `  hanoi(n - <span style="${N}">1</span>, auxiliar, destino, origen);`,
              `}`,
            ]},
            { type: "note", text: "El número total de movimientos que realiza hanoi(n, ...) es 2ⁿ - 1: por eso Torres de Hanói es el ejemplo clásico de un algoritmo con complejidad exponencial." },
          ],
          quiz: {
            question: "En la solución recursiva de Hanói, ¿cuál es el caso base de la función hanoi(n, origen, destino, auxiliar)?",
            options: [
              "n == 0: no hay discos que mover",
              "n == 1: mover un solo disco directamente de origen a destino",
              "origen == destino: las torres son la misma",
              "No existe caso base, la función se detiene sola",
            ],
            correct: 1,
            ok: "El caso base es mover un único disco (n == 1) directamente, sin más llamadas recursivas; para n mayor, la función se divide en dos llamadas con n-1.",
            bad: "El código verifica n == 1, no n == 0, y comparar origen con destino no forma parte de la condición de parada; toda función recursiva necesita un caso base explícito para terminar.",
          },
          extra: {
            type: "order",
            prompt: "Ordena la llamada inicial y los movimientos que imprime hanoi(2, \"A\", \"C\", \"B\") al resolver Torres de Hanói con 2 discos.",
            payload: {
              lines: [
                { id: "c", html: `<span style="${S}">System</span>.out.println(<span style="${S}">"Mover disco 2 de A a C"</span>);` },
                { id: "a", html: `hanoi(<span style="${N}">2</span>, <span style="${S}">"A"</span>, <span style="${S}">"C"</span>, <span style="${S}">"B"</span>);` },
                { id: "d", html: `<span style="${S}">System</span>.out.println(<span style="${S}">"Mover disco 1 de B a C"</span>);` },
                { id: "b", html: `<span style="${S}">System</span>.out.println(<span style="${S}">"Mover disco 1 de A a B"</span>);` },
              ],
            },
            answer: { order: ["a", "b", "c", "d"] },
            ok: "Primero se invoca hanoi(2, A, C, B); esa llamada mueve el disco 1 de A a B, luego el disco 2 de A a C, y por último el disco 1 de B a C: 3 movimientos en total.",
            bad: "El disco grande (2) no puede moverse hasta liberar el disco pequeño (1) de encima, y el pequeño debe terminar en el destino después del grande, nunca antes de la llamada inicial.",
          },
        },
        {
          id: "algo-l8",
          title: "Recursión vs iteración",
          mins: 18,
          content: [
            { type: "p", html: "Todo algoritmo recursivo puede reescribirse de forma iterativa (con bucles) y viceversa; ambos enfoques resuelven el mismo problema, pero difieren en claridad y en uso de memoria." },
            { type: "p", html: "La recursión suele ser más legible para problemas que se definen naturalmente en términos de sí mismos (como recorrer un árbol), pero cada llamada recursiva ocupa espacio en la pila; la iteración usa memoria constante y evita el riesgo de desbordamiento de pila en entradas muy grandes." },
            { type: "code", lines: [
              `<span style="${C}">// Versión iterativa del factorial, sin llamadas recursivas</span>`,
              `<span style="${K}">public static int</span> factorialIterativo(<span style="${K}">int</span> n) {`,
              `  <span style="${K}">int</span> resultado = <span style="${N}">1</span>;`,
              `  <span style="${K}">for</span> (<span style="${K}">int</span> i = <span style="${N}">2</span>; i &lt;= n; i++) {`,
              `    resultado *= i;`,
              `  }`,
              `  <span style="${K}">return</span> resultado;`,
              `}`,
            ]},
          ],
          quiz: {
            question: "¿Por qué la versión iterativa de factorial suele preferirse sobre la recursiva para valores de n muy grandes?",
            options: [
              "Porque la versión recursiva calcula un resultado distinto",
              "Porque los bucles for no existen en versiones recientes de Java",
              "Porque la recursión solo funciona con números pares",
              "Porque la versión iterativa usa memoria constante y evita el riesgo de desbordamiento de pila",
            ],
            correct: 3,
            ok: "Ambas versiones calculan el mismo resultado, pero la recursiva acumula una llamada en la pila por cada nivel; con n grande eso puede agotar la pila, algo que la iterativa evita.",
            bad: "Los bucles for siguen existiendo en Java, la recursión no está limitada a números pares, y ambos enfoques calculan el mismo resultado; la diferencia real está en el uso de memoria de la pila.",
          },
          extra: {
            type: "match",
            prompt: "Empareja cada término con su característica.",
            payload: {
              left: ["Recursión", "Iteración", "Caso base", "Desbordamiento de pila"],
              right: [
                "Repetir instrucciones usando un bucle, con memoria constante independiente del número de repeticiones",
                "Error que ocurre cuando las llamadas recursivas se acumulan sin llegar nunca a un caso base",
                "Una función que se llama a sí misma para resolver una versión más pequeña del mismo problema",
                "Condición simple que detiene la recursión sin generar más llamadas",
              ],
            },
            answer: { pairs: [[0, 2], [1, 0], [2, 3], [3, 1]] },
            ok: "La recursión se llama a sí misma, la iteración repite con bucles y memoria constante, el caso base detiene la recursión, y el desbordamiento ocurre si nunca se alcanza ese caso base.",
            bad: "No confundas la causa (falta de caso base) con el efecto (desbordamiento de pila); y recuerda que la iteración, a diferencia de la recursión, no acumula llamadas en la pila.",
          },
        },
      ],
    },
    {
      id: "algo-u3",
      name: "Unidad 3 · Ordenamiento y búsqueda",
      lessons: [
        {
          id: "algo-l9",
          title: "Búsqueda lineal y binaria",
          mins: 20,
          content: [
            { type: "p", html: "La <code>búsqueda lineal</code> recorre un arreglo elemento por elemento hasta encontrar el valor buscado o llegar al final; funciona en cualquier arreglo, ordenado o no, con complejidad <code>O(n)</code>." },
            { type: "p", html: "La <code>búsqueda binaria</code> requiere que el arreglo esté ordenado: compara el elemento central con el valor buscado y descarta la mitad del arreglo en cada paso, logrando complejidad <code>O(log n)</code>, mucho más rápida para arreglos grandes." },
            { type: "code", lines: [
              `<span style="${K}">public static int</span> busquedaBinaria(<span style="${K}">int</span>[] arreglo, <span style="${K}">int</span> objetivo) {`,
              `  <span style="${K}">int</span> izquierda = <span style="${N}">0</span>, derecha = arreglo.length - <span style="${N}">1</span>;`,
              `  <span style="${K}">while</span> (izquierda &lt;= derecha) {`,
              `    <span style="${K}">int</span> medio = (izquierda + derecha) / <span style="${N}">2</span>;`,
              `    <span style="${K}">if</span> (arreglo[medio] == objetivo) {`,
              `      <span style="${K}">return</span> medio;`,
              `    } <span style="${K}">else if</span> (arreglo[medio] &lt; objetivo) {`,
              `      izquierda = medio + <span style="${N}">1</span>;`,
              `    } <span style="${K}">else</span> {`,
              `      derecha = medio - <span style="${N}">1</span>;`,
              `    }`,
              `  }`,
              `  <span style="${K}">return</span> -<span style="${N}">1</span>;`,
              `}`,
            ]},
          ],
          quiz: {
            question: "¿Por qué la búsqueda binaria exige que el arreglo esté ordenado, mientras que la búsqueda lineal no lo exige?",
            options: [
              "Porque un arreglo desordenado no puede recorrerse con un bucle",
              "Porque la búsqueda binaria descarta la mitad del arreglo comparando con el elemento central, lo que solo es válido si los datos están ordenados",
              "Porque la búsqueda lineal siempre es más rápida que la binaria",
              "Porque los arreglos ordenados no admiten valores repetidos",
            ],
            correct: 1,
            ok: "La búsqueda binaria decide qué mitad descartar comparando con el centro; esa decisión solo es correcta si el orden garantiza que todo lo mayor (o menor) queda de un lado.",
            bad: "Un arreglo desordenado sí puede recorrerse con un bucle (así funciona la búsqueda lineal), la lineal no es siempre más rápida (es O(n) contra O(log n)), y el orden no tiene relación con permitir o no valores repetidos.",
          },
          extra: {
            type: "order",
            prompt: "Ordena los pasos del algoritmo de búsqueda binaria sobre un arreglo ordenado.",
            payload: {
              lines: [
                { id: "c", html: `<span style="${C}">// Paso 3: descartar la mitad del arreglo donde el valor no puede estar</span>` },
                { id: "a", html: `<span style="${C}">// Paso 1: calcular medio = (izquierda + derecha) / 2</span>` },
                { id: "d", html: `<span style="${C}">// Paso 4: repetir el proceso con la mitad restante</span>` },
                { id: "b", html: `<span style="${C}">// Paso 2: comparar arreglo[medio] con el valor buscado</span>` },
              ],
            },
            answer: { order: ["a", "b", "c", "d"] },
            ok: "Primero calculas el medio, luego comparas con el objetivo; si no coincide, descartas la mitad donde no puede estar, y repites el proceso con la mitad restante.",
            bad: "No puedes descartar una mitad antes de comparar, ni comparar antes de calcular el medio; el proceso se repite solo después de descartar, no antes.",
          },
        },
        {
          id: "algo-l10",
          title: "Bubble sort e insertion sort",
          mins: 22,
          content: [
            { type: "p", html: "<code>Bubble sort</code> recorre el arreglo repetidamente, comparando pares de elementos adyacentes e intercambiándolos si están en el orden incorrecto; en cada pasada, el elemento más grande \"burbujea\" hasta su posición final. Su complejidad en el peor caso es <code>O(n²)</code>." },
            { type: "p", html: "<code>Insertion sort</code> construye el arreglo ordenado de a un elemento a la vez: toma cada elemento y lo inserta en la posición correcta dentro de la parte ya ordenada, desplazando los elementos mayores. También es <code>O(n²)</code> en el peor caso, pero eficiente cuando el arreglo ya está casi ordenado." },
            { type: "code", lines: [
              `<span style="${C}">// Bubble sort: intercambia adyacentes fuera de orden</span>`,
              `<span style="${K}">for</span> (<span style="${K}">int</span> i = <span style="${N}">0</span>; i &lt; arreglo.length - <span style="${N}">1</span>; i++) {`,
              `  <span style="${K}">for</span> (<span style="${K}">int</span> j = <span style="${N}">0</span>; j &lt; arreglo.length - <span style="${N}">1</span> - i; j++) {`,
              `    <span style="${K}">if</span> (arreglo[j] &gt; arreglo[j + <span style="${N}">1</span>]) {`,
              `      <span style="${K}">int</span> temp = arreglo[j];`,
              `      arreglo[j] = arreglo[j + <span style="${N}">1</span>];`,
              `      arreglo[j + <span style="${N}">1</span>] = temp;`,
              `    }`,
              `  }`,
              `}`,
            ]},
          ],
          quiz: {
            question: "¿Qué tienen en común bubble sort e insertion sort en cuanto a complejidad en el peor caso?",
            options: [
              "Ambos son O(log n)",
              "Ambos son O(1), porque solo comparan elementos vecinos",
              "Bubble sort es O(n) e insertion sort es O(n²)",
              "Ambos tienen complejidad O(n²) en el peor caso",
            ],
            correct: 3,
            ok: "Los dos algoritmos, en el peor caso (arreglo en orden inverso), requieren aproximadamente n² comparaciones e intercambios: complejidad cuadrática compartida.",
            bad: "Ninguno es logarítmico ni constante, y bubble sort tampoco baja a O(n) en el peor caso: ambos comparten la misma cota O(n²) en ese escenario.",
          },
          extra: {
            type: "order",
            prompt: "Ordena los pasos de la primera pasada de bubble sort sobre el arreglo [3, 1, 2], comparando elementos adyacentes de izquierda a derecha.",
            payload: {
              lines: [
                { id: "c", html: `<span style="${C}">// Comparar índices 1 y 2: 3 &gt; 2 → intercambiar → [1, 2, 3]</span>` },
                { id: "a", html: `<span style="${C}">// Estado inicial: [3, 1, 2]</span>` },
                { id: "d", html: `<span style="${C}">// Fin de la primera pasada: [1, 2, 3]</span>` },
                { id: "b", html: `<span style="${C}">// Comparar índices 0 y 1: 3 &gt; 1 → intercambiar → [1, 3, 2]</span>` },
              ],
            },
            answer: { order: ["a", "b", "c", "d"] },
            ok: "Bubble sort compara pares adyacentes: primero 3 y 1 (se intercambian), luego 3 y 2 (se intercambian de nuevo), dejando el arreglo [1, 2, 3] al final de la primera pasada.",
            bad: "La comparación avanza de izquierda a derecha sobre pares adyacentes; no se puede comparar el segundo par antes del primero, ni el arreglo queda ordenado antes de completar las comparaciones.",
          },
        },
        {
          id: "algo-l11",
          title: "Merge sort",
          mins: 24,
          content: [
            { type: "p", html: "<code>Merge sort</code> aplica la estrategia de <code>divide y vencerás</code>: divide el arreglo por la mitad recursivamente hasta llegar a subarreglos de un solo elemento (ya ordenados por definición), y luego los combina (<code>merge</code>) de a pares, siempre en orden, hasta reconstruir el arreglo completo ordenado." },
            { type: "p", html: "Gracias a que divide el problema a la mitad en cada nivel de recursión, merge sort logra complejidad <code>O(n log n)</code> en todos los casos, mucho mejor que la <code>O(n²)</code> de bubble sort o insertion sort para arreglos grandes." },
            { type: "code", lines: [
              `<span style="${K}">public static int</span>[] mergeSort(<span style="${K}">int</span>[] arreglo) {`,
              `  <span style="${K}">if</span> (arreglo.length &lt;= <span style="${N}">1</span>) {`,
              `    <span style="${K}">return</span> arreglo; <span style="${C}">// caso base: ya está ordenado</span>`,
              `  }`,
              `  <span style="${K}">int</span> medio = arreglo.length / <span style="${N}">2</span>;`,
              `  <span style="${K}">int</span>[] izquierda = mergeSort(<span style="${S}">Arrays</span>.copyOfRange(arreglo, <span style="${N}">0</span>, medio));`,
              `  <span style="${K}">int</span>[] derecha = mergeSort(<span style="${S}">Arrays</span>.copyOfRange(arreglo, medio, arreglo.length));`,
              `  <span style="${K}">return</span> combinar(izquierda, derecha);`,
              `}`,
            ]},
            { type: "note", text: "combinar(izquierda, derecha) mezcla dos listas que ya están ordenadas: compara el primer elemento pendiente de cada una, mueve el menor de los dos al resultado, y repite hasta vaciar ambas listas." },
          ],
          quiz: {
            question: "¿Por qué merge sort logra una complejidad mejor (O(n log n)) que bubble sort (O(n²)) para arreglos grandes?",
            options: [
              "Porque bubble sort solo funciona con números negativos",
              "Porque merge sort no necesita comparar ningún elemento",
              "Porque divide el problema a la mitad en cada nivel de recursión, en lugar de comparar todos los pares posibles",
              "Porque merge sort ordena sin usar recursión",
            ],
            correct: 2,
            ok: "Dividir a la mitad en cada nivel reduce drásticamente el número de comparaciones necesarias frente a comparar cada par adyacente repetidamente, dando O(n log n) en vez de O(n²).",
            bad: "Merge sort sí compara elementos durante el merge, bubble sort funciona con cualquier número, y merge sort depende justamente de la recursión para dividir el arreglo.",
          },
          extra: {
            type: "order",
            prompt: "Ordena las fases de merge sort, desde que recibe el arreglo hasta que devuelve el resultado ordenado.",
            payload: {
              lines: [
                { id: "c", html: `<span style="${C}">// 3. Combinar (merge) las dos mitades ya ordenadas en un solo arreglo ordenado</span>` },
                { id: "a", html: `<span style="${C}">// 1. Dividir el arreglo en dos mitades</span>` },
                { id: "d", html: `<span style="${C}">// 4. Devolver el arreglo combinado y ordenado</span>` },
                { id: "b", html: `<span style="${C}">// 2. Ordenar recursivamente cada mitad con mergeSort</span>` },
              ],
            },
            answer: { order: ["a", "b", "c", "d"] },
            ok: "Merge sort primero divide el arreglo a la mitad, ordena cada mitad por separado (de forma recursiva), las combina en un solo arreglo ordenado, y finalmente devuelve ese resultado.",
            bad: "No puedes combinar mitades que todavía no están ordenadas, ni devolver el resultado antes de combinarlo: primero se divide, después se ordena cada mitad, luego se combina y por último se devuelve.",
          },
        },
        {
          id: "algo-l12",
          title: "Elegir el algoritmo correcto",
          mins: 18,
          content: [
            { type: "p", html: "No existe un algoritmo de ordenamiento o búsqueda que sea siempre el mejor: la elección depende del tamaño de los datos, de si ya están parcialmente ordenados, de la memoria disponible y de la simplicidad de implementación que necesites." },
            { type: "p", html: "Como regla general: para arreglos pequeños o casi ordenados, insertion sort es simple y suficientemente rápido; para arreglos grandes, merge sort garantiza <code>O(n log n)</code> de forma consistente; y si los datos ya están ordenados, la búsqueda binaria siempre supera a la lineal." },
            { type: "code", lines: [
              `<span style="${K}">SI</span> arreglo.length &lt; <span style="${N}">20</span> <span style="${K}">ENTONCES</span>`,
              `  usar insertion sort`,
              `<span style="${K}">SINO</span>`,
              `  usar merge sort`,
              `<span style="${K}">FIN SI</span>`,
            ]},
          ],
          quiz: {
            question: "Tienes un arreglo de 10 elementos casi ordenado y otro de 10 millones de elementos desordenado. ¿Qué combinación de algoritmos es más razonable?",
            options: [
              "Insertion sort para el arreglo pequeño y casi ordenado, merge sort para el arreglo grande",
              "Usar búsqueda binaria para ordenar ambos arreglos",
              "Usar bubble sort en ambos casos, porque es el más simple de programar",
              "No ordenar el arreglo grande, porque O(n log n) es demasiado lento",
            ],
            correct: 0,
            ok: "Insertion sort aprovecha que el arreglo pequeño ya está casi ordenado; merge sort garantiza O(n log n) consistente, necesario para que el arreglo de 10 millones termine en un tiempo razonable.",
            bad: "Bubble sort no escala bien a 10 millones de elementos, la búsqueda binaria sirve para buscar, no para ordenar, y O(n log n) es precisamente la complejidad que hace viable ordenar arreglos grandes.",
          },
          extra: {
            type: "match",
            prompt: "Empareja cada problema con el algoritmo más adecuado para resolverlo.",
            payload: {
              left: [
                "Buscar un valor en un arreglo ordenado de un millón de elementos",
                "Ordenar un arreglo casi ordenado de 15 elementos",
                "Ordenar un arreglo desordenado de un millón de elementos",
                "Buscar un valor en un arreglo desordenado de 10 elementos",
              ],
              right: [
                "Búsqueda lineal: revisa cada elemento hasta encontrarlo, sin depender de que esté ordenado",
                "Merge sort: garantiza O(n log n) incluso en arreglos grandes y desordenados",
                "Búsqueda binaria: descarta la mitad del espacio de búsqueda en cada paso",
                "Insertion sort: eficiente cuando los datos ya están casi ordenados",
              ],
            },
            answer: { pairs: [[0, 2], [1, 3], [2, 1], [3, 0]] },
            ok: "La búsqueda binaria exige orden y aprovecha arreglos grandes; insertion sort brilla con datos pequeños casi ordenados; merge sort garantiza buen rendimiento en arreglos grandes desordenados; y la búsqueda lineal sirve para arreglos pequeños sin garantía de orden.",
            bad: "No uses búsqueda binaria sin arreglo ordenado, ni insertion sort para un millón de elementos desordenados: la elección depende del tamaño y del estado de los datos.",
          },
        },
      ],
    },
  ],
};
