const K = 'color: var(--accent-violet)';
const S = 'color: var(--accent-cyan)';
const N = 'color: var(--accent-amber)';
const C = 'color: var(--text-tertiary)';

export default {
  id: "algo",
  subject: "Algoritmos",
  tone: "violet",
  title: "Recursión y complejidad",
  description: "Piensa como computador: análisis de complejidad, recursión y los algoritmos clásicos.",
  order: 3,
  prereq: null,
  units: [
    {
      id: "algo-u1",
      name: "Unidad 1 · Pensamiento algorítmico",
      lessons: [
        {
          id: "algo-l1",
          title: "Qué es un algoritmo",
          mins: 12,
          content: [
            { type: "p", html: "Un <code>algoritmo</code> es una secuencia finita y ordenada de pasos precisos que resuelve un problema o realiza una tarea. Para que sea válido, cada paso debe ser claro y no ambiguo, y el proceso debe terminar después de un número finito de pasos." },
            { type: "p", html: "Un mismo problema puede resolverse con distintos algoritmos: para ordenar una lista existen decenas de estrategias. Elegir un buen algoritmo importa tanto como escribir código correcto: uno ineficiente puede tardar horas donde uno eficiente tarda segundos." },
            { type: "code", lines: [
              `<span style="${C}">// Algoritmo: encontrar el mayor de tres números</span>`,
              `<span style="${K}">INICIO</span>`,
              `  <span style="${K}">LEER</span> a, b, c`,
              `  <span style="${K}">SI</span> a &gt;= b <span style="${K}">Y</span> a &gt;= c <span style="${K}">ENTONCES</span>`,
              `    <span style="${K}">ESCRIBIR</span> a`,
              `  <span style="${K}">SINO SI</span> b &gt;= c <span style="${K}">ENTONCES</span>`,
              `    <span style="${K}">ESCRIBIR</span> b`,
              `  <span style="${K}">SINO</span>`,
              `    <span style="${K}">ESCRIBIR</span> c`,
              `  <span style="${K}">FIN SI</span>`,
              `<span style="${K}">FIN</span>`,
            ]},
            { type: "note", text: "Antes de escribir código, traza el algoritmo a mano con un ejemplo pequeño: si no puedes explicar cada paso en papel, tampoco podrás traducirlo correctamente a un lenguaje de programación." },
          ],
          quiz: {
            question: "¿Cuál de estas características es obligatoria para que una secuencia de pasos se considere un algoritmo?",
            options: [
              "Debe terminar después de un número finito de pasos",
              "Debe estar escrita en un lenguaje de programación concreto",
              "Debe tardar menos de un segundo en ejecutarse",
              "Debe usar únicamente operaciones aritméticas",
            ],
            correct: 0,
            ok: "Un algoritmo debe ser finito: tiene que terminar tras una cantidad limitada de pasos, sin importar el lenguaje o la velocidad de ejecución.",
            bad: "Un algoritmo puede describirse en pseudocódigo sin lenguaje concreto, puede tardar más de un segundo, y puede incluir operaciones distintas a las aritméticas; lo obligatorio es que termine.",
          },
        },
        {
          id: "algo-l2",
          title: "Pseudocódigo",
          mins: 14,
          content: [
            { type: "p", html: "El <code>pseudocódigo</code> describe un algoritmo con una notación intermedia entre el lenguaje natural y un lenguaje de programación real: usa palabras clave estructuradas (<code>SI</code>, <code>MIENTRAS</code>, <code>PARA</code>) sin atarse a la sintaxis exacta de ningún lenguaje concreto." },
            { type: "p", html: "Escribir primero en pseudocódigo permite concentrarte en la lógica del algoritmo sin distraerte con detalles de sintaxis (punto y coma, llaves, tipos); después puedes traducirlo a Java, Python o cualquier otro lenguaje." },
            { type: "code", lines: [
              `<span style="${C}">// Suma los números del 1 al n</span>`,
              `<span style="${K}">FUNCION</span> sumarHastaN(n)`,
              `  suma &lt;- <span style="${N}">0</span>`,
              `  <span style="${K}">PARA</span> i <span style="${K}">DESDE</span> <span style="${N}">1</span> <span style="${K}">HASTA</span> n <span style="${K}">HACER</span>`,
              `    suma &lt;- suma + i`,
              `  <span style="${K}">FIN PARA</span>`,
              `  <span style="${K}">DEVOLVER</span> suma`,
              `<span style="${K}">FIN FUNCION</span>`,
            ]},
            { type: "note", text: "El símbolo <- representa la asignación: la variable toma el valor de la expresión de la derecha, igual que = en Java pero sin la ambigüedad de la comparación de igualdad." },
          ],
          quiz: {
            question: "¿Cuál es la principal ventaja de escribir primero un algoritmo en pseudocódigo antes de programarlo en Java?",
            options: [
              "El pseudocódigo se ejecuta directamente en la JVM sin compilar",
              "El pseudocódigo es un lenguaje de programación oficial de Java",
              "Permite concentrarte en la lógica del algoritmo sin la sintaxis exacta de un lenguaje concreto",
              "El pseudocódigo elimina la necesidad de probar el algoritmo",
            ],
            correct: 2,
            ok: "El pseudocódigo no se ejecuta ni pertenece a ningún lenguaje: es una herramienta de diseño que te deja pensar en los pasos antes de preocuparte por la sintaxis.",
            bad: "El pseudocódigo no se ejecuta en la JVM, no es un lenguaje oficial de Java, y no reemplaza las pruebas; su valor está en separar el diseño de la sintaxis.",
          },
        },
        {
          id: "algo-l3",
          title: "Trazas de ejecución",
          mins: 16,
          content: [
            { type: "p", html: "Una <code>traza de ejecución</code> consiste en seguir manualmente, paso a paso, cómo cambian las variables de un algoritmo mientras se ejecuta. Es la herramienta más confiable para verificar si un algoritmo hace lo que crees que hace, antes incluso de escribir código." },
            { type: "code", lines: [
              `<span style="${K}">int</span> resultado = <span style="${N}">1</span>;`,
              `<span style="${K}">for</span> (<span style="${K}">int</span> i = <span style="${N}">1</span>; i &lt;= <span style="${N}">4</span>; i++) {`,
              `  resultado = resultado * i;`,
              `}`,
            ]},
            { type: "p", html: "Al trazar este bucle: en i=1, resultado pasa de 1 a 1; en i=2, pasa a 2; en i=3, pasa a 6; en i=4, pasa a 24. Cuando i llega a 5, la condición <code>i &lt;= 4</code> es falsa y el bucle termina." },
          ],
          quiz: {
            question: "Al trazar el bucle for (int i = 1; i <= 4; i++) resultado = resultado * i; con resultado inicial 1, ¿qué valor tiene resultado cuando el bucle termina?",
            options: [
              "1, porque resultado nunca cambia dentro del bucle",
              "10, la suma de 1+2+3+4",
              "4, el último valor de i",
              "24, el resultado de multiplicar 1×2×3×4",
            ],
            correct: 3,
            ok: "El bucle multiplica resultado por cada i de 1 a 4: 1×1×2×3×4 = 24, el factorial de 4.",
            bad: "El bucle multiplica, no suma, así que no da 10; resultado sí cambia en cada vuelta y termina en 24, no en el último valor de i ni en su valor inicial.",
          },
        },
        {
          id: "algo-l4",
          title: "Notación Big O",
          mins: 20,
          content: [
            { type: "p", html: "La <code>notación Big O</code> describe cómo crece el tiempo (o la memoria) que necesita un algoritmo a medida que crece el tamaño de la entrada <code>n</code>, ignorando constantes y términos de menor orden. Es una forma de comparar algoritmos sin depender de la velocidad de una computadora concreta." },
            { type: "p", html: "Órdenes comunes, de mejor a peor: <code>O(1)</code> (constante, no depende de n), <code>O(log n)</code> (logarítmico), <code>O(n)</code> (lineal), <code>O(n log n)</code>, <code>O(n²)</code> (cuadrático) y <code>O(2ⁿ)</code> (exponencial)." },
            { type: "code", lines: [
              `<span style="${C}">// O(1): acceso directo, no depende del tamaño del arreglo</span>`,
              `<span style="${K}">int</span> primero = arreglo[<span style="${N}">0</span>];`,
              ``,
              `<span style="${C}">// O(n): recorre todo el arreglo una vez</span>`,
              `<span style="${K}">for</span> (<span style="${K}">int</span> x : arreglo) {`,
              `  <span style="${S}">System</span>.out.println(x);`,
              `}`,
              ``,
              `<span style="${C}">// O(n²): un bucle anidado dentro de otro</span>`,
              `<span style="${K}">for</span> (<span style="${K}">int</span> i = <span style="${N}">0</span>; i &lt; arreglo.length; i++) {`,
              `  <span style="${K}">for</span> (<span style="${K}">int</span> j = <span style="${N}">0</span>; j &lt; arreglo.length; j++) {`,
              `    <span style="${S}">System</span>.out.println(arreglo[i] + arreglo[j]);`,
              `  }`,
              `}`,
            ]},
            { type: "note", text: "Para comparar dos algoritmos con Big O, fíjate en el término dominante cuando n crece mucho: O(n² + 100n) se simplifica a O(n²), porque el término cuadrático domina sobre el lineal." },
          ],
          quiz: {
            question: "El tercer fragmento anida un for dentro de otro, ambos recorriendo el arreglo completo. ¿Qué complejidad Big O tiene?",
            options: [
              "O(1)",
              "O(n²)",
              "O(n)",
              "O(log n)",
            ],
            correct: 1,
            ok: "Por cada uno de los n elementos del bucle externo, el bucle interno recorre los n elementos otra vez: n × n = n², complejidad cuadrática.",
            bad: "No es constante ni lineal, porque el trabajo crece con el cuadrado de n; tampoco es logarítmico, que describe reducir el problema a la mitad en cada paso.",
          },
        },
      ],
    },
    {
      id: "algo-u2",
      name: "Unidad 2 · Recursión",
      lessons: [
        {
          id: "algo-l5",
          title: "El caso base",
          mins: 18,
          content: [
            { type: "p", html: "Una función <code>recursiva</code> es aquella que se llama a sí misma para resolver una versión más pequeña del mismo problema. Todo algoritmo recursivo necesita un <code>caso base</code>: una condición simple que se resuelve directamente, sin más llamadas recursivas, y que detiene la recursión." },
            { type: "p", html: "Sin un caso base correcto, la función se llamaría a sí misma indefinidamente hasta agotar la memoria disponible para las llamadas pendientes, un error conocido como <code>desbordamiento de pila</code> (stack overflow)." },
            { type: "code", lines: [
              `<span style="${K}">public static int</span> factorial(<span style="${K}">int</span> n) {`,
              `  <span style="${K}">if</span> (n == <span style="${N}">0</span>) {`,
              `    <span style="${K}">return</span> <span style="${N}">1</span>; <span style="${C}">// caso base</span>`,
              `  }`,
              `  <span style="${K}">return</span> n * factorial(n - <span style="${N}">1</span>); <span style="${C}">// llamada recursiva</span>`,
              `}`,
            ]},
          ],
          quiz: {
            question: "¿Qué ocurre si eliminas el caso base if (n == 0) return 1; de la función factorial?",
            options: [
              "El resultado sería el mismo, pero más lento",
              "Java detecta el error y ejecuta el caso base de forma implícita",
              "La función se llamaría a sí misma indefinidamente hasta provocar un desbordamiento de pila",
              "factorial(0) devolvería 0 en lugar de 1",
            ],
            correct: 2,
            ok: "Sin caso base, cada llamada genera otra llamada con n-1, sin detenerse nunca, hasta agotar la memoria de la pila de llamadas.",
            bad: "No es solo más lento, Java no agrega un caso base implícito, y el problema no es el valor de retorno de un caso puntual sino que la recursión nunca termina.",
          },
        },
        {
          id: "algo-l6",
          title: "Recursión sobre listas",
          mins: 20,
          content: [
            { type: "p", html: "La recursión también sirve para procesar arreglos o listas: el caso base suele ser la posición final del arreglo, y el paso recursivo procesa un elemento y delega el resto a una llamada con el índice reducido en uno." },
            { type: "code", lines: [
              `<span style="${K}">public static int</span> sumarArreglo(<span style="${K}">int</span>[] arreglo, <span style="${K}">int</span> indice) {`,
              `  <span style="${K}">if</span> (indice == arreglo.length) {`,
              `    <span style="${K}">return</span> <span style="${N}">0</span>; <span style="${C}">// caso base: no quedan elementos</span>`,
              `  }`,
              `  <span style="${K}">return</span> arreglo[indice] + sumarArreglo(arreglo, indice + <span style="${N}">1</span>);`,
              `}`,
            ]},
            { type: "note", text: "Cada llamada recursiva avanza el índice en uno, acercándose al caso base; si el índice nunca avanzara, la recursión no terminaría." },
          ],
          quiz: {
            question: "En sumarArreglo(arreglo, indice), ¿qué representa el caso base indice == arreglo.length?",
            options: [
              "Que ya no quedan elementos por sumar, así que la suma parcial es 0",
              "Un error de índice fuera de rango",
              "El elemento con el valor más grande",
              "El primer elemento del arreglo",
            ],
            correct: 0,
            ok: "Cuando indice llega a arreglo.length, ya se procesaron todos los elementos; el caso base devuelve 0 porque no hay nada más que sumar.",
            bad: "No representa el primer elemento ni el mayor valor, y no es un error: es la condición de parada, exactamente en el límite válido del arreglo.",
          },
        },
        {
          id: "algo-l7",
          title: "Torres de Hanói",
          mins: 22,
          content: [
            { type: "p", html: "El problema de las <code>Torres de Hanói</code> consiste en mover n discos de una torre origen a una torre destino, usando una torre auxiliar, sin colocar nunca un disco más grande sobre uno más pequeño. Es un ejemplo clásico de recursión: mover n discos se reduce a mover n-1 discos dos veces, más un movimiento simple." },
            { type: "p", html: "Estrategia recursiva: mueve los n-1 discos superiores de origen a auxiliar (usando destino como apoyo), mueve el disco más grande de origen a destino, y luego mueve los n-1 discos de auxiliar a destino (usando origen como apoyo)." },
            { type: "code", lines: [
              `<span style="${K}">public static void</span> hanoi(<span style="${K}">int</span> n, <span style="${S}">String</span> origen, <span style="${S}">String</span> destino, <span style="${S}">String</span> auxiliar) {`,
              `  <span style="${K}">if</span> (n == <span style="${N}">1</span>) {`,
              `    <span style="${S}">System</span>.out.println(<span style="${S}">"Mover disco 1 de "</span> + origen + <span style="${S}">" a "</span> + destino);`,
              `    <span style="${K}">return</span>;`,
              `  }`,
              `  hanoi(n - <span style="${N}">1</span>, origen, auxiliar, destino);`,
              `  <span style="${S}">System</span>.out.println(<span style="${S}">"Mover disco "</span> + n + <span style="${S}">" de "</span> + origen + <span style="${S}">" a "</span> + destino);`,
              `  hanoi(n - <span style="${N}">1</span>, auxiliar, destino, origen);`,
              `}`,
            ]},
            { type: "note", text: "El número total de movimientos que realiza hanoi(n, ...) es 2ⁿ - 1: por eso Torres de Hanói es el ejemplo clásico de un algoritmo con complejidad exponencial." },
          ],
          quiz: {
            question: "En la solución recursiva de Hanói, ¿cuál es el caso base de la función hanoi(n, origen, destino, auxiliar)?",
            options: [
              "n == 0: no hay discos que mover",
              "n == 1: mover un solo disco directamente de origen a destino",
              "origen == destino: las torres son la misma",
              "No existe caso base, la función se detiene sola",
            ],
            correct: 1,
            ok: "El caso base es mover un único disco (n == 1) directamente, sin más llamadas recursivas; para n mayor, la función se divide en dos llamadas con n-1.",
            bad: "El código verifica n == 1, no n == 0, y comparar origen con destino no forma parte de la condición de parada; toda función recursiva necesita un caso base explícito para terminar.",
          },
        },
        {
          id: "algo-l8",
          title: "Recursión vs iteración",
          mins: 18,
          content: [
            { type: "p", html: "Todo algoritmo recursivo puede reescribirse de forma iterativa (con bucles) y viceversa; ambos enfoques resuelven el mismo problema, pero difieren en claridad y en uso de memoria." },
            { type: "p", html: "La recursión suele ser más legible para problemas que se definen naturalmente en términos de sí mismos (como recorrer un árbol), pero cada llamada recursiva ocupa espacio en la pila; la iteración usa memoria constante y evita el riesgo de desbordamiento de pila en entradas muy grandes." },
            { type: "code", lines: [
              `<span style="${C}">// Versión iterativa del factorial, sin llamadas recursivas</span>`,
              `<span style="${K}">public static int</span> factorialIterativo(<span style="${K}">int</span> n) {`,
              `  <span style="${K}">int</span> resultado = <span style="${N}">1</span>;`,
              `  <span style="${K}">for</span> (<span style="${K}">int</span> i = <span style="${N}">2</span>; i &lt;= n; i++) {`,
              `    resultado *= i;`,
              `  }`,
              `  <span style="${K}">return</span> resultado;`,
              `}`,
            ]},
          ],
          quiz: {
            question: "¿Por qué la versión iterativa de factorial suele preferirse sobre la recursiva para valores de n muy grandes?",
            options: [
              "Porque la versión recursiva calcula un resultado distinto",
              "Porque los bucles for no existen en versiones recientes de Java",
              "Porque la recursión solo funciona con números pares",
              "Porque la versión iterativa usa memoria constante y evita el riesgo de desbordamiento de pila",
            ],
            correct: 3,
            ok: "Ambas versiones calculan el mismo resultado, pero la recursiva acumula una llamada en la pila por cada nivel; con n grande eso puede agotar la pila, algo que la iterativa evita.",
            bad: "Los bucles for siguen existiendo en Java, la recursión no está limitada a números pares, y ambos enfoques calculan el mismo resultado; la diferencia real está en el uso de memoria de la pila.",
          },
        },
      ],
    },
    {
      id: "algo-u3",
      name: "Unidad 3 · Ordenamiento y búsqueda",
      lessons: [
        {
          id: "algo-l9",
          title: "Búsqueda lineal y binaria",
          mins: 20,
          content: [
            { type: "p", html: "La <code>búsqueda lineal</code> recorre un arreglo elemento por elemento hasta encontrar el valor buscado o llegar al final; funciona en cualquier arreglo, ordenado o no, con complejidad <code>O(n)</code>." },
            { type: "p", html: "La <code>búsqueda binaria</code> requiere que el arreglo esté ordenado: compara el elemento central con el valor buscado y descarta la mitad del arreglo en cada paso, logrando complejidad <code>O(log n)</code>, mucho más rápida para arreglos grandes." },
            { type: "code", lines: [
              `<span style="${K}">public static int</span> busquedaBinaria(<span style="${K}">int</span>[] arreglo, <span style="${K}">int</span> objetivo) {`,
              `  <span style="${K}">int</span> izquierda = <span style="${N}">0</span>, derecha = arreglo.length - <span style="${N}">1</span>;`,
              `  <span style="${K}">while</span> (izquierda &lt;= derecha) {`,
              `    <span style="${K}">int</span> medio = (izquierda + derecha) / <span style="${N}">2</span>;`,
              `    <span style="${K}">if</span> (arreglo[medio] == objetivo) {`,
              `      <span style="${K}">return</span> medio;`,
              `    } <span style="${K}">else if</span> (arreglo[medio] &lt; objetivo) {`,
              `      izquierda = medio + <span style="${N}">1</span>;`,
              `    } <span style="${K}">else</span> {`,
              `      derecha = medio - <span style="${N}">1</span>;`,
              `    }`,
              `  }`,
              `  <span style="${K}">return</span> -<span style="${N}">1</span>;`,
              `}`,
            ]},
          ],
          quiz: {
            question: "¿Por qué la búsqueda binaria exige que el arreglo esté ordenado, mientras que la búsqueda lineal no lo exige?",
            options: [
              "Porque un arreglo desordenado no puede recorrerse con un bucle",
              "Porque la búsqueda binaria descarta la mitad del arreglo comparando con el elemento central, lo que solo es válido si los datos están ordenados",
              "Porque la búsqueda lineal siempre es más rápida que la binaria",
              "Porque los arreglos ordenados no admiten valores repetidos",
            ],
            correct: 1,
            ok: "La búsqueda binaria decide qué mitad descartar comparando con el centro; esa decisión solo es correcta si el orden garantiza que todo lo mayor (o menor) queda de un lado.",
            bad: "Un arreglo desordenado sí puede recorrerse con un bucle (así funciona la búsqueda lineal), la lineal no es siempre más rápida (es O(n) contra O(log n)), y el orden no tiene relación con permitir o no valores repetidos.",
          },
        },
        {
          id: "algo-l10",
          title: "Bubble sort e insertion sort",
          mins: 22,
          content: [
            { type: "p", html: "<code>Bubble sort</code> recorre el arreglo repetidamente, comparando pares de elementos adyacentes e intercambiándolos si están en el orden incorrecto; en cada pasada, el elemento más grande \"burbujea\" hasta su posición final. Su complejidad en el peor caso es <code>O(n²)</code>." },
            { type: "p", html: "<code>Insertion sort</code> construye el arreglo ordenado de a un elemento a la vez: toma cada elemento y lo inserta en la posición correcta dentro de la parte ya ordenada, desplazando los elementos mayores. También es <code>O(n²)</code> en el peor caso, pero eficiente cuando el arreglo ya está casi ordenado." },
            { type: "code", lines: [
              `<span style="${C}">// Bubble sort: intercambia adyacentes fuera de orden</span>`,
              `<span style="${K}">for</span> (<span style="${K}">int</span> i = <span style="${N}">0</span>; i &lt; arreglo.length - <span style="${N}">1</span>; i++) {`,
              `  <span style="${K}">for</span> (<span style="${K}">int</span> j = <span style="${N}">0</span>; j &lt; arreglo.length - <span style="${N}">1</span> - i; j++) {`,
              `    <span style="${K}">if</span> (arreglo[j] &gt; arreglo[j + <span style="${N}">1</span>]) {`,
              `      <span style="${K}">int</span> temp = arreglo[j];`,
              `      arreglo[j] = arreglo[j + <span style="${N}">1</span>];`,
              `      arreglo[j + <span style="${N}">1</span>] = temp;`,
              `    }`,
              `  }`,
              `}`,
            ]},
          ],
          quiz: {
            question: "¿Qué tienen en común bubble sort e insertion sort en cuanto a complejidad en el peor caso?",
            options: [
              "Ambos son O(log n)",
              "Ambos son O(1), porque solo comparan elementos vecinos",
              "Bubble sort es O(n) e insertion sort es O(n²)",
              "Ambos tienen complejidad O(n²) en el peor caso",
            ],
            correct: 3,
            ok: "Los dos algoritmos, en el peor caso (arreglo en orden inverso), requieren aproximadamente n² comparaciones e intercambios: complejidad cuadrática compartida.",
            bad: "Ninguno es logarítmico ni constante, y bubble sort tampoco baja a O(n) en el peor caso: ambos comparten la misma cota O(n²) en ese escenario.",
          },
        },
        {
          id: "algo-l11",
          title: "Merge sort",
          mins: 24,
          content: [
            { type: "p", html: "<code>Merge sort</code> aplica la estrategia de <code>divide y vencerás</code>: divide el arreglo por la mitad recursivamente hasta llegar a subarreglos de un solo elemento (ya ordenados por definición), y luego los combina (<code>merge</code>) de a pares, siempre en orden, hasta reconstruir el arreglo completo ordenado." },
            { type: "p", html: "Gracias a que divide el problema a la mitad en cada nivel de recursión, merge sort logra complejidad <code>O(n log n)</code> en todos los casos, mucho mejor que la <code>O(n²)</code> de bubble sort o insertion sort para arreglos grandes." },
            { type: "code", lines: [
              `<span style="${K}">public static int</span>[] mergeSort(<span style="${K}">int</span>[] arreglo) {`,
              `  <span style="${K}">if</span> (arreglo.length &lt;= <span style="${N}">1</span>) {`,
              `    <span style="${K}">return</span> arreglo; <span style="${C}">// caso base: ya está ordenado</span>`,
              `  }`,
              `  <span style="${K}">int</span> medio = arreglo.length / <span style="${N}">2</span>;`,
              `  <span style="${K}">int</span>[] izquierda = mergeSort(<span style="${S}">Arrays</span>.copyOfRange(arreglo, <span style="${N}">0</span>, medio));`,
              `  <span style="${K}">int</span>[] derecha = mergeSort(<span style="${S}">Arrays</span>.copyOfRange(arreglo, medio, arreglo.length));`,
              `  <span style="${K}">return</span> combinar(izquierda, derecha);`,
              `}`,
            ]},
            { type: "note", text: "combinar(izquierda, derecha) mezcla dos listas que ya están ordenadas: compara el primer elemento pendiente de cada una, mueve el menor de los dos al resultado, y repite hasta vaciar ambas listas." },
          ],
          quiz: {
            question: "¿Por qué merge sort logra una complejidad mejor (O(n log n)) que bubble sort (O(n²)) para arreglos grandes?",
            options: [
              "Porque bubble sort solo funciona con números negativos",
              "Porque merge sort no necesita comparar ningún elemento",
              "Porque divide el problema a la mitad en cada nivel de recursión, en lugar de comparar todos los pares posibles",
              "Porque merge sort ordena sin usar recursión",
            ],
            correct: 2,
            ok: "Dividir a la mitad en cada nivel reduce drásticamente el número de comparaciones necesarias frente a comparar cada par adyacente repetidamente, dando O(n log n) en vez de O(n²).",
            bad: "Merge sort sí compara elementos durante el merge, bubble sort funciona con cualquier número, y merge sort depende justamente de la recursión para dividir el arreglo.",
          },
        },
        {
          id: "algo-l12",
          title: "Elegir el algoritmo correcto",
          mins: 18,
          content: [
            { type: "p", html: "No existe un algoritmo de ordenamiento o búsqueda que sea siempre el mejor: la elección depende del tamaño de los datos, de si ya están parcialmente ordenados, de la memoria disponible y de la simplicidad de implementación que necesites." },
            { type: "p", html: "Como regla general: para arreglos pequeños o casi ordenados, insertion sort es simple y suficientemente rápido; para arreglos grandes, merge sort garantiza <code>O(n log n)</code> de forma consistente; y si los datos ya están ordenados, la búsqueda binaria siempre supera a la lineal." },
            { type: "code", lines: [
              `<span style="${K}">SI</span> arreglo.length &lt; <span style="${N}">20</span> <span style="${K}">ENTONCES</span>`,
              `  usar insertion sort`,
              `<span style="${K}">SINO</span>`,
              `  usar merge sort`,
              `<span style="${K}">FIN SI</span>`,
            ]},
          ],
          quiz: {
            question: "Tienes un arreglo de 10 elementos casi ordenado y otro de 10 millones de elementos desordenado. ¿Qué combinación de algoritmos es más razonable?",
            options: [
              "Insertion sort para el arreglo pequeño y casi ordenado, merge sort para el arreglo grande",
              "Usar búsqueda binaria para ordenar ambos arreglos",
              "Usar bubble sort en ambos casos, porque es el más simple de programar",
              "No ordenar el arreglo grande, porque O(n log n) es demasiado lento",
            ],
            correct: 0,
            ok: "Insertion sort aprovecha que el arreglo pequeño ya está casi ordenado; merge sort garantiza O(n log n) consistente, necesario para que el arreglo de 10 millones termine en un tiempo razonable.",
            bad: "Bubble sort no escala bien a 10 millones de elementos, la búsqueda binaria sirve para buscar, no para ordenar, y O(n log n) es precisamente la complejidad que hace viable ordenar arreglos grandes.",
          },
        },
      ],
    },
  ],
};
