const K = 'color: var(--accent-violet)';
const S = 'color: var(--accent-cyan)';
const N = 'color: var(--accent-amber)';
const C = 'color: var(--text-tertiary)';

export default {
  id: "prog2",
  subject: "Programación II",
  tone: "blue",
  title: "Herencia y polimorfismo",
  description: "Programación orientada a objetos en Java: clases, herencia, polimorfismo y colecciones.",
  order: 2,
  prereq: null,
  units: [
    {
      id: "prog2-u1",
      name: "Unidad 1 · Objetos y clases",
      lessons: [
        {
          id: "prog2-l1",
          title: "Clases y objetos",
          mins: 16,
          content: [
            { type: "p", html: "Una <code>clase</code> es una plantilla que define qué <code>atributos</code> (datos) y qué <code>métodos</code> (comportamiento) tendrán los objetos creados a partir de ella. Un <code>objeto</code> es una instancia concreta de una clase, con sus propios valores para cada atributo." },
            { type: "p", html: "Para crear un objeto usas el operador <code>new</code>, que reserva memoria para el objeto y ejecuta su constructor. Cada objeto creado a partir de la misma clase comparte la estructura, pero tiene su propio estado independiente." },
            { type: "code", lines: [
              `<span style="${K}">public class</span> <span style="${S}">Persona</span> {`,
              `  <span style="${S}">String</span> nombre;`,
              `  <span style="${K}">int</span> edad;`,
              `}`,
              ``,
              `<span style="${C}">// Dos objetos de la misma clase, con estado independiente</span>`,
              `<span style="${S}">Persona</span> ana = <span style="${K}">new</span> <span style="${S}">Persona</span>();`,
              `ana.nombre = <span style="${S}">"Ana"</span>;`,
              `<span style="${S}">Persona</span> luis = <span style="${K}">new</span> <span style="${S}">Persona</span>();`,
              `luis.nombre = <span style="${S}">"Luis"</span>;`,
            ]},
            { type: "note", text: "Aunque ana y luis se crean a partir de la misma clase Persona, cada uno guarda su propio valor de nombre y edad en su propio espacio de memoria." },
          ],
          quiz: {
            question: "Después de crear Persona ana = new Persona(); y Persona luis = new Persona(); y asignarles nombres distintos, ¿qué relación tienen ana y luis?",
            options: [
              "Son el mismo objeto con dos nombres distintos",
              "Son dos objetos independientes de la misma clase, cada uno con su propio estado",
              "luis sobrescribe los datos de ana en memoria",
              "No pueden coexistir dos objetos de la misma clase",
            ],
            correct: 1,
            ok: "new crea una instancia nueva cada vez; ana y luis ocupan espacios de memoria distintos y cada uno mantiene su propio valor de nombre y edad.",
            bad: "new siempre reserva memoria nueva, así que no son el mismo objeto, uno no sobrescribe al otro, y una clase puede tener tantas instancias como necesites.",
          },
          extra: {
            type: "blanks",
            prompt: "Completa la clase Libro y la creación de un objeto a partir de ella.",
            payload: {
              code: [
                `<span style="${K}">public</span> <b0> <span style="${S}">Libro</span> {`,
                `  <span style="${S}">String</span> titulo;`,
                `  <span style="${K}">int</span> paginas;`,
                `}`,
                ``,
                `<span style="${S}">Libro</span> favorito = <b1> <span style="${S}">Libro</span>();`,
                `favorito.titulo = <span style="${S}">"Cien años de soledad"</span>;`,
              ],
              bank: ["class", "new", "interface", "static"],
            },
            answer: { blanks: ["class", "new"] },
            ok: "class declara la plantilla Libro con sus atributos, y new reserva memoria para crear un objeto concreto a partir de esa plantilla; interface no admite atributos de instancia así, y static no crea instancias.",
            bad: "interface no permite atributos de instancia como titulo, y static describe un miembro compartido, no una instancia: para declarar la plantilla usas class y para crear el objeto, new.",
          },
        },
        {
          id: "prog2-l2",
          title: "Constructores",
          mins: 14,
          content: [
            { type: "p", html: "Un <code>constructor</code> es un método especial que se ejecuta automáticamente al crear un objeto con <code>new</code>. Tiene el mismo nombre que la clase, no declara tipo de retorno, y se usa para inicializar los atributos del objeto con valores iniciales válidos." },
            { type: "code", lines: [
              `<span style="${K}">public class</span> <span style="${S}">Persona</span> {`,
              `  <span style="${S}">String</span> nombre;`,
              `  <span style="${K}">int</span> edad;`,
              ``,
              `  <span style="${K}">public</span> <span style="${S}">Persona</span>(<span style="${S}">String</span> nombreInicial, <span style="${K}">int</span> edadInicial) {`,
              `    nombre = nombreInicial;`,
              `    edad = edadInicial;`,
              `  }`,
              `}`,
              ``,
              `<span style="${S}">Persona</span> ana = <span style="${K}">new</span> <span style="${S}">Persona</span>(<span style="${S}">"Ana"</span>, <span style="${N}">19</span>);`,
            ]},
            { type: "note", text: "Si no defines ningún constructor, Java genera automáticamente uno vacío sin parámetros; en cuanto defines uno propio, ese constructor por defecto deja de estar disponible." },
          ],
          quiz: {
            question: "¿Cuándo se ejecuta el código dentro del constructor Persona(String nombreInicial, int edadInicial)?",
            options: [
              "Cada vez que accedes a un atributo del objeto",
              "Una sola vez por clase, sin importar cuántos objetos crees",
              "Solo si llamas explícitamente al método constructor()",
              "Automáticamente, en el momento en que se ejecuta new Persona(...)",
            ],
            correct: 3,
            ok: "El constructor se ejecuta automáticamente cada vez que usas new sobre esa clase, inicializando los atributos del objeto recién creado.",
            bad: "No se llama con el nombre constructor() ni se ejecuta al acceder a atributos; y se ejecuta una vez por cada new, no una sola vez por clase.",
          },
          extra: {
            type: "blanks",
            prompt: "Completa el constructor de Libro para que use this y distinga el atributo del parámetro.",
            payload: {
              code: [
                `<span style="${K}">public class</span> <span style="${S}">Libro</span> {`,
                `  <span style="${S}">String</span> titulo;`,
                ``,
                `  <span style="${K}">public</span> <b0>(<span style="${S}">String</span> titulo) {`,
                `    <b1>.titulo = titulo;`,
                `  }`,
                `}`,
              ],
              bank: ["Libro", "this", "new", "void"],
            },
            answer: { blanks: ["Libro", "this"] },
            ok: "El constructor lleva el mismo nombre que la clase, Libro, sin tipo de retorno; y this.titulo distingue el atributo del objeto del parámetro titulo, que tiene el mismo nombre.",
            bad: "El constructor nunca declara void como tipo de retorno, y sin this.titulo el parámetro se asignaría a sí mismo en vez de al atributo del objeto.",
          },
        },
        {
          id: "prog2-l3",
          title: "Encapsulamiento",
          mins: 16,
          content: [
            { type: "p", html: "El <code>encapsulamiento</code> consiste en ocultar los atributos internos de un objeto marcándolos <code>private</code>, y exponer solo el acceso controlado que necesites mediante métodos públicos llamados <code>getters</code> y <code>setters</code>." },
            { type: "p", html: "Esto protege la integridad del objeto: en lugar de permitir que cualquier código externo asigne valores inválidos directamente, el setter puede validar antes de aceptar el cambio." },
            { type: "code", lines: [
              `<span style="${K}">public class</span> <span style="${S}">CuentaBancaria</span> {`,
              `  <span style="${K}">private</span> <span style="${K}">double</span> saldo;`,
              ``,
              `  <span style="${K}">public</span> <span style="${K}">double</span> getSaldo() {`,
              `    <span style="${K}">return</span> saldo;`,
              `  }`,
              ``,
              `  <span style="${K}">public</span> <span style="${K}">void</span> depositar(<span style="${K}">double</span> monto) {`,
              `    <span style="${K}">if</span> (monto &gt; <span style="${N}">0</span>) {`,
              `      saldo += monto;`,
              `    }`,
              `  }`,
              `}`,
            ]},
          ],
          quiz: {
            question: "¿Por qué el atributo saldo se declara private en lugar de public en la clase CuentaBancaria?",
            options: [
              "Para forzar que cualquier modificación pase por métodos como depositar, que pueden validar la operación",
              "Porque private hace que el atributo ocupe menos memoria",
              "Porque los atributos double no pueden ser public en Java",
              "Porque de otro modo la clase no compila",
            ],
            correct: 0,
            ok: "private oculta saldo del exterior; solo métodos como depositar (que valida monto > 0) pueden modificarlo, protegiendo la integridad del objeto.",
            bad: "double sí puede ser public, private no reduce memoria, y una clase con atributos public compila igual: el propósito es controlar el acceso, no evitar errores de compilación.",
          },
          extra: {
            type: "match",
            prompt: "Empareja cada pieza del encapsulamiento con su rol.",
            payload: {
              left: ["private", "getter", "setter", "public"],
              right: [
                "Método que valida y asigna un nuevo valor a un atributo privado",
                "Modificador que expone un miembro para que cualquier código externo lo use directamente",
                "Oculta el atributo para que solo se acceda a través de métodos de la propia clase",
                "Método que devuelve el valor actual de un atributo privado",
              ],
            },
            answer: { pairs: [[0, 2], [1, 3], [2, 0], [3, 1]] },
            ok: "private oculta el atributo, el getter lo expone en modo lectura, el setter lo modifica con validación, y public deja el miembro accesible directamente desde fuera.",
            bad: "No mezcles private (oculta) con public (expone directo): el acceso controlado pasa por getter (lee) y setter (escribe con validación), no por hacer el atributo public.",
          },
        },
      ],
    },
    {
      id: "prog2-u2",
      name: "Unidad 2 · Herencia",
      lessons: [
        {
          id: "prog2-l4",
          title: "Extender clases",
          mins: 18,
          content: [
            { type: "p", html: "La <code>herencia</code> permite que una clase (<code>subclase</code>) reutilice atributos y métodos de otra clase (<code>superclase</code>) usando la palabra clave <code>extends</code>. La subclase hereda todo lo público y protegido de la superclase, y además puede añadir sus propios atributos y métodos." },
            { type: "code", lines: [
              `<span style="${K}">public class</span> <span style="${S}">Animal</span> {`,
              `  <span style="${S}">String</span> nombre;`,
              ``,
              `  <span style="${K}">public</span> <span style="${K}">void</span> comer() {`,
              `    <span style="${S}">System</span>.out.println(nombre + <span style="${S}">" está comiendo"</span>);`,
              `  }`,
              `}`,
              ``,
              `<span style="${K}">public class</span> <span style="${S}">Perro</span> <span style="${K}">extends</span> <span style="${S}">Animal</span> {`,
              `  <span style="${K}">public</span> <span style="${K}">void</span> ladrar() {`,
              `    <span style="${S}">System</span>.out.println(nombre + <span style="${S}">" dice guau"</span>);`,
              `  }`,
              `}`,
            ]},
            { type: "note", text: "Un objeto Perro tiene automáticamente el atributo nombre y el método comer() de Animal, además de su propio método ladrar(): no hace falta reescribirlos." },
          ],
          quiz: {
            question: "La clase Perro extends Animal declara solo el método ladrar(). ¿Puede un objeto Perro llamar a comer(), definido en Animal?",
            options: [
              "No, porque comer() pertenece únicamente a Animal",
              "Solo si Perro vuelve a declarar el método comer()",
              "Sí, porque Perro hereda los métodos públicos de Animal al extenderla",
              "No, porque extends solo hereda atributos, no métodos",
            ],
            correct: 2,
            ok: "extends hace que Perro herede tanto atributos como métodos públicos de Animal, así que un objeto Perro puede llamar a comer() sin redeclararlo.",
            bad: "No hace falta redeclarar comer() para heredarlo, y extends hereda tanto atributos como métodos, no solo uno de los dos.",
          },
          extra: {
            type: "blanks",
            prompt: "Completa la subclase Moto para que herede el método arrancar() de Vehiculo.",
            payload: {
              code: [
                `<span style="${K}">public class</span> <span style="${S}">Vehiculo</span> {`,
                `  <span style="${K}">public</span> <span style="${K}">void</span> arrancar() {`,
                `    <span style="${S}">System</span>.out.println(<span style="${S}">"Motor encendido"</span>);`,
                `  }`,
                `}`,
                ``,
                `<span style="${K}">public class</span> <span style="${S}">Moto</span> <b0> <span style="${S}">Vehiculo</span> {`,
                `  <span style="${K}">public</span> <span style="${K}">void</span> hacerCaballito() {`,
                `    <b1>();`,
                `  }`,
                `}`,
              ],
              bank: ["extends", "arrancar", "implements", "this"],
            },
            answer: { blanks: ["extends", "arrancar"] },
            ok: "extends hace que Moto reutilice el método arrancar() de Vehiculo, así que puede llamarlo por su nombre dentro de hacerCaballito(); implements es para interfaces, no para heredar de una clase concreta.",
            bad: "implements no hereda comportamiento de una clase concreta como Vehiculo, y this() llamaría a un constructor, no al método arrancar(): la subclase necesita extends y la llamada arrancar().",
          },
        },
        {
          id: "prog2-l5",
          title: "super y sobreescritura",
          mins: 18,
          content: [
            { type: "p", html: "Dentro de una subclase, la palabra clave <code>super</code> permite acceder a miembros de la superclase, incluido su constructor con <code>super(...)</code>. La <code>sobreescritura</code> (override) ocurre cuando una subclase redefine un método heredado con la misma firma, para darle un comportamiento distinto." },
            { type: "code", lines: [
              `<span style="${K}">public class</span> <span style="${S}">Animal</span> {`,
              `  <span style="${K}">public</span> <span style="${K}">void</span> hacerSonido() {`,
              `    <span style="${S}">System</span>.out.println(<span style="${S}">"Sonido genérico"</span>);`,
              `  }`,
              `}`,
              ``,
              `<span style="${K}">public class</span> <span style="${S}">Perro</span> <span style="${K}">extends</span> <span style="${S}">Animal</span> {`,
              `  <span style="${K}">@Override</span>`,
              `  <span style="${K}">public</span> <span style="${K}">void</span> hacerSonido() {`,
              `    super.hacerSonido();`,
              `    <span style="${S}">System</span>.out.println(<span style="${S}">"Guau"</span>);`,
              `  }`,
              `}`,
            ]},
            { type: "note", text: "La anotación @Override no es obligatoria, pero le pide al compilador que verifique que realmente estás sobreescribiendo un método existente en la superclase." },
          ],
          quiz: {
            question: "Al llamar hacerSonido() sobre un objeto Perro (cuyo método sobreescrito incluye super.hacerSonido()), ¿qué se imprime?",
            options: [
              "Un error, porque no se puede llamar a super desde un método sobreescrito",
              'Solo "Guau"',
              'Solo "Sonido genérico"',
              'Primero "Sonido genérico" y luego "Guau"',
            ],
            correct: 3,
            ok: 'super.hacerSonido() ejecuta primero la versión de Animal, imprimiendo "Sonido genérico"; después continúa el resto del método y se imprime "Guau".',
            bad: "super.hacerSonido() sí es una llamada válida dentro de un método sobreescrito, y su ejecución sí imprime la versión de la superclase antes de continuar con el resto del método.",
          },
          extra: {
            type: "blanks",
            prompt: "Completa el constructor y la sobreescritura de arrancar() en la subclase Moto.",
            payload: {
              code: [
                `<span style="${K}">public class</span> <span style="${S}">Vehiculo</span> {`,
                `  <span style="${S}">String</span> marca;`,
                `  <span style="${K}">public</span> <span style="${S}">Vehiculo</span>(<span style="${S}">String</span> marca) {`,
                `    <span style="${K}">this</span>.marca = marca;`,
                `  }`,
                `}`,
                ``,
                `<span style="${K}">public class</span> <span style="${S}">Moto</span> <span style="${K}">extends</span> <span style="${S}">Vehiculo</span> {`,
                `  <span style="${K}">public</span> <span style="${S}">Moto</span>(<span style="${S}">String</span> marca) {`,
                `    <b0>(marca);`,
                `  }`,
                ``,
                `  <b1>`,
                `  <span style="${K}">public</span> <span style="${K}">void</span> arrancar() {`,
                `    <span style="${S}">System</span>.out.println(marca + <span style="${S}">" arrancando en dos ruedas"</span>);`,
                `  }`,
                `}`,
              ],
              bank: ["super", "@Override", "this", "extends"],
            },
            answer: { blanks: ["super", "@Override"] },
            ok: "super(marca) invoca el constructor de Vehiculo para inicializar el atributo heredado, y @Override marca que arrancar() redefine el método de la superclase con la misma firma.",
            bad: "this(marca) llamaría a otro constructor de la propia clase Moto, que no existe con esa firma, y extends no se repite dentro del cuerpo: el constructor necesita super y el método, @Override.",
          },
        },
        {
          id: "prog2-l6",
          title: "Clases abstractas",
          mins: 20,
          content: [
            { type: "p", html: "Una <code>clase abstracta</code>, declarada con <code>abstract</code>, no puede instanciarse directamente con <code>new</code>: solo sirve como base para que otras clases la extiendan. Puede mezclar métodos ya implementados con <code>métodos abstractos</code>, que no tienen cuerpo y obligan a cada subclase concreta a implementarlos." },
            { type: "code", lines: [
              `<span style="${K}">public abstract class</span> <span style="${S}">Figura</span> {`,
              `  <span style="${K}">public abstract</span> <span style="${K}">double</span> calcularArea();`,
              ``,
              `  <span style="${K}">public</span> <span style="${K}">void</span> describir() {`,
              `    <span style="${S}">System</span>.out.println(<span style="${S}">"Área: "</span> + calcularArea());`,
              `  }`,
              `}`,
              ``,
              `<span style="${K}">public class</span> <span style="${S}">Circulo</span> <span style="${K}">extends</span> <span style="${S}">Figura</span> {`,
              `  <span style="${K}">double</span> radio = <span style="${N}">3</span>;`,
              ``,
              `  <span style="${K}">public</span> <span style="${K}">double</span> calcularArea() {`,
              `    <span style="${K}">return</span> <span style="${S}">Math</span>.PI * radio * radio;`,
              `  }`,
              `}`,
            ]},
            { type: "note", text: "new Figura() no compila porque Figura es abstracta; solo puedes crear objetos de subclases concretas como Circulo, que implementan calcularArea()." },
          ],
          quiz: {
            question: "¿Por qué new Figura(); no compila si Figura es abstract y declara el método abstracto calcularArea()?",
            options: [
              "Porque las clases abstractas nunca pueden tener métodos con cuerpo",
              "Porque una clase abstracta no puede instanciarse directamente: le falta la implementación de sus métodos abstractos",
              "Porque Figura no tiene ningún atributo declarado",
              "Porque describir() no está marcado como abstract",
            ],
            correct: 1,
            ok: "Una clase abstracta representa un concepto incompleto: no puedes crear un objeto de ella porque calcularArea() no tiene implementación hasta que una subclase la provee.",
            bad: "Las clases abstractas sí pueden mezclar métodos con cuerpo (como describir), la ausencia de atributos no es el problema, y describir() no necesita ser abstract.",
          },
          extra: {
            type: "match",
            prompt: "Empareja cada concepto de clases abstractas con su regla.",
            payload: {
              left: ["Clase abstracta", "Clase concreta", "Método abstracto", "Instanciación con new"],
              right: [
                "Implementa todos los métodos abstractos heredados y puede crearse con new",
                "Reserva memoria para un objeto y ejecuta su constructor; falla si la clase es abstracta",
                "No puede crearse directamente con new; sirve de base para que otras clases la extiendan",
                "Se declara sin cuerpo; cada subclase concreta debe darle su propia implementación",
              ],
            },
            answer: { pairs: [[0, 2], [1, 0], [2, 3], [3, 1]] },
            ok: "Una clase abstracta no se instancia directamente, una clase concreta sí porque implementa todo lo abstracto, un método abstracto no tiene cuerpo hasta que una subclase lo define, y new falla precisamente sobre una clase abstracta.",
            bad: "No mezcles clase abstracta (no instanciable) con clase concreta (sí instanciable): el método abstracto es la pieza sin cuerpo que obliga a implementar, y new es la operación que falla al intentar crear una clase abstracta.",
          },
        },
      ],
    },
    {
      id: "prog2-u3",
      name: "Unidad 3 · Polimorfismo y colecciones",
      lessons: [
        {
          id: "prog2-l7",
          title: "Polimorfismo",
          mins: 20,
          content: [
            { type: "p", html: "El <code>polimorfismo</code> permite tratar objetos de distintas subclases a través de una referencia de su superclase común, y que cada uno ejecute su propia versión sobreescrita de un método. Java decide en tiempo de ejecución qué versión del método invocar, según el tipo real del objeto." },
            { type: "code", lines: [
              `<span style="${K}">public class</span> <span style="${S}">Cuadrado</span> <span style="${K}">extends</span> <span style="${S}">Figura</span> {`,
              `  <span style="${K}">double</span> lado = <span style="${N}">4</span>;`,
              ``,
              `  <span style="${K}">public</span> <span style="${K}">double</span> calcularArea() {`,
              `    <span style="${K}">return</span> lado * lado;`,
              `  }`,
              `}`,
              ``,
              `<span style="${S}">Figura</span>[] figuras = <span style="${K}">new</span> <span style="${S}">Figura</span>[] { <span style="${K}">new</span> <span style="${S}">Circulo</span>(), <span style="${K}">new</span> <span style="${S}">Cuadrado</span>() };`,
              `<span style="${K}">for</span> (<span style="${S}">Figura</span> f : figuras) {`,
              `  f.describir();`,
              `}`,
            ]},
            { type: "note", text: "Aunque el arreglo se declare como Figura[], cada elemento ejecuta calcularArea() según su clase real (Circulo o Cuadrado), no una versión genérica de Figura." },
          ],
          quiz: {
            question: "El arreglo Figura[] figuras guarda un Circulo y un Cuadrado. Al llamar f.describir() para cada f, ¿qué versión de calcularArea() se ejecuta en cada caso?",
            options: [
              "Siempre la de Figura, porque el arreglo es de tipo Figura[]",
              "La primera que se haya compilado en el programa",
              "La sobreescrita en la clase real de cada objeto: Circulo o Cuadrado, según corresponda",
              "Ninguna, porque describir() no puede llamar a un método abstracto",
            ],
            correct: 2,
            ok: "El polimorfismo hace que Java resuelva calcularArea() según el tipo real del objeto en tiempo de ejecución, no según el tipo declarado del arreglo.",
            bad: "El tipo declarado del arreglo no determina qué versión se ejecuta, no depende del orden de compilación, y describir() sí puede invocar un método abstracto porque en tiempo de ejecución siempre hay una implementación concreta.",
          },
          extra: {
            type: "order",
            prompt: "Ordena los pasos del flujo polimórfico al asignar un Circulo a una referencia Figura.",
            payload: {
              lines: [
                { id: "a", html: `<span style="${C}">// Java resuelve calcularArea() según el tipo real del objeto, en tiempo de ejecución</span>` },
                { id: "b", html: `<span style="${S}">Figura</span> f;` },
                { id: "c", html: `f = <span style="${K}">new</span> <span style="${S}">Circulo</span>();` },
                { id: "d", html: `f.calcularArea();` },
              ],
            },
            answer: { order: ["b", "c", "d", "a"] },
            ok: "Primero declaras la referencia con el tipo de la superclase, luego le asignas un objeto de la subclase concreta, después llamas al método por la referencia, y en tiempo de ejecución Java elige la versión sobreescrita según el tipo real del objeto.",
            bad: "No puedes llamar calcularArea() antes de asignar el objeto, ni declarar f después de usarla: el orden es declarar → asignar → llamar → resolver en tiempo de ejecución.",
          },
        },
        {
          id: "prog2-l8",
          title: "Interfaces",
          mins: 18,
          content: [
            { type: "p", html: "Una <code>interfaz</code>, declarada con <code>interface</code>, define un contrato de métodos que una clase se compromete a implementar con la palabra clave <code>implements</code>. A diferencia de una clase abstracta, una clase puede implementar varias interfaces a la vez, aunque solo puede extender una superclase." },
            { type: "code", lines: [
              `<span style="${K}">public interface</span> <span style="${S}">Ordenable</span> {`,
              `  <span style="${K}">int</span> comparar(<span style="${S}">Object</span> otro);`,
              `}`,
              ``,
              `<span style="${K}">public class</span> <span style="${S}">Producto</span> <span style="${K}">implements</span> <span style="${S}">Ordenable</span> {`,
              `  <span style="${K}">double</span> precio;`,
              ``,
              `  <span style="${K}">public</span> <span style="${K}">int</span> comparar(<span style="${S}">Object</span> otro) {`,
              `    <span style="${K}">return</span> <span style="${N}">0</span>;`,
              `  }`,
              `}`,
            ]},
            { type: "note", text: "Si Producto omite el método comparar(), el compilador rechaza la clase: implementar una interfaz obliga a definir todos sus métodos." },
          ],
          quiz: {
            question: "¿Cuál es una diferencia clave entre implementar una interfaz y extender una clase abstracta?",
            options: [
              "Una clase puede implementar varias interfaces, pero solo puede extender una única superclase",
              "extends e implements hacen exactamente lo mismo en Java",
              "Una clase abstracta permite extender varias a la vez, igual que una interfaz",
              "Una interfaz nunca puede declarar métodos",
            ],
            correct: 0,
            ok: "Java permite herencia múltiple de interfaces (implements varias) pero solo herencia simple de clases (extends una sola superclase).",
            bad: "Una interfaz sí declara métodos (su contrato), extends e implements no son intercambiables, y la restricción de una sola superclase aplica solo a extends, no a implements.",
          },
          extra: {
            type: "blanks",
            prompt: "Completa la interfaz Volador y la clase Ave que la implementa.",
            payload: {
              code: [
                `<span style="${K}">public</span> <b0> <span style="${S}">Volador</span> {`,
                `  <span style="${K}">void</span> volar();`,
                `}`,
                ``,
                `<span style="${K}">public class</span> <span style="${S}">Ave</span> <b1> <span style="${S}">Volador</span> {`,
                `  <span style="${K}">public</span> <span style="${K}">void</span> volar() {`,
                `    <span style="${S}">System</span>.out.println(<span style="${S}">"El ave vuela"</span>);`,
                `  }`,
                `}`,
              ],
              bank: ["interface", "implements", "class", "extends"],
            },
            answer: { blanks: ["interface", "implements"] },
            ok: "interface declara el contrato Volador con el método volar() sin cuerpo, e implements obliga a la clase Ave a proveer su propia implementación de ese método.",
            bad: "class declararía Volador como una clase normal, no como un contrato, y extends es para heredar de una superclase concreta, no para cumplir una interfaz: aquí hacen falta interface e implements.",
          },
        },
        {
          id: "prog2-l9",
          title: "ArrayList y colecciones",
          mins: 20,
          content: [
            { type: "p", html: "Un <code>ArrayList</code> es una lista de tamaño dinámico de la biblioteca estándar de Java: a diferencia de un arreglo (<code>[]</code>), puede crecer o encogerse durante la ejecución. Se declara con un tipo genérico entre <code>&lt;&gt;</code> que indica qué clase de elementos contiene." },
            { type: "code", lines: [
              `<span style="${K}">import</span> java.util.<span style="${S}">ArrayList</span>;`,
              ``,
              `<span style="${S}">ArrayList</span>&lt;<span style="${S}">String</span>&gt; nombres = <span style="${K}">new</span> <span style="${S}">ArrayList</span>&lt;&gt;();`,
              `nombres.add(<span style="${S}">"Ana"</span>);`,
              `nombres.add(<span style="${S}">"Luis"</span>);`,
              `nombres.remove(<span style="${S}">"Ana"</span>);`,
              `<span style="${S}">System</span>.out.println(nombres.size());`,
            ]},
            { type: "note", text: "A diferencia de un arreglo, un ArrayList no necesita un tamaño fijo al crearlo: add y remove ajustan su tamaño automáticamente." },
          ],
          quiz: {
            question: 'Después de agregar "Ana" y "Luis" y luego eliminar "Ana" con nombres.remove("Ana");, ¿qué imprime nombres.size()?',
            options: [
              "2",
              "1",
              "0",
              "Un error, porque ArrayList no admite remove por valor",
            ],
            correct: 1,
            ok: "Se agregan dos elementos y se elimina uno, así que queda un solo elemento en la lista: size() devuelve 1.",
            bad: "ArrayList sí admite remove(Object) para eliminar por valor, y tras esa eliminación queda exactamente un elemento, ni cero ni dos.",
          },
          extra: {
            type: "blanks",
            prompt: "Completa las operaciones para leer el primer color y contar cuántos hay en la lista.",
            payload: {
              code: [
                `<span style="${K}">import</span> java.util.<span style="${S}">ArrayList</span>;`,
                ``,
                `<span style="${S}">ArrayList</span>&lt;<span style="${S}">String</span>&gt; colores = <span style="${K}">new</span> <span style="${S}">ArrayList</span>&lt;&gt;();`,
                `colores.add(<span style="${S}">"Rojo"</span>);`,
                `colores.add(<span style="${S}">"Azul"</span>);`,
                `<span style="${S}">String</span> primero = colores.<b0>(<span style="${N}">0</span>);`,
                `<span style="${K}">int</span> total = colores.<b1>();`,
              ],
              bank: ["get", "size", "add", "remove"],
            },
            answer: { blanks: ["get", "size"] },
            ok: "get(0) devuelve el elemento en la posición indicada, y size() devuelve cuántos elementos tiene la lista en ese momento; add agrega, no lee, y remove elimina, no cuenta.",
            bad: "add serviría para agregar, no para leer un elemento por posición, y remove elimina en vez de contar: para leer usas get y para contar, size.",
          },
        },
      ],
    },
  ],
};
