const K = 'color: var(--accent-violet)';
const S = 'color: var(--accent-cyan)';
const N = 'color: var(--accent-amber)';
const C = 'color: var(--text-tertiary)';

export default {
  id: "prog1",
  subject: "Programación I",
  tone: "blue",
  title: "Fundamentos y control de flujo",
  description: "Tus primeros programas en Java: variables, condicionales, bucles y funciones.",
  order: 5,
  prereq: null,
  units: [
    {
      id: "prog1-u1",
      name: "Unidad 1 · Primeros pasos",
      lessons: [
        {
          id: "prog1-l1",
          title: "Qué es programar",
          mins: 10,
          content: [
            { type: "p", html: "Programar es escribir instrucciones precisas que una computadora ejecuta paso a paso. Un <code>programa</code> es una secuencia ordenada de instrucciones escritas en un <code>lenguaje de programación</code> como Java, que el computador traduce a instrucciones que su procesador puede ejecutar." },
            { type: "p", html: "Todo programa sigue el mismo ciclo: recibe una <code>entrada</code>, la procesa aplicando una lógica definida, y produce una <code>salida</code>. Aprender a programar es aprender a descomponer un problema en esos tres pasos." },
            { type: "code", lines: [
              `<span style="${C}">// Todo programa Java necesita una clase con un método main</span>`,
              `<span style="${K}">public class</span> <span style="${S}">Hola</span> {`,
              `  <span style="${K}">public static void</span> main(<span style="${S}">String</span>[] args) {`,
              `    <span style="${S}">System</span>.out.println(<span style="${S}">"¡Hola, mundo!"</span>);`,
              `  }`,
              `}`,
            ]},
            { type: "note", text: "El método main es el punto de entrada: la máquina virtual de Java empieza a ejecutar el programa ahí." },
          ],
          quiz: {
            question: "¿Cuál es el punto de entrada de todo programa Java, el método que la máquina virtual ejecuta primero?",
            options: [
              "El primer método declarado en el archivo",
              "El método main",
              "El constructor de la clase",
              "El método println",
            ],
            correct: 1,
            ok: "La JVM busca específicamente el método main dentro de la clase que le indiques; ahí empieza la ejecución.",
            bad: "No es el primero declarado, ni el constructor, ni println: la JVM busca por convención el método main.",
          },
        },
        {
          id: "prog1-l2",
          title: "Variables y tipos de datos",
          mins: 14,
          content: [
            { type: "p", html: "Una <code>variable</code> es un espacio de memoria con nombre que guarda un valor que puede cambiar durante la ejecución. En Java, toda variable se declara con un <code>tipo de dato</code> fijo: ese tipo determina qué valores puede guardar y cuánta memoria ocupa." },
            { type: "p", html: "Los tipos primitivos más comunes son <code>int</code> (enteros), <code>double</code> (decimales), <code>boolean</code> (verdadero o falso) y <code>char</code> (un carácter). Para texto se usa la clase <code>String</code>, que no es primitiva pero se comporta como un tipo básico." },
            { type: "code", lines: [
              `<span style="${C}">// Declaración con tipo explícito e inicialización</span>`,
              `<span style="${K}">int</span> edad = <span style="${N}">19</span>;`,
              `<span style="${K}">double</span> promedio = <span style="${N}">4.5</span>;`,
              `<span style="${K}">boolean</span> aprobado = <span style="${K}">true</span>;`,
              `<span style="${S}">String</span> nombre = <span style="${S}">"Ana"</span>;`,
            ]},
            { type: "note", text: "Java es de tipado estático: una vez declarada una variable con un tipo, no puedes asignarle un valor de otro tipo sin conversión explícita." },
          ],
          quiz: {
            question: 'Con int edad = 19; y String nombre = "Ana";, ¿qué diferencia principal hay entre las dos variables?',
            options: [
              "String solo puede usarse dentro de un método main",
              "int no puede reasignarse después de declararlo",
              "Ninguna, ambas son variables del mismo tipo",
              "int guarda un entero primitivo y String guarda una cadena de texto",
            ],
            correct: 3,
            ok: "int es un tipo primitivo para números enteros; String es una clase que representa texto. Cada tipo define qué valores y operaciones admite.",
            bad: "String no está restringido a main, una variable int normal sí puede reasignarse, y ambas variables no son del mismo tipo.",
          },
        },
        {
          id: "prog1-l3",
          title: "Operadores y expresiones",
          mins: 14,
          content: [
            { type: "p", html: "Los <code>operadores aritméticos</code> (<code>+</code>, <code>-</code>, <code>*</code>, <code>/</code>, <code>%</code>) combinan valores numéricos en una <code>expresión</code>. El operador <code>%</code> (módulo) devuelve el resto de una división entera, útil para saber si un número es par o impar." },
            { type: "p", html: "Los <code>operadores relacionales</code> (<code>==</code>, <code>!=</code>, <code>&lt;</code>, <code>&gt;</code>) comparan dos valores y producen un <code>boolean</code>. Los <code>operadores lógicos</code> (<code>&amp;&amp;</code>, <code>||</code>, <code>!</code>) combinan condiciones booleanas." },
            { type: "code", lines: [
              `<span style="${C}">// El resto de dividir 7 entre 2 es 1: número impar</span>`,
              `<span style="${K}">int</span> numero = <span style="${N}">7</span>;`,
              `<span style="${K}">boolean</span> esPar = (numero % <span style="${N}">2</span> == <span style="${N}">0</span>);`,
              `<span style="${K}">boolean</span> enRango = (numero &gt; <span style="${N}">0</span> &amp;&amp; numero &lt; <span style="${N}">10</span>);`,
            ]},
          ],
          quiz: {
            question: "¿Qué valor tiene la expresión numero % 2 == 0 cuando numero vale 7?",
            options: [
              "false, porque el resto de 7 entre 2 es 1, no 0",
              "true, porque 7 es un número par",
              "Un error de compilación, porque % no existe en Java",
              "0, porque % siempre devuelve el resto sin convertir a boolean",
            ],
            correct: 0,
            ok: "7 % 2 da como resto 1; 1 == 0 es false, así que la expresión completa evalúa a false: 7 es impar.",
            bad: "7 es impar, no par; % sí es un operador válido en Java, y el resultado de la expresión completa es un boolean, no el resto crudo.",
          },
        },
        {
          id: "prog1-l4",
          title: "Entrada y salida",
          mins: 12,
          content: [
            { type: "p", html: "Para mostrar resultados en la consola usas <code>System.out.println</code> (imprime y salta de línea) o <code>System.out.print</code> (imprime sin saltar). Para leer datos que escribe el usuario, Java ofrece la clase <code>Scanner</code>, que lee desde la entrada estándar." },
            { type: "code", lines: [
              `<span style="${K}">import</span> java.util.<span style="${S}">Scanner</span>;`,
              ``,
              `<span style="${S}">Scanner</span> teclado = <span style="${K}">new</span> <span style="${S}">Scanner</span>(<span style="${S}">System</span>.in);`,
              `<span style="${S}">System</span>.out.print(<span style="${S}">"Ingresa tu edad: "</span>);`,
              `<span style="${K}">int</span> edad = teclado.nextInt();`,
              `<span style="${S}">System</span>.out.println(<span style="${S}">"Tienes "</span> + edad + <span style="${S}">" años"</span>);`,
            ]},
            { type: "note", text: "Cada método de Scanner (nextInt, nextDouble, nextLine) espera un tipo específico; si el usuario escribe texto donde se espera un número, el programa lanza una excepción." },
          ],
          quiz: {
            question: "¿Qué clase de Java usas para leer un número entero que el usuario escribe en la consola?",
            options: [
              "System.out",
              "String",
              "Scanner",
              "Integer",
            ],
            correct: 2,
            ok: "Scanner conecta con la entrada estándar; su método nextInt() lee y convierte el texto escrito en un valor int.",
            bad: "System.out es para escribir, no leer; String almacena texto ya leído; Integer solo envuelve un valor entero, no lee entrada.",
          },
        },
      ],
    },
    {
      id: "prog1-u2",
      name: "Unidad 2 · Control de flujo",
      lessons: [
        {
          id: "prog1-l5",
          title: "Condicionales if y else",
          mins: 16,
          content: [
            { type: "p", html: "La instrucción <code>if</code> ejecuta un bloque de código solo si una condición booleana es verdadera. El bloque <code>else</code>, opcional, se ejecuta cuando la condición del if es falsa." },
            { type: "p", html: "Puedes encadenar condiciones con <code>else if</code> para evaluar varias alternativas en orden; Java evalúa cada condición hasta encontrar la primera verdadera y ejecuta solo ese bloque." },
            { type: "code", lines: [
              `<span style="${K}">int</span> nota = <span style="${N}">85</span>;`,
              `<span style="${K}">if</span> (nota &gt;= <span style="${N}">90</span>) {`,
              `  <span style="${S}">System</span>.out.println(<span style="${S}">"Sobresaliente"</span>);`,
              `} <span style="${K}">else if</span> (nota &gt;= <span style="${N}">70</span>) {`,
              `  <span style="${S}">System</span>.out.println(<span style="${S}">"Aprobado"</span>);`,
              `} <span style="${K}">else</span> {`,
              `  <span style="${S}">System</span>.out.println(<span style="${S}">"Reprobado"</span>);`,
              `}`,
            ]},
            { type: "note", text: "Aunque nota también cumpla la condición del else if, si ya cumplió la condición del if ese bloque nunca se evalúa: el orden de las condiciones importa." },
          ],
          quiz: {
            question: "Con nota = 85, ¿qué imprime el bloque if / else if / else anterior?",
            options: [
              "Sobresaliente",
              "Aprobado",
              "Reprobado",
              "No imprime nada",
            ],
            correct: 1,
            ok: '85 no cumple la condición del if (>= 90) pero sí la del else if (>= 70), así que entra ahí e imprime "Aprobado".',
            bad: "85 es menor que 90, así que no imprime Sobresaliente; sí cumple >= 70, así que no cae en Reprobado ni se queda sin imprimir.",
          },
        },
        {
          id: "prog1-l6",
          title: "El switch",
          mins: 12,
          content: [
            { type: "p", html: "La instrucción <code>switch</code> compara una variable contra varios valores posibles y ejecuta el bloque <code>case</code> que coincide. Es una alternativa más legible que una cadena larga de <code>else if</code> cuando comparas contra valores concretos." },
            { type: "code", lines: [
              `<span style="${K}">int</span> dia = <span style="${N}">3</span>;`,
              `<span style="${K}">switch</span> (dia) {`,
              `  <span style="${K}">case</span> <span style="${N}">1</span>:`,
              `    <span style="${S}">System</span>.out.println(<span style="${S}">"Lunes"</span>);`,
              `    <span style="${K}">break</span>;`,
              `  <span style="${K}">case</span> <span style="${N}">3</span>:`,
              `    <span style="${S}">System</span>.out.println(<span style="${S}">"Miércoles"</span>);`,
              `    <span style="${K}">break</span>;`,
              `  <span style="${K}">default</span>:`,
              `    <span style="${S}">System</span>.out.println(<span style="${S}">"Otro día"</span>);`,
              `}`,
            ]},
            { type: "note", text: "Si olvidas el break, la ejecución cae al siguiente case (fall-through) y ejecuta también su código, aunque no coincida con la variable." },
          ],
          quiz: {
            question: "Si eliminas el break; del case 1 en el switch anterior y dia vale 1, ¿qué ocurre?",
            options: [
              "El programa no compila",
              "Solo se ejecuta el case 1 y se detiene ahí",
              "Se ejecuta el default en lugar del case 1",
              "Se ejecuta el case 1 y también cae al siguiente case hasta encontrar un break",
            ],
            correct: 3,
            ok: "Sin break, Java sigue ejecutando los case siguientes en orden (fall-through) hasta toparse con un break o el final del switch.",
            bad: "El código sí compila sin break; no salta directo a default y no se detiene después del primer case: continúa cayendo hacia los siguientes.",
          },
        },
        {
          id: "prog1-l7",
          title: "Bucles while",
          mins: 16,
          content: [
            { type: "p", html: "El bucle <code>while</code> repite un bloque de código mientras una condición se mantenga verdadera. La condición se evalúa antes de cada repetición, así que si es falsa desde el inicio, el bloque no se ejecuta ni una vez." },
            { type: "code", lines: [
              `<span style="${K}">int</span> contador = <span style="${N}">0</span>;`,
              `<span style="${K}">while</span> (contador &lt; <span style="${N}">5</span>) {`,
              `  <span style="${S}">System</span>.out.println(<span style="${S}">"Vuelta "</span> + contador);`,
              `  contador++;`,
              `}`,
            ]},
            { type: "note", text: "Si olvidas actualizar la variable de control dentro del bucle, la condición nunca cambia y el bucle se repite para siempre: un bucle infinito." },
          ],
          quiz: {
            question: "¿Cuántas veces imprime \"Vuelta\" el bucle while (contador < 5) si contador empieza en 0 y se incrementa en 1 cada vuelta?",
            options: [
              "5 veces, para contador 0, 1, 2, 3 y 4",
              "4 veces, para contador 1, 2, 3 y 4",
              "6 veces, para contador 0 a 5",
              "Una sola vez, porque while solo evalúa la condición una vez",
            ],
            correct: 0,
            ok: "El bucle se repite mientras contador sea menor que 5: para 0, 1, 2, 3 y 4 la condición es verdadera, y se detiene al llegar a 5.",
            bad: "El bucle sí incluye contador = 0, se detiene antes de llegar a 5 (no lo incluye), y evalúa la condición en cada vuelta, no solo una vez.",
          },
        },
        {
          id: "prog1-l8",
          title: "Bucles for",
          mins: 16,
          content: [
            { type: "p", html: "El bucle <code>for</code> agrupa en una sola línea la inicialización, la condición de repetición y la actualización de la variable de control, lo que lo hace ideal cuando sabes de antemano cuántas veces quieres repetir algo." },
            { type: "code", lines: [
              `<span style="${K}">for</span> (<span style="${K}">int</span> i = <span style="${N}">0</span>; i &lt; <span style="${N}">5</span>; i++) {`,
              `  <span style="${S}">System</span>.out.println(<span style="${S}">"Elemento "</span> + i);`,
              `}`,
            ]},
            { type: "note", text: "Las tres partes del for van separadas por punto y coma, y cualquiera de ellas puede quedar vacía si no la necesitas." },
          ],
          quiz: {
            question: "¿Qué parte del for (int i = 0; i < 5; i++) se ejecuta exactamente una sola vez, al principio?",
            options: [
              "La condición i < 5",
              "La actualización i++",
              "La inicialización int i = 0",
              "El cuerpo del bucle",
            ],
            correct: 2,
            ok: "La inicialización se ejecuta una única vez, antes de la primera evaluación de la condición; condición, cuerpo y actualización se repiten en cada vuelta.",
            bad: "La condición y la actualización se repiten en cada vuelta, igual que el cuerpo; solo la inicialización ocurre una vez al arrancar el bucle.",
          },
        },
      ],
    },
    {
      id: "prog1-u3",
      name: "Unidad 3 · Funciones",
      lessons: [
        {
          id: "prog1-l9",
          title: "Definir y llamar métodos",
          mins: 18,
          content: [
            { type: "p", html: "Un <code>método</code> agrupa un bloque de código bajo un nombre, para poder ejecutarlo (llamarlo) las veces que necesites sin repetir su lógica. Se declara con un tipo de retorno, un nombre y una lista de parámetros entre paréntesis." },
            { type: "code", lines: [
              `<span style="${K}">public static void</span> saludar() {`,
              `  <span style="${S}">System</span>.out.println(<span style="${S}">"¡Hola!"</span>);`,
              `}`,
              ``,
              `<span style="${K}">public static void</span> main(<span style="${S}">String</span>[] args) {`,
              `  saludar();`,
              `  saludar();`,
              `}`,
            ]},
            { type: "note", text: "static permite llamar al método directamente desde main sin crear un objeto de la clase primero." },
          ],
          quiz: {
            question: 'En el código anterior, ¿cuántas veces se imprime "¡Hola!" en total?',
            options: [
              "Una vez",
              "Dos veces",
              "Ninguna, porque saludar() nunca se llama",
              "Tres veces",
            ],
            correct: 1,
            ok: "main llama a saludar() dos veces seguidas, y cada llamada ejecuta el println una vez: dos impresiones en total.",
            bad: "saludar() sí se llama, y se llama exactamente dos veces, no una ni tres.",
          },
        },
        {
          id: "prog1-l10",
          title: "Parámetros y retorno",
          mins: 18,
          content: [
            { type: "p", html: "Un método puede recibir <code>parámetros</code>: variables locales que reciben los valores pasados al llamarlo. Si el método produce un resultado, lo entrega con <code>return</code>, y su tipo de retorno debe coincidir con el declarado en la firma." },
            { type: "code", lines: [
              `<span style="${K}">public static int</span> sumar(<span style="${K}">int</span> a, <span style="${K}">int</span> b) {`,
              `  <span style="${K}">return</span> a + b;`,
              `}`,
              ``,
              `<span style="${K}">public static void</span> main(<span style="${S}">String</span>[] args) {`,
              `  <span style="${K}">int</span> resultado = sumar(<span style="${N}">3</span>, <span style="${N}">4</span>);`,
              `  <span style="${S}">System</span>.out.println(resultado);`,
              `}`,
            ]},
            { type: "note", text: "Un método con tipo de retorno void no usa return para entregar un valor; puede usar un return vacío solo para salir antes de tiempo." },
          ],
          quiz: {
            question: "¿Qué valor guarda resultado después de ejecutar int resultado = sumar(3, 4);?",
            options: [
              "3",
              "4",
              '"3 4"',
              "7",
            ],
            correct: 3,
            ok: "sumar(3, 4) ejecuta return a + b con a=3 y b=4, así que devuelve 7, el valor que queda guardado en resultado.",
            bad: "El método no devuelve solo uno de los parámetros ni concatena texto: suma los dos enteros y devuelve 7.",
          },
        },
        {
          id: "prog1-l11",
          title: "Ámbito de variables",
          mins: 14,
          content: [
            { type: "p", html: "El <code>ámbito</code> (scope) de una variable es la región del código donde esa variable existe y puede usarse. Una variable declarada dentro de un método o de un bloque <code>{ }</code> solo vive dentro de ese bloque; fuera de él, el compilador no la reconoce." },
            { type: "code", lines: [
              `<span style="${K}">public static void</span> ejemplo() {`,
              `  <span style="${K}">int</span> x = <span style="${N}">10</span>;`,
              `  <span style="${K}">if</span> (x &gt; <span style="${N}">5</span>) {`,
              `    <span style="${K}">int</span> y = <span style="${N}">20</span>;`,
              `    <span style="${S}">System</span>.out.println(x + y);`,
              `  }`,
              `  <span style="${C}">// aquí y ya no existe</span>`,
              `}`,
            ]},
          ],
          quiz: {
            question: "En el método ejemplo() anterior, ¿por qué no puedes usar la variable y después del bloque if?",
            options: [
              "Porque su ámbito termina en la llave de cierre del bloque if donde fue declarada",
              "Porque y nunca se inicializó",
              "Porque las variables int no pueden declararse dentro de un if",
              "Porque x e y tienen el mismo nombre",
            ],
            correct: 0,
            ok: "y se declaró dentro del bloque if, así que su ámbito termina en la llave de cierre de ese bloque; fuera de él, el compilador no la reconoce.",
            bad: "y sí se inicializó, los int sí pueden declararse dentro de un if, y x e y tienen nombres distintos; el problema real es el ámbito del bloque.",
          },
        },
        {
          id: "prog1-l12",
          title: "Descomposición de problemas",
          mins: 20,
          content: [
            { type: "p", html: "<code>Descomponer</code> un problema significa dividirlo en subproblemas más pequeños y manejables, cada uno resuelto por su propio método. Un programa grande escrito como un único bloque de código es difícil de leer, probar y corregir; dividirlo en métodos con una sola responsabilidad facilita las tres cosas." },
            { type: "p", html: "Una buena señal de que necesitas descomponer: si un método hace más de una cosa claramente distinta (leer datos, calcular un resultado, mostrar la salida), cada una de esas tareas puede convertirse en su propio método." },
            { type: "code", lines: [
              `<span style="${K}">public static double</span> calcularPromedio(<span style="${K}">int</span>[] notas) {`,
              `  <span style="${K}">int</span> suma = <span style="${N}">0</span>;`,
              `  <span style="${K}">for</span> (<span style="${K}">int</span> n : notas) {`,
              `    suma += n;`,
              `  }`,
              `  <span style="${K}">return</span> (<span style="${K}">double</span>) suma / notas.length;`,
              `}`,
              ``,
              `<span style="${K}">public static void</span> mostrarResultado(<span style="${K}">double</span> promedio) {`,
              `  <span style="${S}">System</span>.out.println(<span style="${S}">"Promedio: "</span> + promedio);`,
              `}`,
            ]},
            { type: "note", text: "Separar calcularPromedio de mostrarResultado permite reutilizar el cálculo en otro contexto, como guardarlo en un archivo, sin tocar la lógica de impresión." },
          ],
          quiz: {
            question: "¿Cuál es la principal ventaja de dividir calcularPromedio y mostrarResultado en dos métodos separados, en lugar de mezclar cálculo e impresión en uno solo?",
            options: [
              "El programa ocupa menos memoria en tiempo de ejecución",
              "Java exige que cada clase tenga al menos dos métodos",
              "Cada método tiene una responsabilidad clara y se puede reutilizar o probar por separado",
              "Los bucles for solo funcionan dentro de métodos con retorno double",
            ],
            correct: 2,
            ok: "Separar responsabilidades hace que cada método sea más fácil de entender, probar y reutilizar sin arrastrar la lógica de impresión.",
            bad: "La separación no reduce memoria de forma relevante, Java no exige un mínimo de métodos, y el for funciona en cualquier método, no solo en los que retornan double.",
          },
        },
      ],
    },
  ],
};
