const K = 'color: var(--accent-violet)';
const S = 'color: var(--accent-cyan)';
const N = 'color: var(--accent-amber)';
const C = 'color: var(--text-tertiary)';

export default {
  id: "uml",
  subject: "Ingeniería de software",
  tone: "violet",
  title: "Modelado con UML",
  description: "Dibuja lo que el software es y lo que hace: los nueve diagramas que convierten requisitos en diseño.",
  order: 8,
  prereq: "reqsw",
  units: [
    {
      id: "uml-u1",
      name: "Unidad 1 · El lenguaje y el comportamiento",
      lessons: [
        {
          id: "um1",
          title: "UML: un lenguaje, no un método",
          mins: 14,
          content: [
            { type: "p", html: "<code>UML</code> (Unified Modeling Language) es un lenguaje VISUAL estándar para modelar software, mantenido por el <code>OMG</code> (Object Management Group). Ojo con la trampa: UML no es una metodología ni un proceso — no te dice EN QUÉ ORDEN trabajar ni cómo organizar tu equipo, como sí hacen Scrum o el modelo en cascada. Tampoco es un lenguaje de programación: un diagrama de clases no se ejecuta, describe la forma que después alguien traduce a código en Java, Python o el lenguaje que sea." },
            { type: "p", html: "¿Para qué sirve entonces dibujar? Para tres cosas que un párrafo de texto hace peor: <code>comunicar</code> una idea de diseño de un vistazo entre personas que no comparten el mismo vocabulario técnico, <code>razonar</code> sobre un problema ANTES de escribir una sola línea de código (un diagrama mal armado se corrige en un pizarrón; un diseño mal armado se corrige refactorizando), y <code>documentar</code> decisiones que de otro modo solo viven en la cabeza de quien las tomó." },
            { type: "p", html: "UML 2.x define catorce tipos de diagramas, pero en este curso cubrimos nueve fundamentales, divididos en dos familias. Los de <code>estructura</code> retratan el sistema QUIETO: sus piezas y cómo se relacionan — clases, objetos, componentes. Los de <code>comportamiento</code> retratan el sistema EN MOVIMIENTO: qué hace y cómo cambia — casos de uso, actividades, estados, secuencia, tiempo. La pregunta que separa ambas familias es simple: ¿el diagrama describe una foto o una película?" },
            { type: "code", lines: [
              `<span style="${C}">── Las dos familias de UML ─────────────────────</span>`,
              `<span style="${K}">Estructura</span>      clases, objetos, componentes`,
              `<span style="${S}">Comportamiento</span>  casos de uso, actividades,`,
              `                estados, secuencia, tiempo`,
            ]},
            { type: "note", text: "Piensa en los planos de una casa: el plano de la estructura (paredes, cimientos) es la familia estructural; el plano eléctrico mostrando cuándo se enciende cada circuito es la familia de comportamiento. Ambos describen la misma casa desde ángulos distintos." },
          ],
          quiz: {
            question: "¿Qué es UML?",
            options: [
              "Una metodología que define en qué orden deben ejecutarse las fases de un proyecto",
              "Un lenguaje visual estándar para modelar sistemas",
              "Un lenguaje de programación orientado a objetos, como Java o C++",
              "Una herramienta concreta de dibujo, como una aplicación específica de diagramación",
            ],
            correct: 1,
            ok: "UML es un lenguaje VISUAL con notación estandarizada por el OMG: define cómo se dibuja una clase o un caso de uso, pero no impone un proceso de trabajo ni se compila — no es una metodología ni un lenguaje de programación.",
            bad: "No confundas el lenguaje con el proceso: una metodología dicta el ORDEN de trabajo (eso es Scrum o cascada, no UML); un lenguaje de programación se ejecuta (un diagrama no); y UML es el estándar en sí, no una app concreta que lo dibuje.",
          },
          extra: {
            type: "match",
            prompt: "Empareja cada diagrama con su propósito específico.",
            payload: {
              left: ["Diagrama de clases", "Diagrama de secuencia", "Diagrama de casos de uso", "Diagrama de componentes"],
              right: [
                "Muestra las piezas del sistema y las interfaces que las conectan",
                "Muestra qué le ofrece el sistema a cada actor externo",
                "Muestra la estructura estática del sistema y las relaciones entre sus elementos",
                "Muestra los mensajes que se intercambian los objetos, ordenados en el tiempo",
              ],
            },
            answer: { pairs: [[0, 2], [1, 3], [2, 1], [3, 0]] },
            ok: "Cada diagrama mira el sistema desde un ángulo distinto: clases fija la estructura estática y sus relaciones, secuencia ordena los mensajes en el tiempo, casos de uso muestra qué le ofrece el sistema a cada actor, y componentes expone las piezas y sus interfaces.",
            bad: "No los confundas por familia: clases y componentes son estructura, pero uno describe relaciones internas y el otro piezas con interfaz; secuencia y casos de uso son comportamiento, pero uno ordena mensajes en el tiempo y el otro describe el objetivo de un actor.",
          },
        },
        {
          id: "um2",
          title: "Casos de uso",
          mins: 16,
          content: [
            { type: "p", html: "El diagrama de <code>casos de uso</code> mira el sistema desde AFUERA: qué ofrece y a quién. Un <code>actor</code> es un ROL externo que interactúa con el sistema — puede ser una persona (Socio) u otro sistema (la pasarela de pagos); nunca es una parte interna. Un <code>caso de uso</code> es un objetivo con valor observable para ese actor: prestar un libro, no \"consultar la base de datos\"." },
            { type: "p", html: "La notación: el actor fuera, los casos como óvalos dentro de la caja del sistema (la frontera), y líneas que los conectan. Dos relaciones entre casos confunden a todo el mundo: <code>«include»</code> — un paso común factorizado que se ejecuta SIEMPRE — y <code>«extend»</code> — comportamiento opcional que solo ocurre bajo condición." },
            { type: "code", lines: [
              `<span style="${C}">── Casos de uso · biblioteca ──────────────────</span>`,
              `┌─────────┐      ( Prestar libro )`,
              `│ «actor» │────▶(                 )`,
              `│  Socio  │      (_______________)`,
              `└─────────┘             │`,
              `                  <span style="${N}">«include»</span>`,
              `                         ▼`,
              `                 ( Validar socio )`,
            ]},
            { type: "p", html: "Léelo así: cada vez que un Socio presta un libro, el sistema SIEMPRE valida al socio primero — por eso es <code>«include»</code>. En cambio, \"Pagar multa\" solo ocurre si devuelve con retraso: eso sería <code>«extend»</code> sobre \"Devolver libro\"." },
            { type: "note", text: "Regla mental: «include» es el peaje obligatorio de la autopista; «extend» es la parada opcional en la estación de servicio." },
          ],
          quiz: {
            question: "En la biblioteca, \"Pagar multa\" ocurre solo si el socio devuelve con retraso. ¿Cómo se modela respecto a \"Devolver libro\"?",
            options: [
              "Con «include»: siempre forma parte de Devolver libro",
              "Como una generalización del caso Devolver libro",
              "Como una asociación simple entre dos actores",
              "Con «extend»: extiende Devolver libro solo bajo condición",
            ],
            correct: 3,
            ok: "«extend» modela lo condicional: Pagar multa solo se ejecuta si hay retraso. Si fuera «include», pagarías multa en CADA devolución.",
            bad: "Pregúntate: ¿ocurre siempre o solo a veces? Lo que ocurre solo bajo condición EXTIENDE al caso base («extend»); «include» es para pasos que se ejecutan siempre.",
          },
          extra: {
            type: "match",
            prompt: "Empareja cada elemento de la notación con su significado.",
            payload: {
              left: ["( Elipse )", "«actor»", "«include»", "«extend»"],
              right: [
                "Comportamiento opcional que se añade solo bajo condición",
                "Un objetivo del sistema con valor para quien lo usa",
                "Un rol externo que interactúa con el sistema",
                "Paso común factorizado que se ejecuta siempre",
              ],
            },
            answer: { pairs: [[0, 1], [1, 2], [2, 3], [3, 0]] },
            ok: "La elipse es el objetivo, el actor es el rol externo, «include» factoriza lo que siempre pasa y «extend» añade lo condicional.",
            bad: "Repasa: elipse = objetivo con valor; «actor» = rol externo; «include» = siempre; «extend» = solo bajo condición.",
          },
        },
        {
          id: "um3",
          title: "Diagrama de actividades",
          mins: 15,
          content: [
            { type: "p", html: "El diagrama de <code>actividades</code> modela el FLUJO de un proceso: una secuencia de pasos, no la vida de un objeto. Empieza en un <code>nodo inicial</code> (●) y recorre <code>actividades</code> — acciones o pasos del proceso — hasta llegar a un <code>nodo final</code> (◉). A diferencia de un diagrama de secuencia, aquí no importa QUIÉN envía un mensaje a quién: importa el ORDEN en que ocurren las cosas." },
            { type: "p", html: "Cuando el flujo se bifurca según una condición, aparece un <code>nodo de decisión</code> (◇, un rombo) con una flecha de salida por cada camino posible, y cada flecha lleva una <code>guarda</code> entre corchetes — <code>[condición]</code> — que dice bajo qué circunstancia se toma ESE camino. Las guardas de un mismo rombo deben ser mutuamente excluyentes: una situación real solo puede cumplir una. Cuando los caminos vuelven a unirse en uno solo, ese punto se llama <code>fusión</code> (otro rombo, esta vez sin guardas)." },
            { type: "p", html: "La decisión NO es lo mismo que la <code>bifurcación</code> (fork): un rombo elige UNA rama entre varias, pero una barra de bifurcación abre VARIAS ramas que corren en <code>paralelo</code> — ambas ocurren, no una u otra. Una barra de <code>sincronización</code> (join) espera a que todas las ramas paralelas terminen antes de seguir. Cuando el proceso involucra a varios responsables, las <code>calles</code> (swimlanes) dividen el diagrama en carriles — uno por actor o sistema — para dejar claro quién ejecuta cada actividad." },
            { type: "code", lines: [
              `<span style="${C}">── Actividades · checkout del carrito ──────────</span>`,
              `                ●`,
              `                ▼`,
              `       ┌─────────────────┐`,
              `       │ Verificar stock │`,
              `       └────────┬────────┘`,
              `                ◇`,
              `    <span style="${N}">[hay stock]</span>   <span style="${N}">[sin stock]</span>`,
              `    ▼             ▼`,
              `    Cobrar pago   Avisar sin stock`,
              `    ▼             ▼`,
              `    ◉             ◉`,
            ]},
            { type: "p", html: "En el checkout del carrito, el flujo verifica el stock y decide: si hay stock, cobra el pago; si no hay stock, avisa que falta. Fíjate que las dos guardas son excluyentes — un pedido real cae en una sola — y que ambos caminos terminan en su propio nodo final: dos desenlaces distintos del mismo proceso." },
            { type: "note", text: "Regla mental: la decisión pregunta «¿cuál de estos caminos?» (uno se cumple); la bifurcación dice «todos estos a la vez» (paralelo)." },
          ],
          quiz: {
            question: "En el nodo de decisión ◇ del checkout, ¿qué son las etiquetas [hay stock] y [sin stock]?",
            options: [
              "Guardas: condiciones mutuamente excluyentes que determinan qué rama se sigue",
              "Eventos que disparan la transición desde afuera del sistema",
              "Acciones que el sistema ejecuta al entrar en cada rama",
              "Estados en los que puede quedar el objeto Pedido",
            ],
            correct: 0,
            ok: "Son guardas: condiciones entre corchetes sobre la flecha de salida de un rombo de decisión. Son mutuamente excluyentes — un pedido real cumple una sola — y determinan cuál de los caminos posibles se recorre.",
            bad: "No son eventos (algo que dispara una transición desde afuera), ni acciones (lo que se ejecuta al entrar a una rama), ni estados (dónde queda un objeto en el tiempo) — son la condición que el rombo de decisión evalúa para elegir una rama.",
          },
          extra: {
            type: "order",
            prompt: "Ordena el flujo del checkout, del primer paso al último.",
            payload: {
              lines: [
                { id: "pag", html: "Pagar la compra" },
                { id: "con", html: "Recibir confirmación del pedido" },
                { id: "agr", html: "Agregar producto al carrito" },
                { id: "dir", html: "Confirmar dirección de envío" },
              ],
            },
            answer: { order: ["agr", "dir", "pag", "con"] },
            ok: "El checkout sigue un flujo fijo: primero agregas el producto al carrito, luego confirmas dónde debe llegar, después pagas, y al final recibes la confirmación de que el pedido quedó registrado.",
            bad: "No puedes pagar antes de saber a dónde envía el sistema, ni confirmar un pedido antes de haberlo pagado: el orden correcto es agregar al carrito → confirmar dirección → pagar → recibir confirmación.",
          },
        },
        {
          id: "um4",
          title: "Diagrama de estados",
          mins: 16,
          content: [
            { type: "p", html: "El diagrama de <code>estados</code> (o máquina de estados) no describe un proceso completo como el de actividades: describe la VIDA de UN SOLO objeto, desde que nace hasta que termina. Cada <code>estado</code> — dibujado como un rectángulo de esquinas redondeadas — representa una condición estable en la que el objeto puede quedarse un rato: un <code>Préstamo</code>, por ejemplo, puede estar <code>Activo</code>, <code>Vencido</code> o <code>Devuelto</code>. El diagrama arranca en un <code>estado inicial</code> (●) y puede terminar en un <code>estado final</code> (◉)." },
            { type: "p", html: "Lo que mueve al objeto de un estado a otro es una <code>transición</code>, y su notación completa tiene tres partes: <code>evento [guarda] / acción</code>. El <code>evento</code> es lo que dispara el cambio (algo que ocurre afuera del objeto, como que alguien pida devolver un libro); la <code>guarda</code> entre corchetes es una condición opcional que debe cumplirse para que la transición ocurra; la <code>acción</code> después de la barra es lo que el sistema EJECUTA al hacer la transición. Solo el evento es obligatorio — una transición puede no tener guarda ni acción." },
            { type: "code", lines: [
              `<span style="${C}">── Estados · un Préstamo ─────────────────────</span>`,
              `   ╭────────╮           ╭─────────╮`,
              `●─▶│ Activo │──vencer──▶│ Vencido │`,
              `   ╰────────╯           ╰────┬────╯`,
              `                             │`,
              `          <span style="${N}">devolver [con retraso] / calcular multa</span>`,
              `                             ▼`,
              `                       ╭──────────╮`,
              `                       │ Devuelto │`,
              `                       ╰─────┬────╯`,
              `                             ◉`,
            ]},
            { type: "p", html: "Lee la transición resaltada del diagrama: <code>devolver [con retraso] / calcular multa</code>. El evento <code>devolver</code> es lo que dispara el cambio — alguien pide devolver el préstamo. La guarda <code>[con retraso]</code> es la condición que debe cumplirse: el préstamo debe estar vencido para que ESTA transición se tome. Y <code>calcular multa</code> es la acción que el sistema ejecuta al cruzarla, justo antes de asentarse en Devuelto." },
            { type: "note", text: "Un diagrama de estados es la biografía de UN objeto; si necesitas seguir a VARIOS objetos coordinándose, ese es el trabajo del diagrama de secuencia, no el de estados." },
          ],
          quiz: {
            question: "Lee la transición devolver [con retraso] / calcular multa del diagrama. ¿Qué significa?",
            options: [
              "El sistema calcula la multa como condición para permitir el evento devolver",
              "\"Con retraso\" es la acción que el sistema ejecuta al recibir el evento devolver",
              "Al ocurrir el evento devolver, SI hay retraso, el objeto transita y el sistema ejecuta la acción calcular multa",
              "\"Calcular multa\" es el nombre del estado al que llega el préstamo tras devolverse",
            ],
            correct: 2,
            ok: "La lectura correcta respeta el orden evento [guarda] / acción: devolver es lo que dispara la transición, [con retraso] es la condición que debe cumplirse, y calcular multa es lo que el sistema ejecuta al cruzarla — no un estado ni una condición previa al evento.",
            bad: "No inviertas el orden: la guarda no es la acción (va antes de la barra, no después), la acción no es una condición para el evento (ocurre DESPUÉS de que el evento ya disparó la transición), y \"calcular multa\" no es un estado — es lo que el sistema hace, no dónde queda.",
          },
          extra: {
            type: "match",
            prompt: "Empareja cada pieza de una transición con su rol.",
            payload: {
              left: ["Estado", "Evento", "Guarda", "Acción"],
              right: [
                "Lo que el sistema ejecuta al cruzar la transición, como calcular multa",
                "La condición entre corchetes que debe cumplirse para que la transición ocurra",
                "Una condición estable en la que el objeto permanece un tiempo, como Activo o Vencido",
                "Lo que dispara la transición, como recibir la orden de devolver",
              ],
            },
            answer: { pairs: [[0, 2], [1, 3], [2, 1], [3, 0]] },
            ok: "Estado es dónde el objeto permanece (Activo, Vencido); evento es lo que dispara el cambio; guarda es la condición entre corchetes que decide si la transición ocurre; acción es lo que el sistema ejecuta al cruzarla.",
            bad: "No mezcles evento con guarda: el evento siempre dispara la transición, la guarda solo la permite o la bloquea; y la acción no es un estado — ocurre DURANTE el cruce, no es un lugar donde el objeto se queda.",
          },
        },
      ],
    },
    {
      id: "uml-u2",
      name: "Unidad 2 · Estructura, interacción y arquitectura",
      lessons: [
        {
          id: "um5",
          title: "Clases y objetos",
          mins: 18,
          content: [
            { type: "p", html: "El diagrama de <code>clases</code> es el más usado de UML: retrata la estructura estática de un sistema orientado a objetos. Cada <code>clase</code> se dibuja como una caja de tres compartimentos apilados: el <code>nombre</code> arriba, los <code>atributos</code> en medio y las <code>operaciones</code> (métodos) abajo. Cada miembro lleva un símbolo de <code>visibilidad</code>: <code>+</code> (público, cualquiera lo usa), <code>-</code> (privado, solo la propia clase) y <code>#</code> (protegido, la clase y sus herederas)." },
            { type: "p", html: "Las clases no viven solas: se relacionan. La <code>asociación</code> es la relación más simple — una línea que dice \"estas dos clases se conocen\", sin que una posea a la otra. Cuando la relación es de todo-parte, dos matices confunden a todo el mundo: la <code>agregación</code> (◇, rombo hueco) es una posesión débil — la parte sobrevive sin el todo, como <code>Catálogo ◇── Libro</code> (un libro sigue existiendo aunque lo saques del catálogo) — y la <code>composición</code> (◆, rombo relleno) es una posesión fuerte — la parte muere si el todo desaparece. La <code>herencia</code> (△, triángulo hueco) conecta una clase general con una especializada, y el triángulo SIEMPRE apunta hacia el padre: <code>Socio △── SocioPremium</code> dice que SocioPremium ES UN Socio. Toda relación además puede llevar <code>multiplicidades</code> en sus extremos — <code>1</code>, <code>*</code>, <code>0..1</code>, <code>1..*</code> — que dicen cuántas instancias participan de cada lado." },
            { type: "code", lines: [
              `<span style="${C}">── Clases · relación y multiplicidad ──────</span>`,
              `┌────────┐ 1         1..* ┌───────────────┐`,
              `│ Pedido │<span style="${N}">◆</span>───────────────│ LíneaDePedido │`,
              `└────────┘                └───────────────┘`,
              ``,
              `┌────────┐ 1            * ┌──────────┐`,
              `│ Socio  │────────────────│ Préstamo │`,
              `└────────┘                └──────────┘`,
            ]},
            { type: "p", html: "Lee el diagrama: <code>Pedido ◆── LíneaDePedido</code> con multiplicidad <code>1..*</code> dice que un pedido se compone de una o más líneas, y si el pedido se borra, sus líneas se borran con él — nadie más las referencia. En cambio, <code>Socio ── Préstamo</code> es asociación simple: un socio puede tener <code>*</code> préstamos, pero si el socio se diera de baja, los préstamos no desaparecerían con él." },
            { type: "p", html: "Todo esto describe la clase — el molde. Un <code>diagrama de objetos</code> es distinto: una instantánea de instancias concretas EN UN MOMENTO dado, con valores reales en vez de tipos. Donde la clase dice <code>Socio</code> con un atributo <code>nombre: String</code>, el objeto dice <code>ana: Socio</code> con <code>nombre = \"Ana Ruiz\"</code> — ya no es un tipo, es un caso particular." },
            { type: "note", text: "El rombo relleno (◆) es una adopción irreversible: la parte no sobrevive sin el todo. El rombo hueco (◇) es más una tutela — la parte puede seguir su vida por su cuenta." },
          ],
          quiz: {
            question: "Si se elimina el pedido, sus líneas de pedido desaparecen con él. ¿Qué relación modela esto?",
            options: [
              "Agregación: el todo y la parte pueden vivir por separado",
              "Composición: la parte muere si el todo desaparece",
              "Asociación simple: una relación estructural sin dependencia de vida",
              "Herencia: una relación \"es un\" entre una clase general y una especializada",
            ],
            correct: 1,
            ok: "Es composición (◆): la parte no tiene vida propia fuera del todo, así que cuando el pedido se borra, sus líneas de pedido se borran con él — nadie más las referencia.",
            bad: "La agregación deja que la parte sobreviva sola; la asociación simple no implica ninguna dependencia de vida; y la herencia describe \"es un\", no \"se compone de\" — ninguna de las tres explica que las líneas mueran junto al pedido.",
          },
          extra: {
            type: "match",
            prompt: "Empareja cada símbolo con su significado.",
            payload: {
              left: ["◇", "◆", "△", "1..*"],
              right: [
                "Apunta desde la clase hija hacia su clase padre",
                "Indica cuántas instancias participan en cada extremo de una relación",
                "Todo-parte débil: la parte puede sobrevivir sin el todo",
                "Todo-parte fuerte: la parte muere si el todo desaparece",
              ],
            },
            answer: { pairs: [[0, 2], [1, 3], [2, 0], [3, 1]] },
            ok: "◇ es agregación (la parte sobrevive sola), ◆ es composición (la parte muere con el todo), △ apunta siempre hacia el padre en una herencia, y 1..* fija cuántas instancias participan en un extremo de la relación.",
            bad: "No confundas los rombos: el hueco (◇) es la posesión débil, el relleno (◆) es la fuerte. El triángulo (△) nunca apunta al hijo. Y una multiplicidad como 1..* no describe una relación, describe un extremo de ella.",
          },
        },
        {
          id: "um6",
          title: "Diagrama de secuencia",
          mins: 17,
          content: [
            { type: "p", html: "El diagrama de <code>secuencia</code> muestra cómo interactúan varios objetos ORDENADOS EN EL TIEMPO — a diferencia del diagrama de estados, que sigue a un solo objeto, aquí el protagonista es la conversación entre varios. Cada participante dibuja una <code>línea de vida</code> (lifeline): un encabezado <code>objeto: Clase</code> con una línea vertical que baja marcando el paso del tiempo. Cuando un objeto está activamente procesando algo, esa porción de su línea de vida se engrosa en una <code>barra de activación</code>." },
            { type: "p", html: "Los mensajes entre líneas de vida no son todos iguales. Un mensaje <code>síncrono</code> (flecha con punta llena) bloquea al emisor: lo manda y ESPERA a que vuelva una respuesta antes de seguir — como llamar por teléfono. La <code>respuesta</code> (flecha discontinua) es justamente esa vuelta. Un mensaje <code>asíncrono</code> (flecha con punta abierta) es distinto: el emisor lo dispara y sigue de inmediato, sin esperar nada — como enviar un mensaje de texto." },
            { type: "code", lines: [
              `<span style="${C}">── Secuencia · pedir un préstamo ────────────</span>`,
              ` Socio    :SistemaPréstamos       :Catálogo`,
              `   │              │                   │`,
              `<span style="${N}">   │──solicitar───▶                   │</span>`,
              `   │              ┃─────verificar─────▶`,
              `   │              ┃                   ┃`,
              `   │              ◀╌╌╌╌disponible╌╌╌╌╌┃`,
              `   ◀╌╌confirmar╌╌╌┃`,
            ]},
            { type: "p", html: "Lee la secuencia: <code>Socio</code> solicita el préstamo — flecha síncrona, así que Socio se queda esperando. <code>:SistemaPréstamos</code> se activa, y a su vez le pregunta a <code>:Catálogo</code> si hay ejemplares — otra llamada síncrona, otra espera. <code>:Catálogo</code> responde con una flecha discontinua (\"disponible\"), y solo entonces <code>:SistemaPréstamos</code> puede confirmarle a Socio, también con una respuesta discontinua." },
            { type: "note", text: "Un mensaje síncrono es una llamada telefónica: cuelgas cuando termina la conversación. Uno asíncrono es un mensaje de texto: lo envías y sigues con tu día sin esperar frente al teléfono." },
          ],
          quiz: {
            question: "En un mensaje síncrono dentro de un diagrama de secuencia, ¿qué hace el emisor mientras dura la llamada?",
            options: [
              "Sigue ejecutando de inmediato, sin esperar ninguna respuesta",
              "Deja que el receptor decida si la conversación continúa o no",
              "Se bloquea y espera la respuesta antes de continuar",
              "Cancela el mensaje si no recibe una respuesta inmediata",
            ],
            correct: 2,
            ok: "El mensaje síncrono bloquea al emisor: lo manda y se queda esperando a que vuelva una respuesta antes de seguir con lo suyo — igual que sostener el teléfono hasta que cuelgan.",
            bad: "\"Seguir sin esperar\" describe lo asíncrono, no lo síncrono. El receptor no decide si el emisor espera — esa espera es una propiedad del tipo de mensaje, no una elección del receptor. Y un mensaje síncrono no se cancela por tardar: se queda esperando.",
          },
          extra: {
            type: "order",
            prompt: "Ordena los pasos para pedir un préstamo, del primero al último.",
            payload: {
              lines: [
                { id: "reg", html: "Registrar el préstamo en el sistema" },
                { id: "con", html: "Confirmar el préstamo al socio" },
                { id: "sol", html: "Solicitar el préstamo" },
                { id: "ver", html: "Verificar la disponibilidad del ejemplar" },
              ],
            },
            answer: { order: ["sol", "ver", "reg", "con"] },
            ok: "Primero el socio solicita el préstamo, luego el sistema verifica que haya ejemplar disponible, después lo registra, y solo al final confirma al socio que quedó hecho.",
            bad: "No puedes registrar un préstamo antes de verificar que hay ejemplar disponible, ni confirmar algo que todavía no registraste: el orden correcto es solicitar → verificar → registrar → confirmar.",
          },
        },
        {
          id: "um7",
          title: "El diagrama de contexto",
          mins: 14,
          content: [
            { type: "p", html: "El diagrama de <code>contexto</code> nace de una tradición distinta a la del resto de UML: viene del análisis estructurado (el <code>DFD de nivel 0</code>, si alguna vez viste ese nombre) y hoy convive con UML aunque no forma parte de los nueve diagramas que cubre este curso — muchos equipos lo reemplazan con un diagrama de casos de uso a nivel de sistema. Vale la pena conocerlo igual: no hay notación más simple para responder una sola pregunta — ¿dónde termina MI sistema y empieza el mundo?" },
            { type: "p", html: "La idea central es la <code>frontera</code>: el sistema entero se dibuja como UNA sola caja, sin abrir su interior — ni clases, ni módulos, ni cómo resuelve nada por dentro. Alrededor de esa caja aparecen los <code>actores</code> y <code>sistemas externos</code> con los que se comunica, y flechas etiquetadas que describen cada <code>flujo</code> de información que cruza la frontera. Puertas adentro, el sistema puede tener piezas como un <code>módulo de reservas</code> o un <code>catálogo</code> de títulos — pero nada de eso aparece en el diagrama: ahí conviven ocultas dentro de una sola caja opaca." },
            { type: "code", lines: [
              `<span style="${C}">── Contexto · SistemaBiblioteca ─────────────</span>`,
              `                           Socio`,
              `                             │ pide y devuelve libros`,
              `                             ▼`,
              `                   ┌───────────────────┐`,
              `Bibliotecario ──▶  <span style="${N}">│ SistemaBiblioteca │</span> ──▶ PasarelaDePagos`,
              `   da de alta      └───────────────────┘     cobra multas`,
            ]},
            { type: "p", html: "Lee el diagrama: <code>SistemaBiblioteca</code> es la única caja — no se ve qué hay dentro. Alrededor, tres externos cruzan su frontera: <code>Socio</code> pide y devuelve libros, <code>Bibliotecario</code> da de alta el catálogo, y <code>PasarelaDePagos</code> cobra las multas. Cada flecha lleva su etiqueta: eso es TODO lo que el diagrama de contexto promete mostrar." },
            { type: "note", text: "Piensa en el plano de evacuación de un edificio: marca las puertas de salida y quién entra o sale por cada una, pero no te muestra los cables detrás de las paredes — eso es un plano distinto." },
          ],
          quiz: {
            question: "¿Qué NO muestra un diagrama de contexto?",
            options: [
              "La estructura interna del sistema: sus módulos, clases o cómo resuelve cada caso",
              "Los actores externos que interactúan con el sistema",
              "Los sistemas externos con los que el sistema se comunica",
              "Los flujos de información etiquetados entre el sistema y su entorno",
            ],
            correct: 0,
            ok: "El diagrama de contexto dibuja el sistema como una caja opaca: muestra la frontera, los externos y los flujos etiquetados, pero deliberadamente NO abre el interior — para eso existen otros diagramas, como el de componentes o el de clases.",
            bad: "Actores externos, sistemas externos y flujos etiquetados son justo lo que SÍ muestra un diagrama de contexto — es la estructura interna del sistema, puertas adentro, lo único que queda fuera de este diagrama.",
          },
          extra: {
            type: "match",
            prompt: "Empareja cada elemento con su descripción.",
            payload: {
              left: ["Socio", "Pasarela de pagos", "Módulo de reservas", "Catálogo"],
              right: [
                "Responsabilidad interna: gestiona los apartados",
                "Almacén interno de los títulos y ejemplares",
                "Persona externa que solicita préstamos",
                "Sistema externo que procesa los cobros",
              ],
            },
            answer: { pairs: [[0, 2], [1, 3], [2, 0], [3, 1]] },
            ok: "Socio y la pasarela de pagos son externos y por eso aparecen en el diagrama de contexto; el módulo de reservas y el catálogo son responsabilidades internas del sistema, y por eso quedan ocultas dentro de la caja.",
            bad: "No los mezcles por rol dentro del negocio: lo que importa aquí es si están DENTRO o FUERA de la frontera del sistema. Socio y la pasarela cruzan la frontera; el módulo de reservas y el catálogo viven puertas adentro.",
          },
        },
        {
          id: "um8",
          title: "Diagramas de tiempo",
          mins: 15,
          content: [
            { type: "p", html: "El diagrama de <code>tiempo</code> (timing) SÍ es uno de los nueve diagramas de este curso — y el más ignorado en la práctica. A diferencia del diagrama de estados, donde el tiempo no tiene escala (una transición \"tarda\" lo que tarde), aquí el <code>eje horizontal</code> ES el tiempo, con una escala real. El <code>eje vertical</code> muestra los <code>estados</code> por los que pasa UNA línea de vida, y cada cambio de estado se dibuja como un escalón — sube o baja en el momento exacto en que ocurre." },
            { type: "p", html: "Encima del escalón pueden aparecer <code>restricciones</code> entre llaves, como <code>{&lt; 2 s}</code>: una cota de tiempo que ese tramo del ciclo de vida debe respetar. Este diagrama brilla cuando el tiempo real — no solo el orden de los eventos — importa: sensores que deben reaccionar en milisegundos, timeouts de red, protocolos con plazos duros. Si tu problema es \"¿en qué orden pasan las cosas?\", usa un diagrama de estados; si es \"¿CUÁNTO tardan en pasar?\", usa uno de tiempo." },
            { type: "code", lines: [
              `<span style="${C}">── Timing · un Préstamo ──────────────────────</span>`,
              `Activo    ────────────┐`,
              `                      │`,
              `Vencido               └───────┐ <span style="${N}">{&lt; 2 días}</span>`,
              `                              │`,
              `Devuelto                      └──────────`,
              ``,
              `          día 0     día 14     día 15`,
            ]},
            { type: "p", html: "Lee el diagrama: un <code>Préstamo</code> nace <code>Activo</code> el día 0. El escalón baja a <code>Vencido</code> exactamente en el día 14 — ahí cambió de estado, no antes ni después. Se mantiene Vencido apenas un día, con la restricción <code>{&lt; 2 días}</code> resaltada: el sistema garantiza que ese tramo dura menos de dos días. El día 15 baja a <code>Devuelto</code>, su estado final." },
            { type: "note", text: "En un diagrama de estados preguntas \"¿QUÉ puede pasar después?\". En uno de tiempo preguntas \"¿A QUÉ HORA pasó?\" — la misma vida, medida con una regla distinta." },
          ],
          quiz: {
            question: "En un diagrama de tiempo (timing), ¿qué representa el eje horizontal?",
            options: [
              "Los estados posibles de la línea de vida",
              "Los actores involucrados en el escenario",
              "La prioridad de cada evento registrado",
              "El tiempo, que avanza de izquierda a derecha",
            ],
            correct: 3,
            ok: "El eje horizontal ES el tiempo, con una escala real — por eso este diagrama sirve para responder cuánto tardó algo, no solo en qué orden ocurrió.",
            bad: "Los estados van en el eje VERTICAL, no en el horizontal. Los actores no se representan como un eje en este diagrama. Y la prioridad de un evento no tiene ningún eje aquí — lo único que mide el eje horizontal es el paso del tiempo.",
          },
          extra: {
            type: "choice",
            prompt: "Mirando el diagrama de la lección, ¿cuándo pasó el préstamo a Vencido?",
            payload: {
              options: [
                "En el día 14, cuando el escalón baja de Activo a Vencido",
                "En el día 0, al iniciar el préstamo",
                "En el día 15, cuando pasa a Devuelto",
                "No se puede leer del diagrama; falta un reloj explícito",
              ],
            },
            answer: { index: 0 },
            ok: "El escalón que baja de Activo a Vencido está dibujado exactamente sobre la marca del día 14 — ese es el instante en que ocurrió el cambio de estado, no antes ni después.",
            bad: "El día 0 es cuando el préstamo nace Activo, todavía no vencido. El día 15 es cuando pasa a Devuelto, un escalón después. Y el diagrama sí tiene un eje de tiempo explícito con marcas: por eso se puede leer con precisión.",
          },
        },
        {
          id: "um9",
          title: "Diagramas de componentes",
          mins: 15,
          content: [
            { type: "p", html: "El diagrama de <code>componentes</code> describe el software como piezas REEMPLAZABLES — no clases sueltas, sino módulos con una frontera clara: puedes sacar una pieza y meter otra distinta, mientras respete el mismo contrato. Cada pieza se marca con el estereotipo <code>«component»</code> sobre su nombre." },
            { type: "p", html: "El contrato se declara con dos símbolos. Una <code>interfaz provista</code> se dibuja como un <code>lollipop</code> — una línea que termina en círculo, <code>──○</code>: el componente dice \"yo OFREZCO esto\". Una <code>interfaz requerida</code> se dibuja como un <code>socket</code> — una muesca cóncava, <code>──(</code>: el componente dice \"yo NECESITO esto para funcionar\". Cuando el lollipop de uno encaja en el socket de otro, los dos componentes quedan acoplados SOLO por ese contrato — ninguno conoce los detalles internos del otro. Un componente también puede tener una <code>dependencia</code> (flecha discontinua) hacia otro: un uso más suelto, sin comprometerse a una interfaz formal." },
            { type: "code", lines: [
              `<span style="${C}">── Componentes · contrato de pago ───────────</span>`,
              `┌───────────┐      ┌───────────────┐`,
              `│«component»│      │  «component»  │`,
              `│ TiendaWeb <span style="${N}">├──(○──┤</span> PasarelaPagos │`,
              `└───────────┘      └───────────────┘`,
              `             IPagos`,
            ]},
            { type: "p", html: "Lee el diagrama: <code>TiendaWeb</code> tiene el socket — REQUIERE <code>IPagos</code> para poder cobrar. <code>PasarelaPagos</code> tiene el lollipop — PROVEE esa misma interfaz. El acoplamiento ocurre exactamente donde el lollipop encaja en el socket: si mañana cambias PasarelaPagos por otro proveedor que también provea IPagos, TiendaWeb ni se entera." },
            { type: "note", text: "Piensa en un enchufe: el socket de la pared es lo que NECESITAS (tu lámpara no funciona sin electricidad), y la toma que ofrece la compañía eléctrica es lo que PROVEE. Cualquier lámpara con el enchufe correcto encaja, sin importar la marca." },
          ],
          quiz: {
            question: "Un componente dibuja un lollipop ─○ etiquetado IPagos. ¿Qué declara?",
            options: [
              "Que el componente PROVEE (implementa) la interfaz IPagos",
              "Que el componente REQUIERE la interfaz IPagos para funcionar",
              "Que el componente HEREDA el comportamiento de IPagos",
              "Que el componente PROHÍBE el uso de IPagos por otros componentes",
            ],
            correct: 0,
            ok: "El lollipop (─○) es la notación de interfaz PROVISTA: el componente ofrece esa funcionalidad a quien quiera conectarse. El socket, no el lollipop, es el que declara una necesidad.",
            bad: "Requerir se dibuja con un socket, no con un lollipop. Un componente no \"hereda\" de una interfaz — eso es una relación de clases, no de componentes. Y nada en la notación de componentes prohíbe nada: el lollipop siempre ofrece, nunca bloquea.",
          },
          extra: {
            type: "match",
            prompt: "Empareja cada elemento con lo que significa.",
            payload: {
              left: ["Interfaz provista (lollipop)", "Interfaz requerida (socket)", "«component»", "Dependencia (flecha discontinua)"],
              right: [
                "Marca una pieza reemplazable con una interfaz bien definida",
                "Indica que un componente usa a otro sin acoplarse a su interfaz formal",
                "Declara qué servicio necesita el componente para funcionar",
                "Declara qué servicio ofrece el componente a quien se conecte",
              ],
            },
            answer: { pairs: [[0, 3], [1, 2], [2, 0], [3, 1]] },
            ok: "El lollipop ofrece un servicio, el socket declara una necesidad, «component» marca la pieza reemplazable, y una dependencia discontinua es un uso más suelto, sin comprometerse a un contrato formal.",
            bad: "No inviertas provista y requerida: el lollipop OFRECE, el socket NECESITA. Y una dependencia discontinua no es lo mismo que un contrato de interfaz — es un acoplamiento más débil, sin lollipop ni socket de por medio.",
          },
        },
      ],
    },
  ],
};
