const K = 'color: var(--accent-violet)';
const S = 'color: var(--accent-cyan)';
const N = 'color: var(--accent-amber)';
const C = 'color: var(--text-tertiary)';

export default {
  id: "uml",
  subject: "Ingeniería de software",
  tone: "violet",
  title: "Modelado con UML",
  description: "Dibuja lo que el software es y lo que hace: los nueve diagramas que convierten requisitos en diseño.",
  order: 8,
  prereq: "reqsw",
  units: [
    {
      id: "uml-u1",
      name: "Unidad 1 · El lenguaje y el comportamiento",
      lessons: [
        {
          id: "um1",
          title: "UML: un lenguaje, no un método",
          mins: 14,
          content: [
            { type: "p", html: "<code>UML</code> (Unified Modeling Language) es un lenguaje VISUAL estándar para modelar software, mantenido por el <code>OMG</code> (Object Management Group). Ojo con la trampa: UML no es una metodología ni un proceso — no te dice EN QUÉ ORDEN trabajar ni cómo organizar tu equipo, como sí hacen Scrum o el modelo en cascada. Tampoco es un lenguaje de programación: un diagrama de clases no se ejecuta, describe la forma que después alguien traduce a código en Java, Python o el lenguaje que sea." },
            { type: "p", html: "¿Para qué sirve entonces dibujar? Para tres cosas que un párrafo de texto hace peor: <code>comunicar</code> una idea de diseño de un vistazo entre personas que no comparten el mismo vocabulario técnico, <code>razonar</code> sobre un problema ANTES de escribir una sola línea de código (un diagrama mal armado se corrige en un pizarrón; un diseño mal armado se corrige refactorizando), y <code>documentar</code> decisiones que de otro modo solo viven en la cabeza de quien las tomó." },
            { type: "p", html: "UML ofrece nueve diagramas estándar, pero todos caen en dos familias. Los de <code>estructura</code> retratan el sistema QUIETO: sus piezas y cómo se relacionan — clases, objetos, componentes. Los de <code>comportamiento</code> retratan el sistema EN MOVIMIENTO: qué hace y cómo cambia — casos de uso, actividades, estados, secuencia, tiempo. La pregunta que separa ambas familias es simple: ¿el diagrama describe una foto o una película?" },
            { type: "code", lines: [
              `<span style="${C}">── Las dos familias de UML ─────────────────────</span>`,
              `<span style="${K}">Estructura</span>      clases, objetos, componentes`,
              `<span style="${S}">Comportamiento</span>  casos de uso, actividades,`,
              `                estados, secuencia, tiempo`,
            ]},
            { type: "note", text: "Piensa en los planos de una casa: el plano de la estructura (paredes, cimientos) es la familia estructural; el plano eléctrico mostrando cuándo se enciende cada circuito es la familia de comportamiento. Ambos describen la misma casa desde ángulos distintos." },
          ],
          quiz: {
            question: "¿Qué es UML?",
            options: [
              "Una metodología que define en qué orden deben ejecutarse las fases de un proyecto",
              "Un lenguaje visual estándar (OMG) para modelar software, no una metodología ni un lenguaje de programación",
              "Un lenguaje de programación orientado a objetos, como Java o C++",
              "Una herramienta concreta de dibujo, como una aplicación específica de diagramación",
            ],
            correct: 1,
            ok: "UML es un lenguaje VISUAL con notación estandarizada por el OMG: define cómo se dibuja una clase o un caso de uso, pero no impone un proceso de trabajo ni se compila — no es una metodología ni un lenguaje de programación.",
            bad: "No confundas el lenguaje con el proceso: una metodología dicta el ORDEN de trabajo (eso es Scrum o cascada, no UML); un lenguaje de programación se ejecuta (un diagrama no); y UML es el estándar en sí, no una app concreta que lo dibuje.",
          },
          extra: {
            type: "match",
            prompt: "Empareja cada diagrama con su propósito específico.",
            payload: {
              left: ["Diagrama de clases", "Diagrama de secuencia", "Diagrama de casos de uso", "Diagrama de componentes"],
              right: [
                "Muestra las piezas del sistema y las interfaces que las conectan",
                "Muestra qué le ofrece el sistema a cada actor externo",
                "Muestra la estructura estática del sistema y las relaciones entre sus elementos",
                "Muestra los mensajes que se intercambian los objetos, ordenados en el tiempo",
              ],
            },
            answer: { pairs: [[0, 2], [1, 3], [2, 1], [3, 0]] },
            ok: "Cada diagrama mira el sistema desde un ángulo distinto: clases fija la estructura estática y sus relaciones, secuencia ordena los mensajes en el tiempo, casos de uso muestra qué le ofrece el sistema a cada actor, y componentes expone las piezas y sus interfaces.",
            bad: "No los confundas por familia: clases y componentes son estructura, pero uno describe relaciones internas y el otro piezas con interfaz; secuencia y casos de uso son comportamiento, pero uno ordena mensajes en el tiempo y el otro describe el objetivo de un actor.",
          },
        },
        {
          id: "um2",
          title: "Casos de uso",
          mins: 16,
          content: [
            { type: "p", html: "El diagrama de <code>casos de uso</code> mira el sistema desde AFUERA: qué ofrece y a quién. Un <code>actor</code> es un ROL externo que interactúa con el sistema — puede ser una persona (Socio) u otro sistema (la pasarela de pagos); nunca es una parte interna. Un <code>caso de uso</code> es un objetivo con valor observable para ese actor: prestar un libro, no \"consultar la base de datos\"." },
            { type: "p", html: "La notación: el actor fuera, los casos como óvalos dentro de la caja del sistema (la frontera), y líneas que los conectan. Dos relaciones entre casos confunden a todo el mundo: <code>«include»</code> — un paso común factorizado que se ejecuta SIEMPRE — y <code>«extend»</code> — comportamiento opcional que solo ocurre bajo condición." },
            { type: "code", lines: [
              `<span style="${C}">── Casos de uso · biblioteca ──────────────────</span>`,
              `┌─────────┐      ( Prestar libro )`,
              `│ «actor» │────▶(                 )`,
              `│  Socio  │      (_______________)`,
              `└─────────┘             │`,
              `                  <span style="${N}">«include»</span>`,
              `                         ▼`,
              `                 ( Validar socio )`,
            ]},
            { type: "p", html: "Léelo así: cada vez que un Socio presta un libro, el sistema SIEMPRE valida al socio primero — por eso es <code>«include»</code>. En cambio, \"Pagar multa\" solo ocurre si devuelve con retraso: eso sería <code>«extend»</code> sobre \"Devolver libro\"." },
            { type: "note", text: "Regla mental: «include» es el peaje obligatorio de la autopista; «extend» es la parada opcional en la estación de servicio." },
          ],
          quiz: {
            question: "En la biblioteca, \"Pagar multa\" ocurre solo si el socio devuelve con retraso. ¿Cómo se modela respecto a \"Devolver libro\"?",
            options: [
              "Con «include»: siempre forma parte de Devolver libro",
              "Como una generalización del caso Devolver libro",
              "Como una asociación simple entre dos actores",
              "Con «extend»: extiende Devolver libro solo bajo condición",
            ],
            correct: 3,
            ok: "«extend» modela lo condicional: Pagar multa solo se ejecuta si hay retraso. Si fuera «include», pagarías multa en CADA devolución.",
            bad: "Pregúntate: ¿ocurre siempre o solo a veces? Lo que ocurre solo bajo condición EXTIENDE al caso base («extend»); «include» es para pasos que se ejecutan siempre.",
          },
          extra: {
            type: "match",
            prompt: "Empareja cada elemento de la notación con su significado.",
            payload: {
              left: ["( Elipse )", "«actor»", "«include»", "«extend»"],
              right: [
                "Comportamiento opcional que se añade solo bajo condición",
                "Un objetivo del sistema con valor para quien lo usa",
                "Un rol externo que interactúa con el sistema",
                "Paso común factorizado que se ejecuta siempre",
              ],
            },
            answer: { pairs: [[0, 1], [1, 2], [2, 3], [3, 0]] },
            ok: "La elipse es el objetivo, el actor es el rol externo, «include» factoriza lo que siempre pasa y «extend» añade lo condicional.",
            bad: "Repasa: elipse = objetivo con valor; «actor» = rol externo; «include» = siempre; «extend» = solo bajo condición.",
          },
        },
        {
          id: "um3",
          title: "Diagrama de actividades",
          mins: 15,
          content: [
            { type: "p", html: "El diagrama de <code>actividades</code> modela el FLUJO de un proceso: una secuencia de pasos, no la vida de un objeto. Empieza en un <code>nodo inicial</code> (●) y recorre <code>actividades</code> — acciones o pasos del proceso — hasta llegar a un <code>nodo final</code> (◉). A diferencia de un diagrama de secuencia, aquí no importa QUIÉN envía un mensaje a quién: importa el ORDEN en que ocurren las cosas." },
            { type: "p", html: "Cuando el flujo se bifurca según una condición, aparece un <code>nodo de decisión</code> (◇, un rombo) con una flecha de salida por cada camino posible, y cada flecha lleva una <code>guarda</code> entre corchetes — <code>[condición]</code> — que dice bajo qué circunstancia se toma ESE camino. Las guardas de un mismo rombo deben ser mutuamente excluyentes: una situación real solo puede cumplir una. Cuando los caminos vuelven a unirse en uno solo, ese punto se llama <code>fusión</code> (otro rombo, esta vez sin guardas)." },
            { type: "p", html: "La decisión NO es lo mismo que la <code>bifurcación</code> (fork): un rombo elige UNA rama entre varias, pero una barra de bifurcación abre VARIAS ramas que corren en <code>paralelo</code> — ambas ocurren, no una u otra. Una barra de <code>sincronización</code> (join) espera a que todas las ramas paralelas terminen antes de seguir. Cuando el proceso involucra a varios responsables, las <code>calles</code> (swimlanes) dividen el diagrama en carriles — uno por actor o sistema — para dejar claro quién ejecuta cada actividad." },
            { type: "code", lines: [
              `<span style="${C}">── Actividades · checkout del carrito ──────────</span>`,
              `                ●`,
              `                ▼`,
              `       ┌─────────────────┐`,
              `       │ Verificar stock │`,
              `       └────────┬────────┘`,
              `                ◇`,
              `    <span style="${N}">[hay stock]</span>   <span style="${N}">[sin stock]</span>`,
              `    ▼             ▼`,
              `    Cobrar pago   Avisar sin stock`,
              `    ▼             ▼`,
              `    ◉             ◉`,
            ]},
            { type: "p", html: "En el checkout del carrito, el flujo verifica el stock y decide: si hay stock, cobra el pago; si no hay stock, avisa que falta. Fíjate que las dos guardas son excluyentes — un pedido real cae en una sola — y que ambos caminos terminan en su propio nodo final: dos desenlaces distintos del mismo proceso." },
            { type: "note", text: "Regla mental: la decisión pregunta «¿cuál de estos caminos?» (uno se cumple); la bifurcación dice «todos estos a la vez» (paralelo)." },
          ],
          quiz: {
            question: "En el nodo de decisión ◇ del checkout, ¿qué son las etiquetas [hay stock] y [sin stock]?",
            options: [
              "Guardas: condiciones mutuamente excluyentes que determinan qué rama se sigue",
              "Eventos que disparan la transición desde afuera del sistema",
              "Acciones que el sistema ejecuta al entrar en cada rama",
              "Estados en los que puede quedar el objeto Pedido",
            ],
            correct: 0,
            ok: "Son guardas: condiciones entre corchetes sobre la flecha de salida de un rombo de decisión. Son mutuamente excluyentes — un pedido real cumple una sola — y determinan cuál de los caminos posibles se recorre.",
            bad: "No son eventos (algo que dispara una transición desde afuera), ni acciones (lo que se ejecuta al entrar a una rama), ni estados (dónde queda un objeto en el tiempo) — son la condición que el rombo de decisión evalúa para elegir una rama.",
          },
          extra: {
            type: "order",
            prompt: "Ordena el flujo del checkout, del primer paso al último.",
            payload: {
              lines: [
                { id: "pag", html: "Pagar la compra" },
                { id: "con", html: "Recibir confirmación del pedido" },
                { id: "agr", html: "Agregar producto al carrito" },
                { id: "dir", html: "Confirmar dirección de envío" },
              ],
            },
            answer: { order: ["agr", "dir", "pag", "con"] },
            ok: "El checkout sigue un flujo fijo: primero agregas el producto al carrito, luego confirmas dónde debe llegar, después pagas, y al final recibes la confirmación de que el pedido quedó registrado.",
            bad: "No puedes pagar antes de saber a dónde envía el sistema, ni confirmar un pedido antes de haberlo pagado: el orden correcto es agregar al carrito → confirmar dirección → pagar → recibir confirmación.",
          },
        },
        {
          id: "um4",
          title: "Diagrama de estados",
          mins: 16,
          content: [
            { type: "p", html: "El diagrama de <code>estados</code> (o máquina de estados) no describe un proceso completo como el de actividades: describe la VIDA de UN SOLO objeto, desde que nace hasta que termina. Cada <code>estado</code> — dibujado como un rectángulo — representa una condición estable en la que el objeto puede quedarse un rato: un <code>Préstamo</code>, por ejemplo, puede estar <code>Activo</code>, <code>Vencido</code> o <code>Devuelto</code>. El diagrama arranca en un <code>estado inicial</code> (●) y puede terminar en un <code>estado final</code> (◉)." },
            { type: "p", html: "Lo que mueve al objeto de un estado a otro es una <code>transición</code>, y su notación completa tiene tres partes: <code>evento [guarda] / acción</code>. El <code>evento</code> es lo que dispara el cambio (algo que ocurre afuera del objeto, como que alguien pida devolver un libro); la <code>guarda</code> entre corchetes es una condición opcional que debe cumplirse para que la transición ocurra; la <code>acción</code> después de la barra es lo que el sistema EJECUTA al hacer la transición. Solo el evento es obligatorio — una transición puede no tener guarda ni acción." },
            { type: "code", lines: [
              `<span style="${C}">── Estados · un Préstamo ─────────────────────</span>`,
              `   ┌────────┐           ┌─────────┐`,
              `●─▶│ Activo │──vencer──▶│ Vencido │`,
              `   └────────┘           └─────────┘`,
              `                             │`,
              `          <span style="${N}">devolver [con retraso] / calcular multa</span>`,
              `                             ▼`,
              `                       ┌──────────┐`,
              `                       │ Devuelto │`,
              `                       └─────┬────┘`,
              `                             ◉`,
            ]},
            { type: "p", html: "Lee la transición resaltada del diagrama: <code>devolver [con retraso] / calcular multa</code>. El evento <code>devolver</code> es lo que dispara el cambio — alguien pide devolver el préstamo. La guarda <code>[con retraso]</code> es la condición que debe cumplirse: el préstamo debe estar vencido para que ESTA transición se tome. Y <code>calcular multa</code> es la acción que el sistema ejecuta al cruzarla, justo antes de asentarse en Devuelto." },
            { type: "note", text: "Un diagrama de estados es la biografía de UN objeto; si necesitas seguir a VARIOS objetos coordinándose, ese es el trabajo del diagrama de secuencia, no el de estados." },
          ],
          quiz: {
            question: "Lee la transición devolver [con retraso] / calcular multa del diagrama. ¿Qué significa?",
            options: [
              "El sistema calcula la multa como condición para permitir el evento devolver",
              "\"Con retraso\" es la acción que el sistema ejecuta al recibir el evento devolver",
              "Al ocurrir el evento devolver, SI hay retraso, el objeto transita y el sistema ejecuta la acción calcular multa",
              "\"Calcular multa\" es el nombre del estado al que llega el préstamo tras devolverse",
            ],
            correct: 2,
            ok: "La lectura correcta respeta el orden evento [guarda] / acción: devolver es lo que dispara la transición, [con retraso] es la condición que debe cumplirse, y calcular multa es lo que el sistema ejecuta al cruzarla — no un estado ni una condición previa al evento.",
            bad: "No inviertas el orden: la guarda no es la acción (va antes de la barra, no después), la acción no es una condición para el evento (ocurre DESPUÉS de que el evento ya disparó la transición), y \"calcular multa\" no es un estado — es lo que el sistema hace, no dónde queda.",
          },
          extra: {
            type: "match",
            prompt: "Empareja cada pieza de una transición con su rol.",
            payload: {
              left: ["Estado", "Evento", "Guarda", "Acción"],
              right: [
                "Lo que el sistema ejecuta al cruzar la transición, como calcular multa",
                "La condición entre corchetes que debe cumplirse para que la transición ocurra",
                "Una condición estable en la que el objeto permanece un tiempo, como Activo o Vencido",
                "Lo que dispara la transición, como recibir la orden de devolver",
              ],
            },
            answer: { pairs: [[0, 2], [1, 3], [2, 1], [3, 0]] },
            ok: "Estado es dónde el objeto permanece (Activo, Vencido); evento es lo que dispara el cambio; guarda es la condición entre corchetes que decide si la transición ocurre; acción es lo que el sistema ejecuta al cruzarla.",
            bad: "No mezcles evento con guarda: el evento siempre dispara la transición, la guarda solo la permite o la bloquea; y la acción no es un estado — ocurre DURANTE el cruce, no es un lugar donde el objeto se queda.",
          },
        },
      ],
    },
  ],
};
