const K = 'color: var(--accent-violet)';
const S = 'color: var(--accent-cyan)';
const N = 'color: var(--accent-amber)';
const C = 'color: var(--text-tertiary)';

export default {
  id: "web",
  subject: "Desarrollo web",
  tone: "amber",
  title: "HTML, CSS y JavaScript",
  description: "Construye para el navegador: estructura con HTML, estilo con CSS y comportamiento con JavaScript.",
  order: 6,
  prereq: null,
  units: [
    {
      id: "web-u1",
      name: "Unidad 1 · HTML",
      lessons: [
        {
          id: "web-l1",
          title: "Estructura de un documento",
          mins: 14,
          content: [
            { type: "p", html: "Todo documento <code>HTML</code> comienza con <code>&lt;!DOCTYPE html&gt;</code>, que le indica al navegador qué versión de HTML usar. Le sigue la etiqueta raíz <code>&lt;html&gt;</code>, que contiene dos secciones: <code>&lt;head&gt;</code> (metadatos, no visibles) y <code>&lt;body&gt;</code> (el contenido visible de la página)." },
            { type: "p", html: "Cada etiqueta HTML se abre y se cierra: <code>&lt;p&gt;texto&lt;/p&gt;</code>. Algunas etiquetas, de <code>elemento vacío</code>, no tienen contenido ni cierre, como <code>&lt;img&gt;</code> o <code>&lt;br&gt;</code>." },
            { type: "code", lines: [
              `&lt;!DOCTYPE <span style="${K}">html</span>&gt;`,
              `&lt;<span style="${K}">html</span> lang=<span style="${S}">"es"</span>&gt;`,
              `  &lt;<span style="${K}">head</span>&gt;`,
              `    &lt;<span style="${K}">meta</span> charset=<span style="${S}">"UTF-8"</span>&gt;`,
              `    &lt;<span style="${K}">title</span>&gt;Mi página&lt;/<span style="${K}">title</span>&gt;`,
              `  &lt;/<span style="${K}">head</span>&gt;`,
              `  &lt;<span style="${K}">body</span>&gt;`,
              `    &lt;<span style="${K}">h1</span>&gt;¡Hola!&lt;/<span style="${K}">h1</span>&gt;`,
              `  &lt;/<span style="${K}">body</span>&gt;`,
              `&lt;/<span style="${K}">html</span>&gt;`,
            ]},
          ],
          quiz: {
            question: "¿Qué contiene la sección <head> de un documento HTML, a diferencia de <body>?",
            options: [
              "El contenido visible principal de la página",
              "El código JavaScript que siempre debe ejecutarse primero",
              "Únicamente las imágenes del sitio",
              "Metadatos como el título y la codificación de caracteres, que no se muestran directamente en la página",
            ],
            correct: 3,
            ok: "<head> guarda metadatos (título, charset, enlaces a hojas de estilo) que el navegador usa pero no muestra como contenido visible; eso vive en <body>.",
            bad: "El contenido visible va en <body>, no en <head>; <head> no se limita a imágenes ni obliga a que el JavaScript se declare ahí.",
          },
          extra: {
            type: "order",
            prompt: "Ordena las líneas para construir la estructura básica de un documento HTML, desde el doctype hasta el body.",
            payload: {
              lines: [
                { id: "c", html: `  &lt;<span style="${K}">head</span>&gt;&lt;<span style="${K}">title</span>&gt;Mi página&lt;/<span style="${K}">title</span>&gt;&lt;/<span style="${K}">head</span>&gt;` },
                { id: "a", html: `&lt;!DOCTYPE <span style="${K}">html</span>&gt;` },
                { id: "d", html: `  &lt;<span style="${K}">body</span>&gt;&lt;<span style="${K}">h1</span>&gt;¡Hola!&lt;/<span style="${K}">h1</span>&gt;&lt;/<span style="${K}">body</span>&gt;` },
                { id: "b", html: `&lt;<span style="${K}">html</span> lang=<span style="${S}">"es"</span>&gt;` },
              ],
            },
            answer: { order: ["a", "b", "c", "d"] },
            ok: "El documento empieza con el doctype, luego se abre <html>, después va <head> con los metadatos, y por último <body> con el contenido visible.",
            bad: "El doctype siempre va primero, antes de <html>; y <head> debe aparecer antes que <body>, no al revés.",
          },
        },
        {
          id: "web-l2",
          title: "Etiquetas semánticas",
          mins: 16,
          content: [
            { type: "p", html: "Las <code>etiquetas semánticas</code> describen el significado de una sección de contenido, no solo su apariencia. En lugar de envolver todo en <code>&lt;div&gt;</code> genéricos, HTML5 ofrece etiquetas como <code>&lt;header&gt;</code>, <code>&lt;nav&gt;</code>, <code>&lt;main&gt;</code>, <code>&lt;article&gt;</code> y <code>&lt;footer&gt;</code>." },
            { type: "p", html: "Usar etiquetas semánticas mejora la <code>accesibilidad</code> (los lectores de pantalla entienden mejor la estructura) y el <code>SEO</code> (los buscadores identifican el contenido principal con más precisión)." },
            { type: "code", lines: [
              `&lt;<span style="${K}">header</span>&gt;`,
              `  &lt;<span style="${K}">nav</span>&gt;...&lt;/<span style="${K}">nav</span>&gt;`,
              `&lt;/<span style="${K}">header</span>&gt;`,
              `&lt;<span style="${K}">main</span>&gt;`,
              `  &lt;<span style="${K}">article</span>&gt;`,
              `    &lt;<span style="${K}">h2</span>&gt;Título del artículo&lt;/<span style="${K}">h2</span>&gt;`,
              `  &lt;/<span style="${K}">article</span>&gt;`,
              `&lt;/<span style="${K}">main</span>&gt;`,
              `&lt;<span style="${K}">footer</span>&gt;© 2026&lt;/<span style="${K}">footer</span>&gt;`,
            ]},
          ],
          quiz: {
            question: "¿Por qué es preferible usar <article> o <nav> en lugar de envolver todo el contenido en <div> genéricos?",
            options: [
              "Porque comunican el significado de cada sección, mejorando la accesibilidad y el SEO",
              "Porque <article> y <nav> se procesan más rápido que <div> en el navegador",
              "Porque <div> no admite atributos como class o id",
              "Porque <div> ya no es válido en HTML5",
            ],
            correct: 0,
            ok: "Las etiquetas semánticas describen qué es cada sección, algo que lectores de pantalla y buscadores aprovechan; <div> es válido pero no aporta ese significado.",
            bad: "<div> sigue siendo válido en HTML5 y sí admite class/id, y no hay una diferencia relevante de velocidad de renderizado; la ventaja real es semántica.",
          },
          extra: {
            type: "match",
            prompt: "Empareja cada etiqueta semántica con su uso.",
            payload: {
              left: ["<header>", "<nav>", "<main>", "<footer>"],
              right: [
                "Contiene el contenido principal y único de la página, sin repetirse en otras páginas",
                "Información de cierre, como derechos de autor o enlaces secundarios, al final de la página",
                "Encabezado introductorio de la página o de una sección, con logo o título",
                "Agrupa los enlaces de navegación principal del sitio",
              ],
            },
            answer: { pairs: [[0, 2], [1, 3], [2, 0], [3, 1]] },
            ok: "<header> introduce la página o sección, <nav> agrupa la navegación principal, <main> contiene el contenido único y central, y <footer> cierra con información secundaria.",
            bad: "No confundas <main> (contenido central único) con <header> (encabezado introductorio); y <nav> se reserva para los enlaces de navegación, no para el cierre de la página.",
          },
        },
        {
          id: "web-l3",
          title: "Formularios",
          mins: 18,
          content: [
            { type: "p", html: "Un <code>formulario</code> se declara con <code>&lt;form&gt;</code> y agrupa <code>controles de entrada</code> como <code>&lt;input&gt;</code>, <code>&lt;select&gt;</code> y <code>&lt;textarea&gt;</code>. El atributo <code>type</code> de <code>&lt;input&gt;</code> determina qué clase de dato se espera: <code>text</code>, <code>email</code>, <code>password</code>, <code>checkbox</code>, entre otros." },
            { type: "p", html: "Cada campo debería tener una etiqueta <code>&lt;label&gt;</code> asociada mediante el atributo <code>for</code>, que debe coincidir con el <code>id</code> del campo: así el usuario puede hacer clic en el texto de la etiqueta para enfocar el campo, y los lectores de pantalla anuncian correctamente qué representa cada control." },
            { type: "code", lines: [
              `&lt;<span style="${K}">form</span>&gt;`,
              `  &lt;<span style="${K}">label</span> for=<span style="${S}">"correo"</span>&gt;Correo:&lt;/<span style="${K}">label</span>&gt;`,
              `  &lt;<span style="${K}">input</span> type=<span style="${S}">"email"</span> id=<span style="${S}">"correo"</span> name=<span style="${S}">"correo"</span> required&gt;`,
              `  &lt;<span style="${K}">button</span> type=<span style="${S}">"submit"</span>&gt;Enviar&lt;/<span style="${K}">button</span>&gt;`,
              `&lt;/<span style="${K}">form</span>&gt;`,
            ]},
          ],
          quiz: {
            question: '¿Para qué sirve que <label for="correo"> coincida con id="correo" en el <input> correspondiente?',
            options: [
              "Para que el formulario se envíe sin necesidad de un botón submit",
              "Para que el navegador aplique automáticamente el atributo required",
              "Para vincular la etiqueta con el campo: al hacer clic en el texto se enfoca el input, y los lectores de pantalla lo anuncian correctamente",
              "Es solo una convención visual sin efecto funcional",
            ],
            correct: 2,
            ok: "El atributo for vincula la etiqueta con el input que comparte ese id: mejora la usabilidad (clic en el texto) y la accesibilidad (anuncio correcto por lectores de pantalla).",
            bad: "El vínculo no agrega required automáticamente ni permite enviar el formulario sin botón; y sí tiene un efecto funcional real, no es solo decorativo.",
          },
          extra: {
            type: "blanks",
            prompt: "Completa el formulario para que la etiqueta se vincule al campo de correo y el input tenga el tipo correcto.",
            payload: {
              code: [
                `&lt;<span style="${K}">form</span>&gt;`,
                `  &lt;<span style="${K}">label</span> for=<span style="${S}">"<b0>"</span>&gt;Correo:&lt;/<span style="${K}">label</span>&gt;`,
                `  &lt;<span style="${K}">input</span> type=<span style="${S}">"<b1>"</span> id=<span style="${S}">"correo"</span> name=<span style="${S}">"correo"</span> required&gt;`,
                `  &lt;<span style="${K}">button</span> type=<span style="${S}">"submit"</span>&gt;Enviar&lt;/<span style="${K}">button</span>&gt;`,
                `&lt;/<span style="${K}">form</span>&gt;`,
              ],
              bank: ["correo", "email", "password", "usuario"],
            },
            answer: { blanks: ["correo", "email"] },
            ok: "for=\"correo\" debe coincidir con el id=\"correo\" del input para vincular la etiqueta, y type=\"email\" es el tipo de dato esperado en ese campo.",
            bad: "Si for no coincide exactamente con el id, la etiqueta no se vincula al campo; y type=\"password\" ocultaría el texto, algo que no corresponde a un campo de correo.",
          },
        },
        {
          id: "web-l4",
          title: "Imágenes y enlaces",
          mins: 14,
          content: [
            { type: "p", html: "La etiqueta <code>&lt;img&gt;</code> inserta una imagen; requiere el atributo <code>src</code> (la ruta del archivo) y debería incluir siempre <code>alt</code>, un texto alternativo que describe la imagen para lectores de pantalla y que se muestra si la imagen no carga." },
            { type: "p", html: "La etiqueta <code>&lt;a&gt;</code> crea un enlace; su atributo <code>href</code> indica el destino, que puede ser otra página, una sección de la misma página (<code>#id</code>) o una dirección externa." },
            { type: "code", lines: [
              `&lt;<span style="${K}">img</span> src=<span style="${S}">"logo.png"</span> alt=<span style="${S}">"Logo de la empresa"</span>&gt;`,
              `&lt;<span style="${K}">a</span> href=<span style="${S}">"https://coding.dev"</span>&gt;Visita el sitio&lt;/<span style="${K}">a</span>&gt;`,
              `&lt;<span style="${K}">a</span> href=<span style="${S}">"#seccion-2"</span>&gt;Ir a la sección 2&lt;/<span style="${K}">a</span>&gt;`,
            ]},
          ],
          quiz: {
            question: "¿Por qué es importante incluir el atributo alt en una etiqueta <img>?",
            options: [
              "Porque sin alt la imagen no se muestra en ningún navegador",
              "Porque describe la imagen para lectores de pantalla y se muestra si la imagen no carga",
              "Porque alt reemplaza al atributo src",
              "Porque reduce el tamaño del archivo de imagen",
            ],
            correct: 1,
            ok: "alt aporta un texto alternativo accesible: los lectores de pantalla lo leen, y el navegador lo muestra si src falla en cargar.",
            bad: "La imagen sí se muestra sin alt (aunque sin ser accesible), alt no reemplaza a src, y no tiene ningún efecto sobre el peso del archivo de imagen.",
          },
          extra: {
            type: "blanks",
            prompt: "Completa el atributo alt de la imagen y el href del enlace.",
            payload: {
              code: [
                `&lt;<span style="${K}">img</span> src=<span style="${S}">"logo.png"</span> alt=<span style="${S}">"<b0>"</span>&gt;`,
                `&lt;<span style="${K}">a</span> href=<span style="${S}">"<b1>"</span>&gt;Visita el sitio&lt;/<span style="${K}">a</span>&gt;`,
              ],
              bank: ["Logo de la empresa", "https://coding.dev", "logo.png", "#seccion-2"],
            },
            answer: { blanks: ["Logo de la empresa", "https://coding.dev"] },
            ok: "alt describe la imagen para accesibilidad (\"Logo de la empresa\"), y href indica el destino del enlace, aquí una URL externa completa.",
            bad: "alt no debe repetir el nombre del archivo (logo.png); necesita describir la imagen. Y href necesita una URL o ruta válida, no el texto visible del enlace.",
          },
        },
      ],
    },
    {
      id: "web-u2",
      name: "Unidad 2 · CSS",
      lessons: [
        {
          id: "web-l5",
          title: "Selectores y especificidad",
          mins: 18,
          content: [
            { type: "p", html: "Un <code>selector</code> CSS elige qué elementos HTML reciben un estilo. Los más básicos son el selector de <code>etiqueta</code> (<code>p</code>), de <code>clase</code> (<code>.tarjeta</code>) y de <code>id</code> (<code>#header</code>)." },
            { type: "p", html: "Cuando varias reglas aplican al mismo elemento, la <code>especificidad</code> decide cuál gana: un id pesa más que una clase, y una clase pesa más que un selector de etiqueta. Ante un empate, gana la regla declarada más abajo en la hoja de estilos." },
            { type: "code", lines: [
              `<span style="${K}">p</span> {`,
              `  <span style="${S}">color</span>: <span style="${S}">blue</span>;`,
              `}`,
              `<span style="${K}">.tarjeta</span> {`,
              `  <span style="${S}">color</span>: <span style="${S}">green</span>;`,
              `}`,
              `<span style="${K}">#header</span> {`,
              `  <span style="${S}">color</span>: <span style="${S}">red</span>;`,
              `}`,
            ]},
          ],
          quiz: {
            question: 'Si p { color: blue; }, .tarjeta { color: green; } y #header { color: red; } aplican todas al mismo <p id="header" class="tarjeta">, ¿de qué color se muestra el texto?',
            options: [
              "Rojo (red), porque el selector de id tiene la mayor especificidad",
              "Azul (blue), porque el selector de etiqueta se procesa primero",
              "Verde (green), porque las clases siempre ganan sobre etiquetas e ids",
              "Ninguno de los tres, el navegador usa el color por defecto",
            ],
            correct: 0,
            ok: "Un selector de id (#header) tiene mayor especificidad que uno de clase (.tarjeta) o de etiqueta (p), así que su declaración gana: el texto se muestra en rojo.",
            bad: "El orden de escritura no decide aquí porque la especificidad se evalúa primero, y las clases no superan a los ids; el id es el que gana.",
          },
          extra: {
            type: "match",
            prompt: "Empareja cada tipo de selector con su nivel de especificidad.",
            payload: {
              left: ["Selector de etiqueta (p)", "Selector de clase (.tarjeta)", "Selector de id (#header)", "Estilo inline (style=\"...\")"],
              right: [
                "Mayor especificidad que clase o etiqueta; debe ser único por página",
                "La especificidad más alta de todas, escrita directamente en el atributo del elemento",
                "La especificidad más baja de las cuatro; afecta a todos los elementos de ese tipo",
                "Especificidad media; se reutiliza en varios elementos que comparten una característica",
              ],
            },
            answer: { pairs: [[0, 2], [1, 3], [2, 0], [3, 1]] },
            ok: "El orden de especificidad de menor a mayor es: etiqueta, clase, id, inline; cada nivel gana sobre el anterior cuando hay conflicto.",
            bad: "No inviertas el orden: un selector de etiqueta nunca gana sobre uno de clase o id, y el estilo inline supera a los tres cuando compiten.",
          },
        },
        {
          id: "web-l6",
          title: "El modelo de caja",
          mins: 18,
          content: [
            { type: "p", html: "El <code>modelo de caja</code> (box model) describe cómo CSS calcula el tamaño de cada elemento: el <code>content</code> (contenido), rodeado por <code>padding</code> (espacio interno), <code>border</code> (borde) y <code>margin</code> (espacio externo, fuera del borde)." },
            { type: "p", html: "Por defecto, <code>width</code> y <code>height</code> solo definen el tamaño del contenido; padding y border se suman por fuera. La propiedad <code>box-sizing: border-box</code> cambia esto para que width incluya también el padding y el borde." },
            { type: "code", lines: [
              `<span style="${K}">.tarjeta</span> {`,
              `  <span style="${S}">width</span>: <span style="${N}">200px</span>;`,
              `  <span style="${S}">padding</span>: <span style="${N}">16px</span>;`,
              `  <span style="${S}">border</span>: <span style="${N}">2px</span> <span style="${S}">solid</span> <span style="${S}">gray</span>;`,
              `  <span style="${S}">box-sizing</span>: <span style="${S}">border-box</span>;`,
              `}`,
            ]},
            { type: "note", text: "Con box-sizing: border-box, el ancho total renderizado de .tarjeta sigue siendo 200px, aunque tenga padding y borde; sin border-box, el ancho real sería 236px." },
          ],
          quiz: {
            question: "Con .tarjeta { width: 200px; padding: 16px; border: 2px solid gray; box-sizing: border-box; }, ¿cuál es el ancho total que ocupa el elemento en pantalla?",
            options: [
              "236px, porque padding y border siempre se suman al width",
              "168px, porque box-sizing resta el padding del width",
              "216px, sumando solo el padding",
              "200px, porque border-box incluye el padding y el borde dentro del width declarado",
            ],
            correct: 3,
            ok: "box-sizing: border-box redefine width para que incluya padding y border dentro de esos 200px, en lugar de sumarlos por fuera.",
            bad: "Sin border-box sí se sumarían llegando a 236px, pero border-box existe justamente para evitarlo; no resta el padding ni suma solo una parte.",
          },
          extra: {
            type: "blanks",
            prompt: "Completa las propiedades del modelo de caja: espacio interno y borde.",
            payload: {
              code: [
                `<span style="${K}">.tarjeta</span> {`,
                `  <span style="${S}">width</span>: <span style="${N}">200px</span>;`,
                `  <b0>: <span style="${N}">16px</span>;`,
                `  <b1>: <span style="${N}">2px</span> <span style="${S}">solid</span> <span style="${S}">gray</span>;`,
                `  <span style="${S}">margin</span>: <span style="${N}">24px</span>;`,
                `}`,
              ],
              bank: ["padding", "border", "margin", "outline"],
            },
            answer: { blanks: ["padding", "border"] },
            ok: "padding es el espacio interno entre el contenido y el borde, y border dibuja el borde visible alrededor del contenido y el padding.",
            bad: "No confundas padding (espacio interno) con margin (espacio externo, fuera del borde); border es el trazo visible entre ambos.",
          },
        },
        {
          id: "web-l7",
          title: "Flexbox",
          mins: 20,
          content: [
            { type: "p", html: "<code>Flexbox</code> es un modelo de layout de una dimensión: organiza los elementos hijos de un contenedor en una fila o columna, distribuyendo el espacio disponible entre ellos. Se activa con <code>display: flex</code> en el contenedor." },
            { type: "p", html: "La propiedad <code>justify-content</code> controla la alineación en el <code>eje principal</code> (horizontal por defecto); <code>align-items</code> controla la alineación en el <code>eje transversal</code> (vertical por defecto)." },
            { type: "code", lines: [
              `<span style="${C}">/* Distribuye los hijos con espacio entre ellos y los centra verticalmente */</span>`,
              `<span style="${K}">.contenedor</span> {`,
              `  <span style="${S}">display</span>: <span style="${S}">flex</span>;`,
              `  <span style="${S}">justify-content</span>: <span style="${S}">space-between</span>;`,
              `  <span style="${S}">align-items</span>: <span style="${S}">center</span>;`,
              `  <span style="${S}">gap</span>: <span style="${N}">12px</span>;`,
              `}`,
            ]},
          ],
          quiz: {
            question: "En .contenedor { display: flex; justify-content: space-between; align-items: center; }, ¿qué controla justify-content?",
            options: [
              "El color de fondo del contenedor",
              "La alineación de los elementos hijos en el eje principal del contenedor flex",
              "El número de columnas del contenedor",
              "El tamaño de la fuente de los elementos hijos",
            ],
            correct: 1,
            ok: "justify-content distribuye el espacio y alinea los elementos hijos a lo largo del eje principal; por ejemplo, space-between separa el primero y el último hacia los extremos.",
            bad: "justify-content no afecta color, columnas ni tamaño de fuente: es una propiedad de alineación específica del eje principal en flexbox.",
          },
          extra: {
            type: "blanks",
            prompt: "Completa el contenedor flex: el modo de layout y la distribución en el eje principal.",
            payload: {
              code: [
                `<span style="${K}">.contenedor</span> {`,
                `  <span style="${S}">display</span>: <b0>;`,
                `  <span style="${S}">justify-content</span>: <b1>;`,
                `  <span style="${S}">align-items</span>: <span style="${S}">center</span>;`,
                `  <span style="${S}">gap</span>: <span style="${N}">12px</span>;`,
                `}`,
              ],
              bank: ["flex", "space-between", "block", "flex-start"],
            },
            answer: { blanks: ["flex", "space-between"] },
            ok: "display: flex activa el layout flexbox en el contenedor, y justify-content: space-between separa los elementos hacia los extremos del eje principal.",
            bad: "Sin display: flex las demás propiedades no tienen efecto; y space-between distribuye espacio entre elementos, no los centra ni los junta al inicio.",
          },
        },
        {
          id: "web-l8",
          title: "Responsive y media queries",
          mins: 20,
          content: [
            { type: "p", html: "El <code>diseño responsive</code> adapta la presentación de una página al tamaño de pantalla del dispositivo que la muestra. Una <code>media query</code> aplica un bloque de reglas CSS solo cuando se cumple una condición, como un ancho máximo de viewport." },
            { type: "p", html: "La etiqueta <code>&lt;meta name=\"viewport\" content=\"width=device-width, initial-scale=1\"&gt;</code> en el <code>&lt;head&gt;</code> es indispensable: sin ella, los navegadores móviles renderizan la página como si fuera de escritorio y luego la reducen, ignorando tus media queries." },
            { type: "code", lines: [
              `<span style="${K}">.columna</span> {`,
              `  <span style="${S}">width</span>: <span style="${N}">50%</span>;`,
              `}`,
              ``,
              `<span style="${K}">@media</span> (max-width: <span style="${N}">600px</span>) {`,
              `  <span style="${K}">.columna</span> {`,
              `    <span style="${S}">width</span>: <span style="${N}">100%</span>;`,
              `  }`,
              `}`,
            ]},
          ],
          quiz: {
            question: "¿Qué hace @media (max-width: 600px) { .columna { width: 100%; } }?",
            options: [
              "Aplica width: 100% a .columna siempre, sin importar el tamaño de pantalla",
              "Elimina la clase .columna en pantallas grandes",
              "Aplica width: 100% a .columna solo cuando el ancho del viewport es de 600px o menos",
              "Aumenta la resolución de las imágenes dentro de .columna",
            ],
            correct: 2,
            ok: "La media query condiciona ese bloque de reglas a que el viewport mida como máximo 600px; fuera de esa condición, esas reglas no se aplican.",
            bad: "La regla no es incondicional, no elimina la clase, y no tiene relación con la resolución de imágenes: solo activa esos estilos bajo esa condición de ancho.",
          },
          extra: {
            type: "blanks",
            prompt: "Completa el umbral de la media query y el ancho que toma .columna dentro de ella.",
            payload: {
              code: [
                `<span style="${K}">.columna</span> {`,
                `  <span style="${S}">width</span>: <span style="${N}">50%</span>;`,
                `}`,
                ``,
                `<span style="${K}">@media</span> (max-width: <b0>) {`,
                `  <span style="${K}">.columna</span> {`,
                `    <span style="${S}">width</span>: <b1>;`,
                `  }`,
                `}`,
              ],
              bank: ["600px", "100%", "50%", "768px"],
            },
            answer: { blanks: ["600px", "100%"] },
            ok: "La media query se activa cuando el viewport mide 600px o menos, y dentro de ella .columna pasa a ocupar el 100% del ancho disponible.",
            bad: "Si el umbral no fuera 600px, la regla se activaría en un punto distinto; y 50% dejaría la columna igual que fuera de la media query, sin adaptarse a pantallas pequeñas.",
          },
        },
      ],
    },
    {
      id: "web-u3",
      name: "Unidad 3 · JavaScript",
      lessons: [
        {
          id: "web-l9",
          title: "Variables y funciones en JS",
          mins: 18,
          content: [
            { type: "p", html: "En JavaScript moderno, declaras variables con <code>let</code> (si su valor cambiará) o <code>const</code> (si no cambiará). Evita <code>var</code>: su comportamiento de ámbito es menos predecible que el de let y const." },
            { type: "p", html: "Una <code>función</code> agrupa código reutilizable. Puedes declararla con la palabra clave <code>function</code> o como una <code>función flecha</code> (<code>=&gt;</code>), una sintaxis más compacta muy usada en JavaScript moderno." },
            { type: "code", lines: [
              `<span style="${C}">// Convierte un precio base en su valor con IVA incluido</span>`,
              `<span style="${K}">const</span> IVA = <span style="${N}">0.19</span>;`,
              `<span style="${K}">let</span> precio = <span style="${N}">1000</span>;`,
              ``,
              `<span style="${K}">function</span> calcularTotal(precio) {`,
              `  <span style="${K}">return</span> precio * (<span style="${N}">1</span> + IVA);`,
              `}`,
              ``,
              `<span style="${K}">const</span> calcularTotalFlecha = (precio) =&gt; precio * (<span style="${N}">1</span> + IVA);`,
            ]},
          ],
          quiz: {
            question: "¿Por qué se recomienda usar let o const en lugar de var al declarar variables en JavaScript moderno?",
            options: [
              "Porque var ya no está soportado en ningún navegador",
              "Porque var no permite guardar números",
              "Porque let y const tienen un ámbito de bloque más predecible que var",
              "Porque let y const se ejecutan más rápido en cualquier caso",
            ],
            correct: 2,
            ok: "let y const respetan el ámbito de bloque ({ }), mientras que var tiene un comportamiento de ámbito de función que suele generar errores sutiles; por eso se prefieren.",
            bad: "var sigue siendo válido en todos los navegadores y sí admite números; la razón real es la previsibilidad del ámbito, no la velocidad de ejecución.",
          },
          extra: {
            type: "blanks",
            prompt: "Completa la declaración: una constante y una función flecha.",
            payload: {
              code: [
                `<span style="${K}">const</span> IVA = <span style="${N}">0.19</span>;`,
                ``,
                `<b0> calcularTotal = (precio) <b1> precio * (<span style="${N}">1</span> + IVA);`,
              ],
              bank: ["const", "=>", "let", "function"],
            },
            answer: { blanks: ["const", "=>"] },
            ok: "const declara una variable cuyo valor no volverá a reasignarse, y => define una función flecha de forma compacta.",
            bad: "let permitiría reasignar la función más adelante, algo que no buscamos aquí; y function no usa la sintaxis de flecha =>, que es la que completa esta declaración.",
          },
        },
        {
          id: "web-l10",
          title: "El DOM",
          mins: 20,
          content: [
            { type: "p", html: "El <code>DOM</code> (Document Object Model) es la representación en memoria del documento HTML que el navegador construye y que JavaScript puede leer y modificar. Cada etiqueta HTML se convierte en un <code>nodo</code> dentro de un árbol." },
            { type: "p", html: "Para acceder a un elemento usas métodos como <code>document.querySelector</code> (devuelve el primer elemento que coincide con un selector CSS) o <code>document.getElementById</code>. Una vez obtenida la referencia, puedes leer o cambiar su contenido y sus estilos." },
            { type: "code", lines: [
              `<span style="${K}">const</span> titulo = document.querySelector(<span style="${S}">"h1"</span>);`,
              `titulo.textContent = <span style="${S}">"Nuevo título"</span>;`,
              `titulo.style.color = <span style="${S}">"blue"</span>;`,
              ``,
              `<span style="${K}">const</span> lista = document.getElementById(<span style="${S}">"lista"</span>);`,
              `<span style="${K}">const</span> item = document.createElement(<span style="${S}">"li"</span>);`,
              `item.textContent = <span style="${S}">"Nuevo elemento"</span>;`,
              `lista.appendChild(item);`,
            ]},
          ],
          quiz: {
            question: '¿Qué hace document.querySelector("h1").textContent = "Nuevo título";?',
            options: [
              "Crea un nuevo elemento h1 en el documento",
              'Busca el primer h1 del documento y reemplaza su texto por "Nuevo título"',
              "Cambia el color del primer h1 encontrado",
              "Busca todos los elementos h1 y los elimina",
            ],
            correct: 1,
            ok: "querySelector devuelve el primer elemento que coincide con el selector \"h1\"; asignar textContent reemplaza el texto que contiene ese elemento.",
            bad: "No crea ni elimina elementos, y no modifica el color (eso requeriría .style.color); solo cambia el contenido de texto del primer h1 encontrado.",
          },
          extra: {
            type: "blanks",
            prompt: "Completa el método para seleccionar el elemento y la propiedad para cambiar su texto.",
            payload: {
              code: [
                `<span style="${K}">const</span> titulo = document.<b0>(<span style="${S}">"h1"</span>);`,
                `titulo.<b1> = <span style="${S}">"Nuevo título"</span>;`,
              ],
              bank: ["querySelector", "textContent", "querySelectorAll", "innerHTML"],
            },
            answer: { blanks: ["querySelector", "textContent"] },
            ok: "querySelector busca el primer elemento que coincide con el selector, y textContent reemplaza el texto que contiene ese elemento.",
            bad: "querySelectorAll devolvería una lista de elementos, no uno solo; e innerHTML interpretaría el valor como HTML, no como texto plano.",
          },
        },
        {
          id: "web-l11",
          title: "Eventos",
          mins: 18,
          content: [
            { type: "p", html: "Un <code>evento</code> es una acción que ocurre en la página, como un clic, una tecla presionada o el envío de un formulario. Para reaccionar a un evento, registras un <code>listener</code> con <code>addEventListener</code>, indicando el tipo de evento y una función que se ejecutará cuando ocurra." },
            { type: "code", lines: [
              `<span style="${K}">const</span> boton = document.querySelector(<span style="${S}">"#enviar"</span>);`,
              `boton.addEventListener(<span style="${S}">"click"</span>, () =&gt; {`,
              `  console.log(<span style="${S}">"¡Botón presionado!"</span>);`,
              `});`,
            ]},
            { type: "note", text: "La función que pasas a addEventListener no se ejecuta al registrarla: el navegador la guarda y la invoca solo cuando ocurre el evento indicado." },
          ],
          quiz: {
            question: '¿Cuándo se ejecuta la función que pasas como segundo argumento a boton.addEventListener("click", funcion)?',
            options: [
              "Nunca, a menos que se llame manualmente",
              "Inmediatamente, en el momento en que se ejecuta addEventListener",
              "Solo una vez, la primera vez que carga la página",
              "Cada vez que el usuario hace clic en boton, después de haberla registrado",
            ],
            correct: 3,
            ok: "addEventListener registra la función como respuesta al evento; el navegador la invoca automáticamente cada vez que ese evento (click) ocurre sobre boton.",
            bad: "No se ejecuta al registrarla ni una sola vez fija: se ejecuta cada vez que ocurre el evento, y sí se llama automáticamente, no hace falta invocarla a mano.",
          },
          extra: {
            type: "blanks",
            prompt: "Completa el método para registrar el listener y el nombre del evento de clic.",
            payload: {
              code: [
                `<span style="${K}">const</span> boton = document.querySelector(<span style="${S}">"#enviar"</span>);`,
                `boton.<b0>(<span style="${S}">"<b1>"</span>, () =&gt; {`,
                `  console.log(<span style="${S}">"¡Botón presionado!"</span>);`,
                `});`,
              ],
              bank: ["addEventListener", "click", "removeEventListener", "submit"],
            },
            answer: { blanks: ["addEventListener", "click"] },
            ok: "addEventListener registra la función como respuesta al evento, y \"click\" indica que se ejecutará cuando el usuario haga clic en boton.",
            bad: "removeEventListener quitaría un listener existente, no lo registraría; y \"submit\" es el evento de un formulario, no de un clic en un botón.",
          },
        },
        {
          id: "web-l12",
          title: "fetch y APIs",
          mins: 22,
          content: [
            { type: "p", html: "<code>fetch</code> es la función estándar de JavaScript para hacer peticiones HTTP desde el navegador, por ejemplo para consumir una <code>API</code> externa. Devuelve una <code>Promise</code>, un objeto que representa un resultado que estará disponible en el futuro." },
            { type: "p", html: "Como fetch es asíncrono, se combina con <code>async</code>/<code>await</code> para escribir el código en un estilo secuencial y legible. Siempre conviene manejar errores, por ejemplo con <code>try/catch</code>, porque la red puede fallar." },
            { type: "code", lines: [
              `<span style="${K}">async function</span> obtenerUsuarios() {`,
              `  <span style="${K}">try</span> {`,
              `    <span style="${K}">const</span> respuesta = <span style="${K}">await</span> fetch(<span style="${S}">"https://api.ejemplo.com/usuarios"</span>);`,
              `    <span style="${K}">const</span> usuarios = <span style="${K}">await</span> respuesta.json();`,
              `    console.log(usuarios);`,
              `  } <span style="${K}">catch</span> (error) {`,
              `    console.log(<span style="${S}">"Error al obtener usuarios"</span>);`,
              `  }`,
              `}`,
            ]},
          ],
          quiz: {
            question: "¿Por qué se envuelve la llamada a fetch dentro de un bloque try/catch en obtenerUsuarios()?",
            options: [
              "Para capturar y manejar errores de red o de la petición sin que el programa se detenga",
              "Para que la función se ejecute más rápido",
              "Porque fetch nunca funciona sin try/catch",
              "Porque await solo puede usarse dentro de un try",
            ],
            correct: 0,
            ok: "Las peticiones de red pueden fallar (sin conexión, servidor caído); try/catch permite capturar ese error y manejarlo en lugar de que la aplicación se rompa.",
            bad: "fetch sí puede usarse sin try/catch (solo que los errores no se manejarían), no afecta la velocidad, y await no exige estar dentro de un try: la razón es el manejo de errores.",
          },
          extra: {
            type: "order",
            prompt: "Ordena la cadena de promesas: hacer la petición, convertir la respuesta a JSON, usar los datos y manejar errores.",
            payload: {
              lines: [
                { id: "c", html: `.then((datos) =&gt; console.log(datos))` },
                { id: "a", html: `fetch(<span style="${S}">"https://api.ejemplo.com/usuarios"</span>)` },
                { id: "d", html: `.catch((error) =&gt; console.log(<span style="${S}">"Error al obtener usuarios"</span>))` },
                { id: "b", html: `.then((res) =&gt; res.json())` },
              ],
            },
            answer: { order: ["a", "b", "c", "d"] },
            ok: "Primero se hace la petición con fetch, luego se convierte la respuesta a JSON con .then(res => res.json()), después se usan los datos en otro .then, y por último .catch maneja cualquier error de la cadena.",
            bad: "No puedes usar los datos antes de convertir la respuesta con res.json(), y catch debe ir al final para capturar errores de cualquier paso anterior de la cadena.",
          },
        },
      ],
    },
  ],
};
